### ISSUE TITLE
Standarized Terminology (Business Glossary)

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#107]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5220004367

---

A Business Glossary is an efficient, scalable, and reliable way of curating and standardizing critical business terminology for every stakeholder in an organization.

- [x] [Data Dictionary](https://cat.data.fin.gov.bc.ca/documentation/terminology#data-dictionary)
- [x] [Data Catalogue](https://cat.data.fin.gov.bc.ca/documentation/terminology#data-catalogue)
- [x] [Data Custodian](https://cat.data.fin.gov.bc.ca/documentation/terminology#data-custodian)
- [x] [Data Steward](https://cat.data.fin.gov.bc.ca/documentation/terminology#data-steward)
- [x] [Metadata record](https://cat.data.fin.gov.bc.ca/documentation/terminology#metadata-record)
- [x] [Metadata editor](https://cat.data.fin.gov.bc.ca/documentation/terminology#metadata-editor)
- [x] [Metadata author](https://cat.data.fin.gov.bc.ca/documentation/terminology#metadata-author)
- [x] [Unpublished (draft) metadata](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#unpublished-draft-metadata)
- [x] [Published metadata](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#published-metadata)
- [x] [Information Schedule](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#information-schedule)
- [x] [ARCS](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#administrative-records-classification-system-arcs)
- [x] [ORCS](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#operational-records-classification-systems-orcs)
- [x] [Special Schedule](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#special-schedules)
- [x] [Metadata record publish date](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#record-publish-date)
- [x] [Metadata record modified date](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#record-modified-date)
- [x] [Data set](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#data-set)
- [x] [Data-related asset](https://cat.data.fin.gov.bc.ca/documentation/business-glossary#data-related-asset)
- [x] [Data domain](https://cat.data.fin.gov.bc.ca/documentation/terminology#data-domain)

**Comment by CraigClark** [comment]
@NicoledeGreef I have started a page in the documentation for this. see <https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/terminology>

**Comment by CraigClark** [comment]
@NicoledeGreef related to terminology, we need to differentiate between _data set_ as in what we are adding to this site and _data set_ as in what we are entering meta data about. 

I propose _data set record_ for what we are doing in Drupal. 

Once we settle on that, we need to think about labels and descriptions. For example, _Published date_ and _Last updated date_, I am assuming that's the publishing and updating of the  data set record, and not the source data set, however we need to make that clear.

**Comment by NicoledeGreef** [comment]
A _metadata record_ is what users publish and edit in the Finance Data Catalogue. 
A _metadata record_ can represent: Form, Data, Report or another item that represents a data output, e.g. Dashboard or Cube.

**Comment by CraigClark** [comment]
@NicoledeGreef , I have renamed the content type to _Metadata record_, however we now have a mismatch between label and machine name. 

We can fix this, but we would need to blow away all the test records. Are you OK with this?

I would like to have:

label: Metadata record
machind name: `record`

**Comment by NicoledeGreef** [comment]
@CraigClark in the grand scheme of things, all the test records are junk. However, will you be able to re-load the sample data records provided by others once the machine name is changed?

**Comment by CraigClark** [comment]
Yes, I can put it back. But I'll wait until after the sprint demo

**Comment by NicoledeGreef** [comment]
[Data custodian](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#data-custodian)
[Data dictionary](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#data-dictionary)
[Data catalogue](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#data-catalogue)
[Data set](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#data-set)
[Data steward](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#data-steward)
[Metadata record](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#metadata-record)
[Unpublished metadata record](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#unpublished-metadata-record)
[Metadata author](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#metadata-author)
[Metadata editor](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#metadata-editor)
[Metadata record publish date](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#metadata-record-publish-date)
[Metadata record modified date](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#metadata-record-modified-date)
[Data domain](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#data-domain)
[Information schedule](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#information-schedule)
[Administrative Records Classification System (ARCS)](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#administrative-records-classification-system-arcs)
[Operational Records Classification System (ORCS)](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#operational-records-classification-system-orcs)
[Special Schedules](https://test.cat.data.fin.gov.bc.ca/documentation/terminology#special-schedules)

**Comment by CraigClark** [comment]
@NicoledeGreef I'd like the correct generic term for the thing a metadata recored is about. For example, on the dependency report, we currently are using _Reverenced by X datasets_. What is the correct word? I've come across both 'item' and 'asset' in this context.

**Comment by NicoledeGreef** [comment]
I spent some time on the [Business Glossary](https://cat.data.fin.gov.bc.ca/documentation/business-glossary) (formerly known as Terminology page) in the Documentation. I am going to close this ticket but everyone should know that this is a living document, easily modified. Please file a new ticket for each modification (addition, change, or  deletion) you would like to see.
