### ISSUE TITLE
Set up notification system

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#111]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/stuck pending GC Notify approval

---

**OP timer**

<https://openplus.monday.com/boards/4092908516/pulses/4886281662>

---

Set up the notification system so that users can be notified of significant events in the data catalogue.

BC has an implementation of GC Notify we can use:
https://digital.gov.bc.ca/bcgov-common-components/notify/

There is a self service for GC Notify, use your IDIR account.

**Comment by CraigClark** [comment]
@lkmorlan We are going to have to document how this works for the client. Could you please direct me to the openshift settings we are using and the module settings page? I'll take it from there and you can review.

**Comment by lkmorlan** [comment]
Config for `message_gcnotify` is here:
https://dv21.openplus.ca/admin/config/message/message-gcnotify

We don't have this working on OpenShift. On `dv21`, it is just placeholder config. We need to get the API and template keys. Currently the module has message sending disabled. This means it doesn't contact GCN; it just logs what it would have sent.

**Comment by CraigClark** [comment]
I tried to set up an account at https://digital.gov.bc.ca/bcgov-common-components/notify/ and received the following:

> We hope this message finds you well. We’d like to inform you that your request regarding GC Notify has been successfully received.
>
>Currently, our team in Digital Office, in collaboration with the federal government, is diligently working to enhance and refine our service journey. As a part of the BC Gov common component service, we are temporarily unable to accommodate new requests. Please note that this is a strategic measure to ensure that we can provide you with the best possible service in the future.
>
However, we want to assure you that you and your program are still encouraged to access the service directly through notification.canada.ca. While we fine-tune our service protocols on our end, you can continue to leverage this platform for your notification needs. Before submitting a direct request, we kindly ask you to review the comprehensive [Terms of Use](https://notification.canada.ca/terms) and [Service Level Agreement](https://notification.canada.ca/service-level-objectives). This will help you assess whether GC Notify aligns with your specific requirements.

I have set up a GC Notify account at https://notification.canada.ca/. We will use that for the time being

**Comment by NicoledeGreef** [comment]
https://notification.canada.ca/contact is a form where you can submit a question for support.  As there are header/footer branding challenges in using the GC Notify service, this might be an avenue to obtain more information.
