### ISSUE TITLE
Find another way to deal with a data set author

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#112]
In discussions at stand-up, it was pointed out that there can be issues with re-assigning node authors. This can be particularly challenging when workflow is being used.

We should discuss other ways to identify who the data manager for a data-set is. Perhaps something can be done with taxonomies and user entity fields.

It would be helpful to have a greater understanding of the organizational structure of MFIN and how different sectors will managing data sets. 

@NicoledeGreef we will need to meet to discuss this.

**Comment by lkmorlan** [comment]
It might make sense to have a user reference field for this, additional to the author.

**Comment by CraigClark** [comment]
Yes, that's along the lines of what I was thinking, instead of a field on  the node, was thinking a user reference field on a term. That would make updates a snap when there is a change in responsibilities. Need more info on how MFIN plans to work first.

**Comment by NicoledeGreef** [comment]
pointOfContactforMetadata: the metadata author (anyone should be able to contac them) 
AND
we need to address the scenario where if that person leaves, we need a way to re-assign their record(s)

CC to talk to Joel about using Drupal author

**Comment by CraigClark** [comment]
TODO
Test if email works when using idir account

**Comment by CraigClark** [comment]
For now we are going to use the default Drupal author field. We will revisit if there are issues down the road.
