### ISSUE TITLE
Allow import of Excel (.xslx) files to populate the data dictionary

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#115]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4966375984

---

## User story

As a person who builds data-sets, I want to be able to import data from Excel spreadsheets (*.xlsx*) so I can work in tools familiar to me and have to convert to another format to import from a spreadsheet.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Additional context

Currently we support csv and tsv imports. Joel mentioned at stand-up that there is a way to work with _.xlsx_ files that works well.

## Proposed solution

developer recommendation 

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [x] From the data-set build page, I can import fields into the data dictionary using an excel spreadsheet

### Automated functional tests

- [x] I have written functional tests for this feature
- [x] I have run the functional tests and they pass

**Comment by lkmorlan** [comment]
Will use `PhpSpreadsheet`:
https://github.com/PHPOffice/PhpSpreadsheet

https://phpspreadsheet.readthedocs.io/en/latest/topics/reading-files/
