### ISSUE TITLE
Remove shield

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#117]
Timer

https://openplus.monday.com/boards/4092908516/pulses/4987972526

---

Please remove the shield from sites deployed in BC Gov Openshift environments. This should be done before we release to users for review and comment.

Depends on #119

**Comment by CraigClark** [comment]
@lkmorlan I'm still seeing shield on dv21

**Comment by CraigClark** [comment]
**NOTE**: Shield is still active on dv21. This is setup in the settings file and is not part of config.
