### ISSUE TITLE
Configure production site to be indexed by search engines

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#120]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4991402787

---

In production, this task is intended to reverse work done on #117 

In config split for prod: 

1. [x] remove patch for `robots.txt` that prevents any indexing on the site
2. [x] remove `<META NAME="robots" CONTENT="noindex,nofollow">` to every page on the site; [see this](https://developers.google.com/search/blog/2007/03/using-robots-meta-tag#multiple-content-values)

>**Note**: we want to make sure dev environments do not index and the production environment does. Verify this in config split.

**Comment by CraigClark** [comment]
We will not make the app indexable by search engines until content has been added

**Comment by lkmorlan** [comment]
Since the deployment this afternoon, I have checked that the robots configuration is the same on `dev` and `test` while on `prod` robots are no longer blocked.

**Comment by NicoledeGreef** [comment]
Google has not yet crawled the site.

**Comment by lkmorlan** [comment]
If nothing links to the site, Google may not find it. If you want them to crawl it, you could submit the URL to Google.

**Comment by NicoledeGreef** [comment]
OK - it's not critical to have it crawled (especially when there is very minimal content) so I'll mark this as complete.
