### ISSUE TITLE
Draft MVP roles 

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#125]
## User story

_As a Product Owner
I want to grant appropriate access to users
So that  they can view or create/update/delete metadata in the Finance Data Catalogue._

## This feature support the following requirements

Flesh out user stories taking into account that:

[x] Roles must reflect the personae that were derived from Service Design, or have a good reason for not doing so
[x] Roles must control the ability of a user to create/update/delete metadata vs. only view content
[x] Roles must enable users to use specific functions as applicable
[tbd ] Roles can be used in conjunction with workflow management

**Comment by NicoledeGreef** [comment]
Nicole to schedule Meeting to discuss this further.

**Comment by NicoledeGreef** [comment]
"User_Stories_To_Inform_Role_Creation.xlsx" is under development

**Comment by NicoledeGreef** [comment]
[User_Stories_To_Inform_Role_Creation.xlsx](https://github.com/bcgov/MFIN-Data-Catalogue/files/12772819/User_Stories_To_Inform_Role_Creation.xlsx)

**Comment by CraigClark** [comment]
Rolesa re all set , we can modify as needed
