### ISSUE TITLE
Investigate Active Directory to determine if groups correspond to data providing business domains

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#127]
Rather than re-inventing the wheel in terms of determining what domain a user belongs to, are there Security Groups or Distribution Lists in Active Directory that we can leverage?

"Data providing business domains" note: "Data" encompasses forms, datasets, and reports; these are the business groups within Finance that are responsible for these entities

**Comment by CraigClark** [comment]
@NicoledeGreef I thought this was done and there is no useful mapping we can use?

**Comment by NicoledeGreef** [comment]
Look at DLs as well as Security Groups.

**Comment by NicoledeGreef** [comment]
My take on it is that while DLs would be nice to use, the sample of users I investigated didn't yield majority solid results to build on.

[AD_Mappings_to_Domains.pdf](https://github.com/bcgov/MFIN-Data-Catalogue/files/12836024/AD_Mappings_to_Domains.pdf)
