### ISSUE TITLE
Test CSV Upload with Indigenous languages

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#130]

**Comment by CraigClark** [comment]
Tested on OpenShift cloud environment.

Passed tests for:

1. Inuktitut syllabics
2. Cree syllabics
3.  Coast Salish



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/cb1cb944-75b5-4015-9faf-d965c55c3135)
