### ISSUE TITLE
Reach out to common components contacts about GC Notify

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#131]
- [x] Establish who is the key contact
- [x] Explain our needs/concerns
- [x] Gather insights as to their roadmap
- [x] Assess how the BC instance of GC Notify evolution lines up with our needs

**Comment by NicoledeGreef** [comment]
Emailed a common component contact to obtain more info as to who is key contact at Gov of BC.

**Comment by NicoledeGreef** [comment]
GC Notify liaison for BC has inquired as to rebranding.

https://teams.microsoft.com/l/message/19:b7f982f104f94e58a54216ddc45f29f9@thread.tacv2/1693255400519?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=22f4036e-9930-40dd-9be2-7073e734beac&parentMessageId=1693255400519&teamName=Digital%20Delivery%20Network%20(Open)&channelName=-%20GC%20Notify&createdTime=1693255400519&allowXTenantAccess=false

BC Gov clients using GC Notify will be given a no reply to use that will allow you to specify the prefix.  The no reply will end with @notification.gov.bc.ca

**Comment by NicoledeGreef** [comment]
Re-branding does seem feasible as per these instructions:

When logged into your GC Notify account here are the steps to change the Image of the email template:

Settings > Emails > Email branding (change)

 You will see an option to upload an image. To be consistent we suggest that everyone uses the same published BC Gov image. We suggest using the horizontal RGB positive png attached here.![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/7e84e326-d0f6-4fda-8ac8-40f75a66e158)


or available to download as a complete set here: 

[https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/download-marks](https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/download-marks)

 
Once image is uploaded, the GC notify team will need to approve it before the change becomes activated.

FYI, GC notify doesn't resize the image automatically. so users need to upload the resized png file. This is the guide provided from GC notify. *Make sure your logo is a PNG file and exactly 108 pixels tall to fit correctly in email messages.*

**Comment by CraigClark** [comment]
closed and fix is implemented in #138
