### ISSUE TITLE
Load sample metadata to Delivery environment

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#132]
sample data assembled and hosted at: https://bcgov.sharepoint.com/:f:/r/teams/06981/Shared%20Documents/General/architecture/sample_data?csf=1&web=1&e=43DWR0

**Comment by CraigClark** [comment]
The provided sample data have all been uploaded to the cloud environment.

- https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set/bca-data-advice
- https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set/home-owner-grant-dashboard
- https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set/bca-folio-address
- https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set/bca-values
- https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set/bca-folio-description
