### ISSUE TITLE
Create User Roles

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#135]
To start with DataCatAdmin – add taxomonies, assign users, etc.
MetadataEditors  - create/update?delete metadata content
DataCatUser – anybody who has authenticated via IDIR SSO will have ability to set Bookmarks, get Notified etc.  If a user logs in successfully

**Comment by CraigClark** [comment]
PR submitted https://github.com/bcgov/MFIN-Data-Catalogue/pull/140

**Comment by CraigClark** [comment]
As per slack conversation with Liam, for consistency update all roles

- data_catalogue_custodian
- data_catalogue_administrator
- data_catalogue_user

check for auto-assign role for the data catalogue user
