### ISSUE TITLE
Login labeling and options

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#136]
Re-label this button:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/62ee2fe5-e9fc-4d13-9bc9-fe3c14fc3bec)
to "IDIR Login"(?)

and reduce the two SSO login options to one (Azure IDIR):

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/13512a64-1552-453d-bbea-0e3d3a67d060)

**Comment by CraigClark** [comment]
This is done. 
*Login with…* is the build in prefix to the login button. There is a field where you can fill in what you want to use as a value. This was changed to _IDIR_. 

on the SSO portal, IDIR was removed so AZURE IDIR is the only option. Now users are taken directly to the AZURE login without having to make a choice.

**Comment by CraigClark** [comment]
>**NOTE**: This change is tagged for base-build candidate. OpenID is already in base-build, the rest is all config which happens on a per project basis.
