### ISSUE TITLE
visual flag for metadata content changes between revision?

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#139]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/question

---

## User story

As a consumer of data listed in the Data Catalogue that receives a notification of change
I want to see a visual flag (icon and or color) of what the change entails 
so that I can check my dependencies and update them accordingly.

## Describe the idea

Can we highlight fields in the data dictionary that were modified?
Other content attributes as well that contributed to the email notification?

@nicoledegreef heard this from @eloynav and we worked up the ticket together.

## Actions

- [x] Hurray! I'm going to be a feature!

**Comment by CraigClark** [comment]
possible starting points

1. https://www.drupal.org/project/highlight_changes

the DIFF module will show changes made, typically we don't expose this to content consumers, but there might be a way to leverage it.

One of the issue with highlighting changes is how do I get rid of the highlight once it's not needed anymore. Related, how do I know which change the highlight is for? Say I change something on April 1, you go check it on April 2 and the highlight is there. Then I make a change on June 1, June 1 you go and see a highlight from April and a Highlight from June. How to know what the right highlight is.

Maybe we can look into sending a diff in the email notice.

**Comment by NicoledeGreef** [comment]
@CraigClark to demo this to @NicoledeGreef

**Comment by CraigClark** [comment]
Stuck until memory limit is increased on cloud. see #154

**Comment by CraigClark** [comment]
Will has done work on this and diff now works.

@NicoledeGreef , lets schedule a demo.

**Comment by CraigClark** [comment]
done

not bookmarked



![not bookmarked](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/ae02b669-2c36-4d17-98f6-2e6bf11fd91f)

bookmarked



![bookmarked](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/7a28649e-3409-4ad4-bec7-dc1683cc3155)

**Comment by NicoledeGreef** [comment]
@eloynav  - thanks for the feature suggestion. This has been implemented (it was demo'd at Sprint 6 Review meeting).  There's a recording of the demo in the Teams channel.
