### ISSUE TITLE
Authenticator Issues

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#141]
**OP timer**

---

## Describe the bug
Guidance indicates two options available for log in, however only Log In with IDIR is displayed (screenshot # 1).  When that option is selected a dialog pops up indicating to enter the code on the Microsoft Authenticator app on your mobile device (screenshot # 2), however the app does not activate on the mobile device and no code is given.  User cannot log in to the Catalogue

## To reproduce
Steps to reproduce the behaviour:
1. Go to the Catalog
2. Click on Log in with IDIR
3. The authenticator dialog shows

## Expected behaviour
Either log in happens without authentication as indicated in the Alpha guidance, or there is successful integration with the authenticator app so that a code is sent to the user.  A 'Send another code' option would be a bonus, to allow the user to resend the code if there were problems the first time (or if code expired before they could enter it).

## Screenshots
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/84afe349-72a4-4f5e-99e1-cea3a162e3fb)

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/9b83f7e0-c4af-404d-a515-7de3f65375e7)

## Other Information
Note, I was able to click on the 'Verify another way' which allowed me to choose an option the 'Verify with Authenticator App'.  This option then gave me a code which I was able to successfully enter via the app and get into the Catalogue.  This worked, but wasn't intuitive or easy to figure out.  A more streamlined log in process is needed.

**Comment by CraigClark** [comment]
Hi @mjmcclung At this point in the process, the authentication is outside of the data catalogue application.

The way it should be working is that when you click _Log in with IDIR_, you are taken to BC's authentication.  I have had no issues with the authenticator app. It runs constantly and assigns a new code that lasts for 30 seconds. This is what I put in the dialogue and I haven't had issues. 

> **Screenshot of authenticator app**
>
>![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/f39bdeda-e94a-4258-84eb-b99d49d0ba92)
>

The site is accessible without authentication, for now we have the home page set as the login screen. I'll change that to the search page this afternoon. That should help people who want to see the app wthout logging in.

There are currently two ways of logging in. Administrators can log in with a Drupal account and bypass the IDIR authentication. Most users don't do this and will be using IDIR.

**Comment by mjmcclung** [comment]
Interesting.  I manually opened my Authenticator app and saw that 30 second code on one of the screens.  I tried that code in the Catalogue screen but it didn't work for me.

**Comment by NicoledeGreef** [comment]
@mjmcclung this is outside of the MFIN Data Catalogue application.  Let me know if you still have issues accessing it.  It took me some effort to get set up.

**Comment by NicoledeGreef** [comment]
https://support.microsoft.com/en-us/account-billing/common-problems-with-two-step-verification-for-a-work-or-school-account-63acbb9b-16a1-47b9-8619-6a865e8071a5

when you get a code on screen from Microsoft you must enter that in your device that is configured for MFA.  in my case i get a pop-up on my phone and enter the code.  you must ensure that the MFA is correctly set up on you account.  a month or so prior i used to rely on Microsoft calling my cellphone and then i would press # and it would authenticate me.  the code popup is much smoother.  see:
https://support.microsoft.com/en-us/account-billing/change-your-two-step-verification-method-and-settings-c801d5ad-e0fc-4711-94d5-33ad5d4630f7
