### ISSUE TITLE
Bookmark improvements

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#142]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a use I want the bookmarking to be intuitive and similar to how bookmarks work in other places so that I find the service easy to use and navigate.

## Describe the idea
The bookmark button currently shows above the right hand data box and visually looks like a tab for this box.
It would be great if additional white space could be added between the button and the box to differentiate it.
Also wondering if a bookmark icon could be added?  Is it also possible to have this filled in if bookmarked?  This would help give a visual clue to the user that this dataset is bookmarked.

## Screenshots
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/81ff1f0e-6ef4-427c-b451-88476e569a61)

Bookmark icon:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/746d3c92-6508-423b-8ac6-7f83c166eb85)

## Actions

- [x] Horray! I'm going to be a feature!

**Comment by CraigClark** [comment]
done

not bookmarked



![not bookmarked](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/ae02b669-2c36-4d17-98f6-2e6bf11fd91f)

bookmarked



![bookmarked](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/7a28649e-3409-4ad4-bec7-dc1683cc3155)

**Comment by NicoledeGreef** [comment]
Great to see some UI refinements being worked into the app. Reviewed in dv21.
