### ISSUE TITLE
Make guidelines around capitalization, spelling etc. for taxonomy terms

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#150]
**OP timer**

---

I was uploading test data and I was getting failures on the term `varchar`, which exists in the taxonomy as `Varchar`.

We should have that standardized so errors don't get thrown.

**Comment by lkmorlan** [comment]
Do you want it to be case-preservation?

**Comment by NicoledeGreef** [comment]
Related to email from MS re: data types in the data catalog
Nicole to book meeting with that team of power users early in the sprint if possible to discuss before we make decisions.

**Comment by NicoledeGreef** [comment]
Email re: data types question:

"...question related to our data catalog discussion from yesterday. Will the catalog be able to support detailed data type information that reflects the platform where the dataset is stored, and also the type/version of the storage platform itself? For example SQL server has the following INT types:

Sql Server:
TinyInt – unsigned 8 bit
SmallInt – signed 16 bit
Int – signed 32 bit
BigInt – signed 64 bit

While these are all instances of type Int, there is potentially value for our team to have the more granular details as well. There are also cases where different DBMS and data storage formats have different data types or implement data types in a slightly different manner. 

Datetime types

Sql server:
date
datetime
datetime2
datetimeoffset
smalldatetime
time

SAP HANA:
DATE
TIME
SECONDDATE
TIMESTAMP

Datatypes can start to vary even more when you get into spatial types, support for json/xml, and binary types."

**Comment by CraigClark** [comment]
We met on this on Sept 11.

we will use taxonomy for this with two levels

The first level will be the high level field type, ie. date. the second level will be the specific data type.

Unless otherwise specified, Taxonomy terms will use sentence case. Specific data types will use camel case. so this would look like:

- Date  
  - DateTime
  - DateTime2
  - DateTimeOffset
  - SmallDateTime
- Time  
  - TimeStamp

This example is field specific and is part of the data dictionary, for data-type, display as top level term and second term, ie: _Number: TinyInt_

The data set format (MySQL, SAP etc) is metadata on the data set.


There is a related issue #165

**Comment by CraigClark** [comment]
see https://digital.gov.bc.ca/about/style-guide/

**Comment by CraigClark** [comment]
Done https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/writing-guidelines
