### ISSUE TITLE
Planning for restriction of access to metadata records

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#151]
**OP timer**

---

Give users the option to restrict a metadata record's visibility to other users by applying one or more Organization values.
Note: Organization is already a value used on the metadata record and we don't want that want to conflict with security.

**Comment by NicoledeGreef** [comment]
We need to discuss and map it out.

**Comment by NicoledeGreef** [comment]
dataset editor role currently can add or edit any dataset. ideally only a business domain editor should be able to add/edit/delete metadata records in their own domain(s).

**Comment by NicoledeGreef** [comment]
Nicole to schedule meeting with Craig to discuss further, later in the sprint after we've discussed it internally.

**Comment by NicoledeGreef** [comment]
scheduled for September 12

**Comment by CraigClark** [comment]
We met on this. Before we proceed, we need to investigate Active Directory integration. If that has useful groups, we can use that to determine the org a data set should belong to as well as the security. See #127
