### ISSUE TITLE
UI discussion

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#152]
- UI for data input (what is exposed, what is hidden, picklists vs. auto-filter)
- dataset view (how the metadata is displayed onscreen)

content model review/updates
should the data dictionary be in a table, similar to BCDC implementation

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/fa56dc6b-716c-4303-81d1-5d61c0bee022)

**Comment by NicoledeGreef** [comment]
scheduled for Sept 14

**Comment by CraigClark** [comment]
Closing. This meeting was held. The result was some new tasks that consolidate what users will need to fill out on a form. Additionally, we planned for a card sort to group fields. Once we have that info, we will meet again further plan UI
