### ISSUE TITLE
Reminder: grant editor role(s) to users in Delivery

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#155]
**OP timer**

---

We need to set up @NicoledeGreef so that she can enable other accounts to be able to add/edit metadata records in Delivery *or* grant all the users the role directly.  @NicoledeGreef has list of IDIR accounts.

**Comment by CraigClark** [comment]
We have run into issues with the role_delegation module. It is causing tests to fail. Working on it

**Comment by CraigClark** [comment]
Issue with role delegation is resolved. Data catalogue admins can assign roles
