### ISSUE TITLE
Review Taxonomy and terms vs. Content Architecture doc

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#157]
**OP timer**

---

https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/admin/structure/taxonomy

BC-MFIN-Content-Architecture-Living-doc

@CraigClark to map the dataset fields to the appropriate taxonomy.

**Comment by CraigClark** [comment]
This mapping is done. see https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/admin/structure/taxonomy
