### ISSUE TITLE
Route access control

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#158]
**OP timer**

---

## Describe the bug
Various screens appear to allow a user to build or edit information, however user does not have the appropriate role to do this.

## To reproduce
Steps to reproduce the behaviour:
1. Go to user dashboard
2. Scroll down to bookmarked datasets
3. Click on Build button
4. Click on Edit button
5. Get 403 Forbidden error

Build Tab is also visible when a user clicks on a specific dataset (screenshot # 4)

## Expected behaviour
If user does not have the appropriate permissions they should not have the various Build and Edit buttons available to them.

## Screenshots
# 1:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/d0d4c78b-90e6-447f-8b60-6fc420ada781)
# 2:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/3f81053f-793d-49cd-a2b2-b4f11fedf70b)
# 3:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/5c39cc9f-1af4-4a30-a63b-a35df62ec354)
# 4: 
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/da56cd51-8a40-4f98-85cd-c6f29ad165e4)

**Comment by lkmorlan** [comment]
Joel's suggestion: See RSAMS gcext/src/Controller/CheckBuildAccess. This is associated using the path in the routing file. Nothing explicitly connects it to page manager except that it uses the same path.

One option: https://drupal.stackexchange.com/questions/300744/custom-access-method-for-a-page-manager-page

**Comment by joel-osc** [comment]
Prefer pageAccessCheck to Condition system... the Condition system is awkward in D8+, not as nice as the ctools condition system in D7. My 2 cents.
