### ISSUE TITLE
Update Headers to use Title Case

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#159]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a user I want to have a consistent look and feel across catalogues so that I can focus on the content.

## Describe the idea
Headers for metadata content should use Title Case for consistent look and feel.

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
So far we have been adhering to the Canadian Style Guide but we are going to adopt the BC version https://digital.gov.bc.ca/about/style-guide/

I don't disagree with the Title Case (it's my personal preference) but seems to Sentence case is the current standard.
