### ISSUE TITLE
Update Information Security Classification Taxonomy

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#160]
**OP timer**

---

## Describe the bug
Information security classification taxonomy could be improved to provide more context and awareness to the user by including the Confidential prefix for the applicable classifications.

## Expected behaviour
Information Security Classifications Protected A through C should be prefixed with 'Confidential', i.e. "Confidential - Protected A".  This will align with the usage of this taxonomy in other government systems (e.g. EDRMS).

## Screenshots
Catalogue: 
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/0582f6a2-5253-4869-a870-3f0aa25e8166)

EDRMS Example:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/14073cdf-f142-4d78-af0f-67d749094735)

**Comment by CraigClark** [comment]
Removing bug label. This is a content change, https://github.com/bcgov/MFIN-Data-Catalogue/labels/bug is for things that do not work as designed.

**Comment by NicoledeGreef** [comment]
Updated in Drupal
