### ISSUE TITLE
Add environmental indicatiors to OpenShift environment

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#172]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5194389654

---

The environmental indicators module has been enabled. The code below needs to be added to settings.php

```
# enviromnent indicator
$config['environment_indicator.indicator']['name'] = 'BC cloud dev';
$config['environment_indicator.indicator']['bg_color'] = '#9F0000';
$config['environment_indicator.indicator']['fg_color'] = '#FFE3E3';
```

**Comment by CraigClark** [comment]
These can be edited here https://github.com/bcgov-c/tenant-gitops-ea352d/blob/main/helm-drupal/values-mfin-data-catalogue.yaml#L62

**Comment by lkmorlan** [comment]
Implemented:

https://github.com/bcgov-c/tenant-gitops-ea352d/commit/44e85b5f87c4deb6edb970c887e94783e686df91

**Comment by CraigClark** [comment]
thanks
