### ISSUE TITLE
Create list of data dictionary fields and what they are used for

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#174]
**OP timer**

---

This is similar to #173 , but for fields used in the data dictionary.

- [ ] A list of data dictionary fields has been added to the documentation

**Comment by CraigClark** [comment]
~~There is a field in the data dictrionary, _Provenance field name_ `field_provenance_field_name` that is not in the [architecture document](https://bcgov.sharepoint.com/:w:/r/teams/06981/_layouts/15/Doc.aspx?sourcedoc=%7BD7CD5A7F-B845-4CA2-9C88-2A17FE87B27F%7D&file=BC-MFIN-Content-Architecture-Living-doc.docx&action=default&mobileredirect=true). @NicoledeGreef , do you know what this is?~~ 

Edit - found it

**Comment by CraigClark** [comment]
This is done. https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/data-dictionary-fields

@NicoledeGreef In the help guide, we have a description of what all these fields are for. We can add the descriptions as help text right on the input field in the build form. It wouldn't take long to add these.

Do you think this would be useful?

For example



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/6d7ee5d4-d24f-4629-ab71-39b434abb809)

**Comment by NicoledeGreef** [comment]
see #228
