### ISSUE TITLE
Personalise footer by organization

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#176]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5225361090

---

>[!NOTE]
> Some if this work is done in <https://github.com/bcgov/MFIN-Data-Catalogue/tree/176-personalise-footer-by-organization>.
> - global menu links have been added in openshift and on dv21
> - some theme fixes to dc_theme and bcbb_theme
> - global footer menu block placed
>
> **Todo**
> add personification to footer, this should be above the global footer
> once that is working, assign to Craig to finish up the theming

## User story

As a user of the data catalogue, I want to see my organization reflected in the interface so that it is clear to me that my organizations contributions to the data catalogue are recognized.  

## Describe the idea

There are a few different tasks related to various org units seeing themselves reflected in the UI. We will use a custom footer to achieve this in the alpha release.  Custom block; the Data Catalogue Managers (a small number of users with in a domain) can manage the content of the custom block.

Custom block has the following fields:
- [x] image (svg)
- [x] org title
- [x] hyperlinks

These will be stored as fields on the org's taxonomy term.

Default BC footer should be persistent
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/a9482c7a-7748-4397-85d8-4ca9b4dba414)

Customization footer is optional (see Gov of Canada footer for example).

Default - authenticated: link to https://intranet.fin.gov.bc.ca/fintranet

If there is personalization allow for a custom graphic with unlimited links.

Manager role can make the footer personalization change.

## Outstanding footer issues
- [ ] Image is wrapped in an `article` element. Should be `div`.
- [ ] Image has a visually-hidden "Image" label. Should not appear.
- [ ] Links should be wrapped in a `nav` element.

**Comment by CraigClark** [comment]
Related to #69

**Comment by NicoledeGreef** [comment]
Question for @nicoledegreef to answer: 
Does the prototype footer satisfy this requirement?
Admin users would have the role to update the footer graphic, name, and links for a domain (Organization).

If someone belongs to more than one Org, they will see the one that is first in their User profile.

**Comment by NicoledeGreef** [comment]
Let's implement this.

Default - un-authenticated: mimic the BC Gov webpage footer

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/c61ebdfa-cb4a-48aa-8a3c-5c79ef6d31bd)



Default - authenticated: link to https://intranet.fin.gov.bc.ca/fintranet


If there is personalization allow for a custom graphic with unlimited links.

Manager role can make the footer personalization change.

**Comment by NicoledeGreef** [comment]
Please see this link for guidance on the basic Gov web footer:
https://developer.gov.bc.ca/Footer-Basic

@CraigClark

**Comment by CraigClark** [comment]
Fixed  ~~Assigning back to Craig to fix, footer is in the middle of the search page.~~

**Comment by NicoledeGreef** [comment]
Can we restrict the pixels dimension of the uploaded graphic in order to manage the height of the footer better?  The daisy example was really big and stretched things vertically, I thought.
