### ISSUE TITLE
Updates to Information Schedule Documentation

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#177]
--

## User story

As a catalogue manager I want to understand the information I am filling out/choosing so that I can label my information accurately.

## Describe the idea
Update the [Information Schedule taxonomy page](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/information-schedule) to use plain language and BC gov't language.

The current page doesn't reflect the language of the BC Gov't and doesn't match the language used in various government policy and guidance in the records mgmt space.

There are too many changes to list in one Idea - how would you like them provided?  A word document?  Or can I have direct access to edit myself?

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by CraigClark** [comment]
the attached markdown fine can be edited. When it's done, send it back to me. I can convert to HTML and add to the docs.

[information_schedule.md](https://github.com/bcgov/MFIN-Data-Catalogue/files/12770862/information_schedule.md)

**Comment by CraigClark** [comment]
There is a second part to the information schedule docs now. The attached document is about importing terms into the taxonomy

[information_schedule_import_taxonomy.md](https://github.com/bcgov/MFIN-Data-Catalogue/files/13309449/information_schedule_import_taxonomy.md)

**Comment by CraigClark** [comment]
Closing this. The markdown file is too outdated. At this point, best to edit on the documentation pages in Drupal

**Comment by mjmcclung** [comment]
Agreed.  I started to edit the markdown file a while back but there was too much in flux and too many edits required.  Best to start fresh if any edits are required.  Plus, the taxonomy documentation has been moved to the Administration area, so this info won't be accessed by general catalogue editors.
