### ISSUE TITLE
Automated tests failing

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#18]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4582100205

---

## Describe the bug

Liam has identified that  automated tests for features are not working as expected.

## Expected behaviour

When an automated test is run, it is able to complete and inform developers if the test passed or failed.

**Comment by CraigClark** [comment]
@lkmorlan is this an issue with the data catalogue? Does this need to be fixed in the base-build as well?

**Comment by lkmorlan** [comment]
These are data catalogue tests.
