### ISSUE TITLE
Meet to discuss Info Schedule finer points #128

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#180]
Meet to discuss #128

**Comment by NicoledeGreef** [comment]
scheduled for Oct 3rd

**Comment by NicoledeGreef** [comment]
**Discussion:**
- advice: please hold off on general UI improvement feedback for another sprint or two as there is planned work in this area and it may address some of the concerns
- the display of Information schedule could be modified for context/usability; requested to please create a Task ticket with mock-up of wish list items for consideration

- outstanding questions:
--> adding support for more than 1 schedule being applied to a metadata record (meeting now set up to discuss this)
--> loading the Info Schedule taxonomy values through an API
- new exploratory question: currently the metadata editor is forced to specify all levels of the Info Schedule taxonomy  before they can save the record; can we scale that back to the first two levels and make the last two optional?

- in terms of sourcing data for the ARCS and ORCS taxonomy values we can likely use the attached spreadsheet for ARCS and we are hopeful to get a dump of applicable ORCS (and Specials?) from an EDRMS report

**Comment by CraigClark** [comment]
> new exploratory question: currently the metadata editor is forced to specify all levels of the Info Schedule taxonomy before they can save the record; can we scale that back to the first two levels and make the last two optional?

That would be custom code. By default, you can force deepest term or not. The issue would be though, most of the key information depends on selecting all terms. For example, active period, semi active, retention, special flags - those are all on the last term. The info schedule I saw for BC does not have any of that information on the top level categories. Also, the info schedule code would be inaccurate.

For the spreadsheet, I don't see it attached to your comment. It would be useful to have though if we decide to move ahead with some sort of bulk upload for taxonomies.

**Comment by CraigClark** [comment]
There is an existing [taxonomy import module](https://www.drupal.org/project/taxonomy_import), I've never tried it. It does seem to support hierarchy and there is a [patch for adding custom fields](https://www.drupal.org/project/taxonomy_import/issues/3067263).
