### ISSUE TITLE
Amend PIA to reflect the nature of IP logging

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#183]
PIA was submitted but new info determined.
e.g. dv21 dblog keeps 1000 msgs

In Production, typically we stop tracking this in the DB and the webserver in Openshift takes over.  Is there a standard retention for logs?
Check FOIPPA/FIPPA and talk to infra team.

**Comment by NicoledeGreef** [comment]
@CraigClark  - please review attached PIA updates (highlighted lines) around IP Address logging in Drupal and let me know if I have characterized it properly.

[PIA_Draft_0.2_updates.pdf](https://github.com/bcgov/MFIN-Data-Catalogue/files/13418810/PIA_Draft_0.2_updates.pdf)

**Comment by CraigClark** [comment]
@NicoledeGreef I ran this by Liam and he says it looks good. He did point out that Apache will typically log requests

**Comment by NicoledeGreef** [comment]
Thanks - the updated document has been submitted to the Privacy team.

**Comment by NicoledeGreef** [comment]
Met with P&S team to discuss the amended PIA. PIA should be signed off by Dec 8th and a SOAR with be prepared as well. In their estimation is should all be ready well before Dec 31st.
