### ISSUE TITLE
configure breadcrumbs for the site

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#185]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5249244346

---

- [x] use the Search page for the data set landing page
- [x] only index the metadata records for that search
- [x] ensure that the Search block in the header goes to the landing page
- [x] display Dashboard on homepage

**Comment by CraigClark** [comment]
Tested on dv21, works as expected. Not sure we need the page title to be 'Search data sets', just 'data sets' would align it to the breadcrumb and it's pretty obvious what this page does.
