### ISSUE TITLE
Ability to import taxonomy values and fields for Information Schedule

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#188]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5284137698

---
There is an existing [taxonomy import module](https://www.drupal.org/project/taxonomy_import). It does seem to support hierarchy.

This is a taxonomy needs to support the creation of Information Schedule values because of the high number of values involved.  ARCS, in particular, is too arduous to create manually.

Note: if you think this will take more than 3 days, please raise it with @CraigClark 

- [x] test an import
- [ ] provide a template to @NicoledeGreef

**Comment by lkmorlan** [comment]
I have taxonomy_import working. There is very little config. It basically just works, but there are some caveats.

Only CSV import works for us. XML import does not support custom fields.

There are four fields in the information_schedule taxonomy that are entity reference fields that refer to taxonomy terms. For these, the value that needs to appear in the CSV file is the term ID. We could provide a list of these so that BC staff can create a CSV with these values or we could write custom code to handle mapping between the term name and term ID.

If there is more than one term which could be a parent, there is no way to control which one of these new terms will be attached to. Any that are wrong will need to be manually fixed.

Do not upgrade `taxonomy_import` past version 2.0.12 without checking that custom field imports still work. The commit after tag 2.0.12 removes this feature.

We need to know if the import will be done once or repeatedly. If it is just once, we don't need to add it to the build or make it easy and automated to do.

If this is to be done repeatedly, it may be that using the migration module would work better than `taxonomy_import`.

**Comment by CraigClark** [comment]
@lkmorlan is this anywhere I can take a look at it? I looked around on dv21, but didn't see anything about importing taxonomies

**Comment by CraigClark** [comment]
@lkmorlan I tested this with the attached csv file and I got the following error



[info_schedule_import.csv](https://github.com/bcgov/MFIN-Data-Catalogue/files/13231497/info_schedule_import.csv)

I tested with branch 188-ability-to-import-taxonomy-values-and-fields-for-information-schedule

Does this include the patch to import fields?

```
The website encountered an unexpected error. Please try again later.


InvalidArgumentException: Field Description is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 583 of core/lib/Drupal/Core/Entity/ContentEntityBase.php).

Drupal\Core\Entity\ContentEntityBase->get('Description') (Line: 624)
Drupal\Core\Entity\ContentEntityBase->set('Description', 'Test desc') (Line: 217)
Drupal\taxonomy_import\Form\create_taxonomy('information_schedule') (Line: 115)
Drupal\taxonomy_import\Form\ImportForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 597)
Drupal\Core\Form\FormBuilder->processForm('import_taxonomy_form', Array, Object) (Line: 325)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 592)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 270)
Drupal\shield\ShieldMiddleware->bypass(Object, 1, 1) (Line: 137)
Drupal\shield\ShieldMiddleware->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```
```

**Comment by lkmorlan** [comment]
@CraigClark There are no patches to `taxonomy_import` on that branch.

**Comment by CraigClark** [comment]
Closing this, feature will be included in  #216

**Comment by CraigClark** [comment]
Additional task tied to this:

Check and see if an import appends or replaces existing taxonomy. Check TIDs and field values

**Comment by CraigClark** [comment]
@NicoledeGreef 

I tested this this morning

## Test 1)  import of new terms

### Test

1. create a view using all the fields of the info schedule and the term ID
2. attach a `csv` export to the view
3. export csv and get all current values with term ID
4. import [sample `csv` from the help guide](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/sites/default/files/2023-11/bc_mfin_information_schedule_sample.csv)
5. export and compare results

### Result

1. New terms were added 
2. Existing terms were not replaced, this was determined by a comparison of term ID's before and after import

## Test 2) import of updated terms

### Test

1. export information schedule values after test 1 (this includes the new values)
2. change some field values
3. change title of one term
4. import back into data catalogue
5. export and compare results

### Results

1. Existing terms and values did not change
2. If values for a term changed, but the term name did not, the values were updated
3. if a term name was changed, it was added as a new term

>[!IMPORTANT]
> 
>To test this, a view was created that shows all information schedule values and a link to download the values as csv. This will probably be useful to DC admins as the information schedule is developed. 
> 
> I'll commit that view as part of this issue. There will be another ticket submitted to allow for embedding views blocks. Once that is comitted, I'll add this block to the relevant page in the documentation.


## Attachment: test results



[taxonomy_import_test_results.xlsx](https://github.com/bcgov/MFIN-Data-Catalogue/files/13571190/taxonomy_import_test_results.xlsx)

**Comment by CraigClark** [comment]
Feature branch with view for exporting info schedule values https://github.com/bcgov/MFIN-Data-Catalogue/tree/188-view-for-exporting-info-schedule-values

**Comment by CraigClark** [comment]
closing, #258 is the issue to get views blocks embedded in CKEDitor
