### ISSUE TITLE
Ability for editors to restrict access to some metadata records

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#190]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5313808202

---

## User story

As a contributor to the data catalogue, I want to have control over who can see the metadata record so that no information is leaked to people before it is ready for wider consumption.

## This feature support the following requirements
[mvp build](https://openplus.monday.com/boards/3958997205/pulses/4162762530)

## Additional context

Currently there is a vocabulary for Organization. This field vocabulary is referenced by `field_primary_responsibility_org` on the metadata record. This is information that is available on every record, no matter the access. This rules out using TAClite out of the box as it looks for terms on a page and restricts access based on that. This is an issue because sometimes a record that belongs to _Property taxation branch_ is publicly available, sometimes it might be available only to staff at _Property taxation branch_ .

> **NOTE**: It doesn't look like we can rely on Active Directory to assign roles. This means that an admin at BC will need to be responsible for assigning roles to users manually. This will probably require an internal business process.

## Editing Permissions
- Users can create/edit metadata records only in Orgs that they belong to
- Users can belong to more than on Org
- User's Org has to match the OPR value on the metadata record

## Viewing Permissions
- MR can be visible to public users OR
- MR can be visible to all logged in users OR
- MR can be visible to users that belong to the MR's OPR or other designated Orgs

## Proposed solution

Investigate contrib modules and see if there is anything that will satisfy this requirement. TAClite may be a place to start, but won't meet this requirement out of the box.

## Estimated level of effort

- 5  days

## Definition of done (DoD)
- [x] editor can restrict access to an organization by selecting an org from a list
- [x] if I am not a member of the org, I cannot access the node
- [x] users can be assigned an organization (or multiple organizations)
- [ ] Document that the Organization taxonomy has to be flat

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

**Comment by lkmorlan** [comment]
@NicoledeGreef Should DC admin be able to bypass this access check and see all content, even if it has access restricted to a particular org unit?

**Comment by NicoledeGreef** [comment]
@lkmorlan DC Admin users should, in theory, have access to view/edit all metadata. Thinking of potentially restricted metadata, we are checking with the business domain this most likely affects to see what their thoughts are.  I will get back to you on this.

**Comment by NicoledeGreef** [comment]
Have confirmed that it is OK for users with the DC Admin role to see all restricted metadata.  Same for Drupal admin, potentially.

**Comment by CraigClark** [comment]
Notes on some testing I did for this

I got access doing what we need it do do on a local copy of RSAMS. 
I've added my changes to this branch https://github.com/openplus/site-rsams/tree/test/edit-view-access-by-org

1. Created terms Public and Authenticated on ORG taxonomy
2. Created an entity reference field to org
3. configure tac for view access

Looking at this on RSAMS

## assigning org to users

This is done on an individual level. On the edit user page, there is a field to add people to an ORG, or ORGs. As orgs are added, they are assigned terms on the 'access by taxonomy' page.  There is no need manually make changes to the 'access by taxonomy' page.Recall admins can't even access it.

I like this approach, it's easy for admins

## Assigning org to a recall

I think this is the piece we are missing for BC.

When I create a recall, my org is assigned. Not sure how it works, but I'm sure Drupal knows my org. Note that on the recall field settings for `field_organization`, there are field permissions set. Nobody can edit their own value for this field, recall admins can change any value for this field.

When I create a recall, I am given a list issue types to choose from. I'm not sure, but I think the org is assigned to the node based on the alert type I select. BC doesn't have a version of this. Maybe one way to do it is:

1. use the webform node builder (or whatever the module is called)
2. In the webform, get a list of the orgs the user creating the MR has assigned to them
3. Make those orgs available as options on the webform when I create an MR
4. whatever org I select from the form, populates the OPR field on the MR
5. use field permissions (I'm assuming it's a module) and on OPR field, only an admin can change it

This would prevent me from locking myself out of my own MR. For instances where someone will be working across orgs, we assign them all the orgs.

only admins can change an org once it is assigned.

Looking at RSAMS

There are permissions on the field for org, see <https://hcdev.openplus.ca/en/admin/structure/types/manage/recall/fields/node.recall.field_organization>

There is custom code related to TAC, I don't know what it does, for example see here <https://github.com/openplus/site-rsams/blob/dev/html/modules/custom/gcext/gcext.module>

**Comment by CraigClark** [comment]
I think RSAMS holds the solution for this, however we have spent a lot of tome on it. I'm moving it to the backlog until we have a chance to better understand the problem and how it has been solved on other projects.

**Comment by CraigClark** [comment]
I ran into a couple of issues testing.

## as user with role DC editor and org FREDA

1. create a new MR
2. set OPR to FRIDA (I could not assign OPR, had to do that as admin - this is fine, its by design)
3. set visibility to public
4. Save
5. in another browser, not logged in, see that I can see the node **[PASS]**

##  as user with role DC editor and org FREDA Change visibility to a different ORG (auditors)

1. select build tab
2. set visibility to _auditors_
3. see error `You can only change the book outline for the published version of this content.` **[FAIL]**

## as admin, Change visibility to a different ORG (auditors)

1. select build tab
2. set visibility to _auditors_
3. publish
4. as user with role DC editor and org FREDA, view the node **[ FAIL ]**

I would expect that I would still see this because the OPR on the MR is FREDA and I am assigned the ORG FREDA

**Comment by joel-osc** [comment]
Liam and I discussed this... you can change the view schemas to include OPR if you want... or ensure to add OPR in vis. Books hit is not part of this.

**Comment by CraigClark** [comment]
- [x] @lkmorlan can you please change the view schema so that if a user and a record have the same org/opr, they can view the content?

**Comment by CraigClark** [comment]
This feature extends how the taxonomy access module typically works. This has been documented in the [wiki for the data catalogue project](https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Features#restricting-access-to-a-metadata-record).
