### ISSUE TITLE
Add pruner

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#191]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5320175018

---

We can run into issues with large revision tables, especially if we get large data dictionaries. A pruner removed previous unpublished revisions. It will keep previous published revisions and all forward revisions.

**Comment by lkmorlan** [comment]
Module `cm_revision_delete` installed and configured.

**Comment by lkmorlan** [comment]
UI misspellings corrected:
https://www.drupal.org/project/cm_revision_delete/issues/3412170

**Comment by CraigClark** [comment]
@lkmorlan 

I could not get the pruner to work, I am testing on this node https://dv21.openplus.ca/node/79/revisions

1. create a few revisions
2. publish
3. set content moderation to run every time cron runs https://dv21.openplus.ca/admin/config/content/cm_revision_delete
4. run cron a couple of times
5. clear caches
6. see that the draft revisions are still there.

**Comment by CraigClark** [comment]
tested and approved on dv21

**Comment by lkmorlan** [comment]
Revisions are not being pruned. The update to `cm_revision_delete` may be all that is needed to fix this.

**Comment by lkmorlan** [comment]
Revisions are now being pruned correctly.

**Comment by NicoledeGreef** [comment]
To test this: set up some revisions and publications on records  in dv14 then check to see if they have been pruned overnight.

**Comment by NicoledeGreef** [comment]
Test record: https://dv14.openplus.ca/node/37/revisions

As of 3:08pm on May 21:

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/b92c4e54-1a68-421b-80cd-51b4d33e02f9)

Will check for pruning action on May 22.

**Comment by NicoledeGreef** [comment]
The Drafts were removed overnight. All older Published  versions are maintained.
