### ISSUE TITLE
Information Schedule Changes

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#192]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5329347133

---
Hello!  I've reviewed the Information Schedule display in the Catalogue and have the following feedback to action:
1. If possible, please add a header to this section of the info box and title it "Information Management".
2. I would only like to display high level details here.  Full details, such as Active Period, Semi-Active Period, Final Disposition, scope notes, etc should be displayed elsewhere by clicking on a "More Information" (or similar) button.  Only a subset of users will be interested in these full details and we don't want to overwhelm the average user with information they don't understand.  _All_ the information schedule pieces should be available for reporting purposes though (report specs to come later).
3. Please display three sets of information on the main metadata record page:
    a) Information Schedule Type: ARCS/ORCS/Special/Unscheduled
    b) IM Classification Detail: concatenation of the _names_ of the chosen terms with the following format: [INFORMATION SCHEDULE] [Primary Name]:[Secondary Name] e.g., ‘ARCS Administration, General: Lists, spreadsheets, and registers’, ‘PTAX Property taxation - general: Property taxation data warehouse data’.  **Note the use of the ORCS schedule abbreviation instead of the schedule number.  This is a change from the current display.**
    c) IM Classification Code: concatenation of the _codes_ of the chosen terms with the following format: [INFORMATION SCHEDULE ABBREVIATION] [PRIMARY NUMBER]-[SECONDARY NUMBER] e.g., ‘ARCS 100-05’, ‘PTAX 45000-03’.  **Note the use of the ORCS schedule abbreviation instead of the schedule number.  This is a change from the current display.**

**Comment by NicoledeGreef** [comment]
Assigning to @CraigClark so he can prototype the Info Schedule term page view.

**Comment by CraigClark** [comment]
@mjmcclung We have a prototype for this

Clicking on the _Information schedule link_ will take you to the term page. The breadcrumbs at the top will take you to the parent terms, however all the schedule info is most accurately captured in the last term.

- [desktop demo](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=381-19174&t=3VGghz7vWoClPktT-1&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302&mode=design)
- [mobile demo](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=373-19561&t=J3kGfLvpwQs1MIsu-1&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167)

Does this work for you?

**Comment by CraigClark** [comment]
Stuck pending client feedback

**Comment by mjmcclung** [comment]
> Stuck pending client feedback

On the list for tomorrow! :)

**Comment by mjmcclung** [comment]
I added feedback to the mobile prototype in Figma.  All feedback would apply to the desktop version as well.

**Comment by CraigClark** [comment]
These changes have been reviewed. Some will be implemented. We can work on that next sprint.

**Comment by CraigClark** [comment]
@mjmcclung @NicoledeGreef I've left a comment on the [prototype](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=373-19561&t=J3kGfLvpwQs1MIsu-1&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167).

In the example provided on what things should look like in the node view, it isn't clear to me how someone gets to the term page. 

We could link each level of the taxonomy, but I'm not sure that's useful. All the important info is on the last term. Would it make sense to have the entire IM classification details link to the last term's page?

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/2917930b-252b-4397-9cb9-5dbe8d52b9eb)

**Comment by CraigClark** [comment]
@lkmorlan I have changes for this in branch [192-information-schedule-changes](https://github.com/bcgov/MFIN-Data-Catalogue/tree/192-information-schedule-changes)

I'm not sure how to do the per-processors to get the terms to appear the way Melinda wants them. If you pull the branch and look at a node view for a node with values in the info schedule, the changes I need are in red text.

By parent in IM classification details, I mean the top level term.



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/f2f615b5-66c2-4db6-8f4c-9be056e90ee6)

**Comment by CraigClark** [comment]
@lkmorlan Please have the value for the IM classification details link to the term page for whatever the last selected term in the hierarchy.

If we can do it, it would be ideal to only have the link if the last term in the hierarchy is selected, otherwise plain text,

so, in this example, https://dv21.openplus.ca/node/79, you would have 

```html

<a href="/taxonomy/term/tid">Property taxation: Property taxation - general: Policy and procedures</a>

```
because the full term depth is sepected.

if the whole term depth was not selected, you would only have 

```html

Property taxation: Property taxation - general

```

If it is complicated doing this, let me know

**Comment by CraigClark** [comment]
I'm going to close this and make a new task for the link

**Comment by CraigClark** [comment]
see #236
