### ISSUE TITLE
Develop Scorecard criteria for determining if data is considered Authoritative

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#194]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5351523761

---
Develop a scorecard to provide guidance to business reps when they are authoring metadata. This will be delivered outside the Catalogue application initially; possibly can be integrated with the app in the future.

**Comment by NicoledeGreef** [comment]
A while back there was some activity on the Discussion I started re: [Review of the flags on metadata records for Data](https://github.com/bcgov/MFIN-Data-Catalogue/discussions/201):

There was some talk of leaving out **Authoritative** in the MVP. "Authoritative" is currently a non-mandatory element in the model and user interface, applied to metadata records where their Type = "Data". It has not been suppressed as of Sprint 15.

Here are some questions we might be able to use for a scorecard now or later (open to suggestions):

Is the subject Data item...
- considered to be the primary or most reliable source for the information?
- tied to legal authority in terms of collection or management?
- considered to be accurate and reliable for a specific attribute(s) at any given time?
- representative of the most up-to-date data available and is generally the first system to be updated when data changes?
- restricted to  a select group of users that change stored data?
- managed and maintained ("generally owned?") by group(s) that can vouch for its authenticity?
- derived from the modification of data originating elsewhere (e.g., updating identity attributes for use in downstream processes, data normalization) and therefore becomes authoritative by virtue of performing the modification?

**Comment by mjmcclung** [comment]
I would suggest not pursuing this at this time until we have more information from the GCIO, or delegate.  From the Data Management Policy:

> The Government Chief Information Officer, or delegate, has the responsibility to:
> - Develop and maintain the process for identifying, reviewing and approving authoritative government data 

I would hope that they would come up with a scorecard or questions to ask as part of the 'identification' piece.

**Comment by NicoledeGreef** [comment]
OK - officially Iceboxed :)
