### ISSUE TITLE
High Value is a visual flag determined by the presence of other values

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#195]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5351529365

---

Display the high-value flag when `field_critical_information` is true.

## Original description

Develop a scorecard to provide guidance to business reps when they are authoring metadata. This will be delivered outside the Catalogue application initially; possibly can be integrated with the app in the future.

**Comment by NicoledeGreef** [comment]
A while back there was some activity on the Discussion I started re: https://github.com/bcgov/MFIN-Data-Catalogue/discussions/201:

Here are some questions we might be able to use for a scorecard now or later (open to suggestions):

Does the subject data...
- hold significant business value?
- enable decision-making in support of programs, services, evaluation, and accountability requirements benefiting a high number of users?
- ~~rate as being Authoritative?~~ (see #390)
- rate as being Critical? (see #196)

**Comment by NicoledeGreef** [comment]
We currently have a `High value info` attribute in the metadata model but is it truly needed?  According to the DMP when a data set is deemed Critical or Authoritative it is considered High value.   

If that is the case we could remove the `high value info` attribute from the metadata model.

We could apply a **High value** marker on a metadata record only when it is flagged as Critical (and/or later Authoritative). Thoughts?

**Comment by CraigClark** [comment]
@NicoledeGreef 

It might be more useful for users seeing _authoritative_ and/or _critical_ instead of _high value_ because those are more specific and explain what makes the MR high value.

I guess though, since critical and authoritative are in the property box, a high value label at the top if either of thesr are true would be a good visual indicator. 

Let's discuss tomorrow at the meeting.

**Comment by CraigClark** [comment]
@NicoledeGreef did you wan the award badge?



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/df687873-8537-4970-85db-44f35d0d599b)

**Comment by mjmcclung** [comment]
Food for thought...
I believe there will be instances where something may be high value but not necessarily Critical or Authoritative.  This would be useful to explore in a workshop-style discussion (not in comments on a ticket) with both data and business SME's where we can take some examples and flush them out to see where they land (critical? high value? both?).  This may require us to define high-value and critical in a more explicit way, or perhaps this is an outcome of this workshop process.  High value and/or Critical may mean something different between ministries and we should define what it means for Finance.

**Comment by CraigClark** [comment]
This works on dv14. I'll leave to @NicoledeGreef to close

**Comment by CraigClark** [comment]
@NicoledeGreef we might need another ticket related to this. On the reports page, we have blocks for critical and authoritative assets. What happens to those as a result of this change?

**Comment by NicoledeGreef** [comment]
Corporate blue badge with the icon looks like.  Please remove "info" from the label.

**Comment by CraigClark** [comment]
@lkmorlan ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/195-label-high-value

This is a two part fix. The branch adds the custom bg for the badge and we need a composer update to bring in the new icon from the base-build.

**Comment by CraigClark** [comment]
Assigning to Liam for merge/review

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
reviewed in dv14; @lkmorlan please change label from "High value info" to "High value"

**Comment by lkmorlan** [comment]
Text updated.

**Comment by mjmcclung** [comment]
Noticed in conversation with Christa today that High Value is still referenced in the help (from back when it used to be its own checkbox).  This needs updating.

**Comment by NicoledeGreef** [comment]
Something to be aware of: the Documentation is content and we are only consistently updating Documentation in Production since the postgres migration completed. I see it in Production: https://cat.data.fin.gov.bc.ca/documentation/metadata-fields#high-value-info

**Comment by NicoledeGreef** [comment]
reviewed in dv14
