### ISSUE TITLE
403 for anonymous users on home page/dashboard

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#197]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5359612469

---

## Describe the bug

When an anonymous user goes to the home page, there is a 403 error. When I check the logs, I see

Label | value
-- | --
Type | access denied
Date|Thursday, October 19, 2023 - 13:36
User|Anonymous (not verified)
Location|https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/
Referrer|https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set/wip-additional-property-transfer-tax-att-application-refund-forms
Message|Path: /. Drupal\Core\Http\Exception\CacheableAccessDeniedHttpException: The 'view data_set revisions' permission is required. in Drupal\Core\Routing\AccessAwareRouter->checkAccess() (line 115 of /var/www/html/core/lib/Drupal/Core/Routing/AccessAwareRouter.php).
Severity|Warning
Hostname| \*.*\*.*\*.*\** (IP obscured)
 

## To reproduce
Steps to reproduce the behaviour:
1. As anonymous user
2. Go to https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca
5. See 403 error message

## Expected behaviour
I see a page wit the BC logo at the top

## Screenshots

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/249bde19-3fa1-42f2-8332-b4adc03e7eee)

## Additional context

This is only happening on the homepage, which is the dashboard. I can get to other content without issue, ie <https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set/additional-property-transfer-tax-att-appeal-files>

**Comment by lkmorlan** [comment]
Design for dashboard for anon users: https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=381-19302&t=Jy2mCfflc8JaCGkF-1&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302&mode=design
