### ISSUE TITLE
Incorrect URL in dataset update overdue notification

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#199]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5365319869

---
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f7370981-fd8a-4d27-bf1b-5d7e754f23f0)

**Comment by CraigClark** [comment]
@NicoledeGreef is this still happening to you?

**Comment by NicoledeGreef** [comment]
As of the Dec 31 notifications it was still happening.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/0048ebfe-28cd-4dec-80ca-1f21695c0d42)

**Comment by CraigClark** [comment]
This should be fixed. We can wait until Sunday to see if email goes out with correct URL.

**Comment by CraigClark** [comment]
@NicoledeGreef Did you receive email Sunday? Was the URL correct?

**Comment by NicoledeGreef** [comment]
Sunday Jan 13th was still "default"

**Comment by NicoledeGreef** [comment]
I received emails from dev and test environments and the messages are reflecting the correct URLs.
