### ISSUE TITLE
Bulk upload for Data Dictionary data

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#20]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4606147836

---

## User story

As a metadata provider, I want to have a way to bulk upload Data Dictionary data (for columns in my dataset), so that I save time on data entry and reduce the risk of human error during input.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Additional context

When creating a data-set, there is potential for there to be more columns in the data dictionary than is reasonable to enter manually. A way to manage columns in bulk is necessary. 

On the data-set content type, there is a field called `field_columns` that accepts unlimited values. This is an entity reference to the paragraph type `data_column` which has several fields where a user can enter values. There are several different field formats available in a data column.

We are looking for a way to bulk import data into these columns.

## Proposed solution

TBD by developer.

Note that we do something similar on RSAMS. Jose has experience doing some advanced work with csv.

## Definition of done (DoD)
- [x] csv file can be used to import information into data-set
- [x] csv columns map correctly to fields in dataset columns

### Automated functional tests

- [x] I have written functional tests for this feature
- [x] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

No

**Comment by NicoledeGreef** [comment]
@CraigClark please fix template as mentioned in Planning

**Comment by lkmorlan** [comment]
@NicoledeGreef Some of the columns allow only values from a fixed vocabulary. For example, `column_type` may only be "String", "Boolean", and a few others. We need to figure out what happens if a person uploads a file which includes a value that is not in the allowed vocabulary. 

What I am working on now is having it highlight the invalid value and display a list of allowed values so that people can correct their upload file.

Question for you: Should it be case-sensitive? For example, if the file contains "boolean" should that map to "Boolean" or raise an invalid value error?

**Comment by CraigClark** [comment]
@lkmorlan I know you are still working on this. I did some preliminary evaluation today. Looks good, there were two things that struck me.

**CSV vs TSV**

Is there a reason we are using `*.tsv` instead of `*.csv`? I think csv is more commonly used. If it needs to be tsv, we should update all the language around the field to say tsv.

**Issue with Excel**

I downloaded the sample file and added some values to upload. I kept getting an error for an empty column. I think this is something Excel is doing. I tried a few ways in Excel to get rid of it, but no luck. If I open the tsv in a text editor and remove the extra <kbd>tab</kbd> it imports fine. @NicoledeGreef can confirm, but I suspect Excel is the tool people are most likely to use for this, so whatever we do, we should see if there's a way to make it work with Excel. That being said, we aren't here to fix Microsoft issues. Something to be aware of.

**Comment by NicoledeGreef** [comment]
CSV is most common, and Excel is the most common means of creating CSV for business users. CSV would be the ideal format.

**Comment by lkmorlan** [comment]
It will accept both `tsv` and `csv`. It uses the file extension to determine how to parse it.

It may be that Excel adds an empty column at the end. I could have the code trim the lines first.

**Comment by CraigClark** [comment]
@lkmorlan I'll test the csv out of Excel to see if we have the same issue with blank columns. If CSV/TSV doesn't matter to Drupal, lets just use csv for everything. Any help text or alerts, field labels, that sort of thing as well as the sample file that can be downloaded. We should stick as close to what users are familiar with as we can.

**Comment by CraigClark** [comment]
@lkmorlan I tested:

1. download test file
2. open in excel
3. add values
4. save as `csv`
5. import to dv21

This fails because Excel adds a comma at the end of the first row. I've attached the file for reference. I tried an export from Numbers and it works fine.



[excel-export-sample-for-data-dictionary.csv](https://github.com/bcgov/MFIN-Data-Catalogue/files/11970087/excel-export-sampla-for-data-dictionary.csv)



> **Note**: @NicoledeGreef , Just an FYI, we have had issues with other  clients using Excel generated `.csv` files in French. This is because Excel does not encode unicode properly in csv. If you have special characters in the csv, they won't encode correctly. This will definitely be an issue for many Indigenous languages.

**Comment by lkmorlan** [comment]
While working on this, I encountered and reported this bug:
https://www.drupal.org/project/drupal/issues/3374239

**Comment by CraigClark** [comment]
Results from uploading various csv files

| **test** | **upload time <br> seconds** | **import time <br> seconds** | **load edit page <br> seconds** |
| -------- | ------------------------------ | ------------------------------ | --------------------------------- |
| 100 rows | instant | 1.75| instant |
| 500 rows | instant | 3.75  | 5 |
| 1000 rows | instant | 30.83 | 8 |
| 1500 rows | instant | 56.77 | 4x49 |

> **Note**: While there is no max number of rows that can be imported in Drupal, there is a limitation that is set by the environment the application is hosted on.

## Issues

### Max file size error

To duplicate

1. upload a csv with 100 rows
2. import
3. on the build page beside data columns , click *edit*
4. select *edit all* at the top of the page
5. select *collapse all* at the top of the page
6. see error message
   > An unrecoverable error occurred. The uploaded file likely exceeded the maximum file size (8 MB) that this server supports.

### Data columns opens in edit tab

1. once csv has been imported
2. on the build page beside data columns , click *edit*
3. see that *edit* is the active tab at the top of the page
4. select the *edit* tab and see that you are now on the node/edit page

### Load edit page

For now, we need to go to the node edit page to publish, edit is taking a long time to load, even with only 100 rows. Probably because it is loading 100 paragraphs.

## Notes

For future discussion, maybe we should get rid of the UI for editing rows and do it all by CSV. There is no need to act on this now, but something to keep an eye on once people start working with the system

@lkmorlan

**Comment by lkmorlan** [comment]
Max file size error: In web posts, similar issues have been caused a variety of web server config issues such as the use of Suhosin or ModSecurity. Even if it is not that, this would be a Drupal issue. The relevant code is not code new to this project. The edit/collapse buttons work correctly when there are fewer items. The issue can be reproduced by expanding all items and collapsing just one. This only happens when there are a large number of items (the cut-off is unknown).

Data columns opens in edit tab: The edit pages are form modes of the regular edit page, so they use the same tab. We can override this with some hook. We need to figure out what it should do.

Load edit page: If we want the publishing to be done some other way, we need to figure out what that should be.

None of these issues are directly related to the CSV upload. They should be noted elsewhere so that this can be merged and closed.

**Comment by CraigClark** [comment]
That makes sense @lkmorlan I'll create issues for the other problems then close this. I'll take over this issue until that is done.

**Comment by CraigClark** [comment]
New issue created from this. See #104

**Comment by CraigClark** [comment]
As per Liam's comment:

> Data columns opens in edit tab: The edit pages are form modes of the regular edit page, so they use the same tab. We can override this with some hook. We need to figure out what it should do.

we can close this and deal with it when we get more into interface. That will be a new set of issues.

**Comment by CraigClark** [comment]
Closing this. Identified issues are really part of the csv import feature, an issue has been posted for the memory issue and we will deal with the edit tab when we get into UI
