### ISSUE TITLE
Azure GUIDs appearing rather than human readable name

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#202]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5441125318

---

## Describe the bug
Azure IDs are appearing is at least a couple of places:
1 - in bulk re-assignment of metadata author (VBO)
2- at the bottom of a metadata edit screen

## To reproduce
Steps to reproduce the behaviour:
1. go to Content overview page
2. choose one or more records to re-assign
3. use VBO to-reassign author
4. see that Azure IDs are showing in the list rather than human readable names

## Expected behaviour
Human-readable user names

## Screenshots
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/96ac0f9c-1a2e-4979-8cdb-7de0f6b5d87b)

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/cbb7d889-e8ac-4fb1-bfd3-3ea9802e42c9)

**Comment by lkmorlan** [comment]
@NicoledeGreef How many users are there likely to be on the system? There are two different name selectors used by VBO, each with their own problems. One is for when there are fewer than 200 users and the other for 200 and above. If we know which one will be in use, we can focus our efforts on fixing that one. Fixing one does not fix the other.

**Comment by CraigClark** [comment]
Fixed
