### ISSUE TITLE
Delete temp files programaticaly

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#204]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5375266268

---

## Describe the bug

Files are piling up in `/tmp` on the dev server. These are data files. csv, xlsx, tsv and ods.

Joel reports that these are coming from BC. We need to make sure that whenever files are created, they only exist long enough for someone to download them. They should not stay in the tmp directory.

**Comment by CraigClark** [comment]
@lkmorlan I'm not sure how to test this. Are there automated tests? can I just trust that this works?

**Comment by lkmorlan** [comment]
There are no automated tests for this. I did observe that files were being created then I made this change and observed that they are not being created. Note that the files were being created in `/tmp/systemd-private-021c24e92b074b20938ab1008cebcb53-php-fpm.service-E8hvgt/tmp/`.

**Comment by CraigClark** [comment]
I'll take your word for it and close this. I downloaded a csv which should have triggered a tmp file, I didn't have access to check the folder you mention
