### ISSUE TITLE
Remove book outline options from content types that are not books

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#207]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5391591733

---

## Describe the bug

When a user creates an MR, there is an option to add it to a book outline. Since MR is not a book content type, this should not be there. There is a hook on DV4 and other sites (ask Joel) that gets rid of it.

## To reproduce
Steps to reproduce the behaviour:
1. Go to /node/add/data_set
3. Scroll down to the bottom
4. See that there is an option to add the page to a book outline

## Expected behaviour
Since data_set is not configured to use book at /admin/structure/book/settings, I should not see book related options when working with data_set content type.

If the content type is in the allowed list at /admin/structure/book/settings, I see the outline options.

## Screenshots

This is taken from the data_set content type build page
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/c6413249-7e27-4db9-990f-2e1ce2af6b1c)

**Comment by lkmorlan** [comment]
Drupal core issue about this:
https://www.drupal.org/project/drupal/issues/2862291

**Comment by CraigClark** [comment]
@lkmorlan Joel has a fix for it we have used on other sites

**Comment by CraigClark** [comment]
Reviewed, I no longer see this issue on dv21

**Comment by CraigClark** [comment]
Re-opening

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/ccd5929f-0528-47a6-9a23-412b6b532231)

I'm getting this when I try to save a build section, role = DC editor, I thought we had fixed this
I don't have the problem as admin

**Comment by lkmorlan** [comment]
- [x] When this is completed, let Craig know the solution.

**Comment by lkmorlan** [comment]
The patch in this issue appears to fix this issue:
https://www.drupal.org/project/drupal/issues/2918537

**Comment by CraigClark** [comment]
Tested and passed on dv21
