### ISSUE TITLE
Data Dependency report

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#208]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5410271222

---

## User story

As a Data Catalogue user
I want to access reports
So that I can gain insights into the data holdings of the Ministry.

As a Ministry of Finance Data Management rep
I want to access a report that will give me insights into the data holdings of the Ministry and their dependencies
so that I can use that info to determine priority datasets in support of planning activities that relate to or impact data holdings in the Ministry.

## This feature support the following requirements
#137 

## Additional context
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/2e3e8076-f3d4-4a9f-8c10-0b7fd8d4f844)

This should be a view in Drupal

Data managers should be able to discern what the foundational datasets are within the Ministry. If we see that, for example, 50 data sets and reports happen to be using the same source, that is significant, and we can be fairly confident in the documented dependencies and prioritize activities based this report.
 
The report would be a matter of harvesting all the relationships between metadata records and then grouping them and ordering with the items that have the highest degree of dependencies at the top of the report. For the purposes of the mockup below I will just label items as “MR #” but obviously the title would be better in a real report and hyperlinking to the MR. “…” just indicates more dependencies that would appear in a real report.
 
 
MR 322 (Used in 50 items)
               MR 101
               MR 136
               MR 197
               MR 201
               MR 231
               ….
 
 
MR 421 (Used in 46 items)
               MR 235
               MR 456
               MR 504
               MR 563
               MR 776
               ….
 
MR 421 (Used in 43 items)
               MR 102
               MR 225
               MR 286
               MR 324
               MR 456
               ….

**Comment by CraigClark** [comment]
What do we mean by most consumed MR? Is it the MR that uses the most MRs as dependencies?

**Comment by NicoledeGreef** [comment]
In this case it's "Most consumed data" in the process of building of other data assets.  In other words, evaluate all dependencies but order the output so the item with the most dependencies shows at the top of the list and show all the items that are dependent on it.  The relationships are defined by metadata editors in MRs through the use of _field_data_sets_used_

**Comment by CraigClark** [comment]
@NicoledeGreef yes, that's our understanding. This report will probably be a table, most consumed MR at the top and in descending order. We will have filters similar to the info schedule. When we get to characterizing this, we will specify the fiend and filters you need.

Would it be useful to go the other way too? So most dependencies and most depended on?

**Comment by NicoledeGreef** [comment]
The items with the most things built off it have the most dependencies/are the most depended on in our data ecosystem. That's really what is useful here.  Showing what those dependencies is beneficial: Item 101 is used in Items A, B, C, E, and H

It would also be good to know that Item H is based on Item 101, Item B and Item 62 (this is a different report, I think)

**Comment by CraigClark** [comment]
@NicoledeGreef 

How is this pattern?


>[!IMPORTANT]
>Ignore the tab in the screenshot, this should be under reports and accessible by all IDIR users.


![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/3316c993-f6f6-4e3b-bc26-3ceae648ee44)

**Comment by NicoledeGreef** [comment]
I like it - can we export all to CSV and/or expand all and print to PDF?

**Comment by CraigClark** [comment]
I can ask about expand all, should be doable, we did it on the data dictionary.

as for csv, I'm not sure what that would look like. Maybe we could have the dataset as a column heading and dependant datasets as column values, I'd want to verify that with @lkmorlan or @joel-osc

**Comment by NicoledeGreef** [comment]
CSV would be pretty basic, just an ungrouped (flat) listing of item and dependent items, in the spirit of:


item_name, item_link, dependent_ item_name, dependent_item_link
"Test Data set", https://test.cat.data.fin.gov.bc.ca/node/322, "A test data set", https://test.cat.data.fin.gov.bc.ca/node/101
"Test Data set", https://test.cat.data.fin.gov.bc.ca/node/322, "My test report", https://test.cat.data.fin.gov.bc.ca/node/151
"Test Data set", https://test.cat.data.fin.gov.bc.ca/node/322, "Fun data set", https://test.cat.data.fin.gov.bc.ca/node/250
"Test Data set", https://test.cat.data.fin.gov.bc.ca/node/322, "A named MR", https://test.cat.data.fin.gov.bc.ca/node/345
"Test Data set", https://test.cat.data.fin.gov.bc.ca/node/322, "One big test", https://test.cat.data.fin.gov.bc.ca/node/450
"Test Data set", https://test.cat.data.fin.gov.bc.ca/node/322, "Hello world", https://test.cat.data.fin.gov.bc.ca/node/475
......

**Comment by CraigClark** [comment]
There is code already to expand/collapse details elements. see https://github.com/bcgov/MFIN-Data-Catalogue/blob/1.0.x/html/themes/custom/dc_theme/js/mr.js

**Comment by mjmcclung** [comment]
Question: is this a report-based version of something that will be dynamic at some point in the (far) future?  I can see other dependencies being of interest now (e.g. datasets by source system) and in combination with other information in the future (datasets by infrastructure).

**Comment by NicoledeGreef** [comment]
@mjmcclung The long term vision is to represent relationships between the subject items in the catalogue in a more dynamic way (for example: using a graph DB such as Neo4j).  The Finance Data Catalogue we are developing is a first step towards that because it gives us a better picture of what data assets exist and all the particulars about them. Once we're satisfied that things have come a ways in that regard, loading into a graph DB will be useful. Happy to see that Drupal has at least one module that is for Neo4j; see blog post: https://neo4j.com/blog/graph-databases-drupal-neo4j-module-rules-integration/

It is to be determined whether the Data Catalogue capability remains with Drupal for years to come. If it works well for everyone, why not? If we need more that Drupal cannot deliver there are commercial alternatives; many of these include graph DB based functionality.

**Comment by mjmcclung** [comment]
Understood.  There is a need to know dependencies by Source System, which fits under the user story of this ticket, however it doesn't necessarily need to be in graphic form.  It could be just be in report form, with CSV export as above.  Shall I create a separate ticket for this report need?

**Comment by NicoledeGreef** [comment]
> Understood. There is a need to know dependencies by Source System, which fits under the user story of this ticket, however it doesn't necessarily need to be in graphic form. It could be just be in report form, with CSV export as above. Shall I create a separate ticket for this report need?

Please create a new ticket.

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
Reviewed in dv14.

Please change "dataset" to "asset" where applicable:

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/1860259f-2ef9-490b-b0cc-83a86dae5dd2)

Also please add CSV export and the toggle details JS.

**Comment by lkmorlan** [comment]
Rename of "dataset" to "asset" implemented on `dv14`. I grepped the code for other uses of "dataset" and updated those as well.

**Comment by CraigClark** [comment]
The collapsible details portion is done and waiting for review/merge by @lkmorlan  https://github.com/bcgov/MFIN-Data-Catalogue/tree/208-add-toggle-to-details-on-data-dependency-report

**Comment by NicoledeGreef** [comment]
Toggle looks good.

Moving to "To do" until the export to CSV is completed.

**Comment by CraigClark** [comment]
@NicoledeGreef As per out discussion about the complexity of this, can we close this? I'll make another ticket about a report builder

**Comment by NicoledeGreef** [comment]
Closing because we cannot export from this screen. Report builder ticket investigation is #395

**Comment by CraigClark** [comment]
@lkmorlan some adjustments ready for review/merge here https://github.com/bcgov/MFIN-Data-Catalogue/tree/208-enhance-data-dependency-report

**Comment by lkmorlan** [comment]
Merged
