### ISSUE TITLE
Search Terms Report

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#209]
**OP timer**

---

## User story

As a Data Catalogue user
I want to access reports
So that I can gain ensure my metadata is tagged appropriately to enhance discovery of data.

## This feature support the following requirements
#137 

## Additional context
"Search Term" = text that users entered and submitted to search the catalogue's content
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/6fc9e6e0-bb69-451f-9939-347ca8d675c2)

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by CraigClark** [comment]
Drupal doesn't do this type of analysis. Typically this would be done by Matomo (in BCs case)

**Comment by NicoledeGreef** [comment]
We will shelf item this until Matomo implementation.
