### ISSUE TITLE
Info Schedule Missing Report

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#210]
**OP timer**

---

## User story

As an Information Management specialist
I want to access reports
So that I can gain insights into the state of information management within the metadata records in the Data Catalogue.

## Additional context

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/58bfff42-9573-4184-a2da-787c9fe3e1a6)

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by CraigClark** [comment]
We can talk about this. I'm not sure how to generate this since we have decided to allow for partial info-schedule. We cannot go by if the field is empty or not. Liam might have an idea.

**Comment by lkmorlan** [comment]
Is the need to create a report of MR that do not have a leaf value in their information schedule field? Unless there is a feature for this I am not aware of, we would have to make a query to get the list of leaf terms and then query for MRs that are not tagged with one of those.

**Comment by CraigClark** [comment]
1. can we have sort for schedule?
2. can we attaching a csv download for reports would be useful. The module is already installed for it
3. can we add org and make it sortable
4. Also permissions, right now anon can see this. It should be for DC admins
5. Since this report is for IM folks, they will probably want a NID too, in case MRs have the same name

**Comment by joel-osc** [comment]
Added a PR with these changes: https://github.com/bcgov/MFIN-Data-Catalogue/pull/270

**Comment by CraigClark** [comment]
This is done and was demoed at sprint review
