### ISSUE TITLE
Metadata Records by Office of Primary Responsibility (OPR)

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#211]
**OP timer**

---

## User story

As a Data Catalogue user
I want to access reports
So that I can gain insights into the data holdings of the Ministry.

## Additional context
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/34a2bde4-c75d-4b55-9131-1461b82cec2b)

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by CraigClark** [comment]
@NicoledeGreef How is this different than the search results by OPR facet?

**Comment by NicoledeGreef** [comment]
Agreed this is fulfilled by the "Meta data record management" view.  

Catalogue Manager role confirmed can access this tab 
but a Cat Manager can currently unpublish items that are restricted outside their org (bug being created for this).
