### ISSUE TITLE
Global dashboard for logged in users of the Finance Data Catalogue

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#213]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5434944965

---

## User story

As an authenticated user
I want to see high level metrics about Finance Data Catalogue holdings (through the global dashboard)
So that I can see how my contributions fit into the overall data landscape at Ministry of Finance.

As a Finance Data Catalogue Administrator
I want users to see how their domain's contributions fit into the overall data landscape
So that there is recognition of the importance of contributing and maintaining metadata, helping to improve Data Awareness within in the Ministry and recognition of the Ministry's data holdings by interested parties in other Ministries.

## This feature support the following requirements

#60
#70
#82
#94
#137

## Additional context

Mockup:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f16b0991-90e3-438d-af58-068baadc8d64)

See attached PDF for more detail:
[Finance_Metadata_Dashboard_Concept_Mockup_2023Nov1.pdf](https://github.com/bcgov/MFIN-Data-Catalogue/files/13229602/Finance_Metadata_Dashboard_Concept_Mockup_2023Nov1.pdf)

## Proposed solution

The mockup contains 3 types of widgets:

Statistic blocks: 

- Number of Published Metadata Records (includes all Types: Form, Dataset, Report)
- Number of Overdue Metadata Records (includes all Types: Form, Dataset, Report)
- Number of Critical Datasets (only includes Datasets, no Forms or Reports)
- Number of Authoritative Datasets (only includes Datasets, no Forms or Reports)

Pie Charts (or another representation of the attribute values):
- Metadata Records by Information Classification (includes all Types: Form, Dataset, Report)
- Metadata Records by Restriction (includes all Types: Form, Dataset, Report)

Top 5 Lists:

- Display top 5 Bookmarked Datasets across the Catalogue
- Display top 5 Bookmarked Reports across the Catalogue
- Display top 5 Bookmarked Forms across the Catalogue

## User Interface Considerations

- Rename "My dashboard" to "Dashboard"
- On the Dashboard there are two tabs similar to the default Drupal node tabs: default tab is "My dashboard" and the other is "Metrics & reports"

**Comment by CraigClark** [comment]
We need to discuss where in the UI people find this report

**Comment by CraigClark** [comment]
For consideration https://www.drupal.org/project/charts
billboard.js and highchart have the nicest charts, I think highchart is a paid service though, not sure

**Comment by CraigClark** [comment]
#327 will be deployed along with this feature

**Comment by CraigClark** [comment]
related #341 341
