### ISSUE TITLE
Theme search page

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#214]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5441555471

---

An HTML file has been created that applies the styles necessary to implement the theme done in figma. the html files are in the [theme/html](https://github.com/bcgov/MFIN-Data-Catalogue/tree/theme/html) branch. See the folder `theme_html` at the root.

## Notes
These templates use bootstrap classes where ever possible. Some previously written custom css will need to be removed once templates are updated to use BS.

- [x] ~~remove class `block-views-exposed-filter-blocksite-search-block-1` from `bcbb_theme/scss/components/_search.scss`~~ **Turns out we need this**
- [x] merge changes in `themes/custom/dc_theme` in the `theme/html`  into 1.0.x branch

## Issues

On the search page, the event that activates the collapse has a css style that disables the pointer at certain breakpoints. I think if a thing can be clicked or is disabled should be announced by aria, but I'm not sure how to do this? JS maybe?

- The theming for the search page should be part of the base-build
- The layout should be done using page manager

Figma references

- [mobile](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=373-19167&t=J3kGfLvpwQs1MIsu-1&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167&mode=design)
- [desktop](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=381-19302&t=6OMIzijwr6cpkrH5-1&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302&mode=design)

**Comment by CraigClark** [comment]
Not sure how to apply correctly to base-build. Most of it should work, however the block for 'save this search' and all the things for exporting to csv/xlsx are specific to the project.

**Comment by lkmorlan** [comment]
Feature request made to `search_api` module. I ended up fixing this for our use in a form alter.
https://www.drupal.org/project/search_api/issues/3401922

**Comment by CraigClark** [comment]
@lkmorlan This is ready for review

there are three feature branches to make this work

- save this search block: https://github.com/bcgov/MFIN-Data-Catalogue/tree/214-theme-search-page
- adjustments to layout module in base-build: https://github.com/bcgov/bcbb/tree/2-col-layout-changes
- base build theme (most of the changes) https://github.com/bcgov/bcbb-theme/tree/17-basebuild-search-theme-updated

## Known issues

- [x] there was a minor adjustment to the search results view. This is in config sync for the DC, but it might need to be in BCBB. _Edit: The changes cannot be applied to `bcbb`._

- [x] A11y, in the collapsible blocks for save this search and facets there are tags to tell screen readers if an element is open or not. The element visibility is controlled by css, so these don't change at full width screen.  I'm not sure what to do about this, JS maybe? _Will be addressed in #243._

**Comment by CraigClark** [comment]
related issue added, see #243
