### ISSUE TITLE
Search results can be downloaded as `.csv`

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#22]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Base-build%20candidate

**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4606244178

---

## User story

As a  user of the data catalogue, I want to be able to download the results of my searches so that I can use the results for analysis and reporting.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Additional context

This feature currently exists on Evri. See [dv10 for an example](https://dv10.openplus.ca/en/search/studies?search_api_fulltext=Emissions).

1. a user does a search
2. there is checkbox beside each result
3. user has option to select all results
4. there is an option to download csv
5. all fields of the data-set content type are in the csv

Verify that there are no HTML tags in the csv output. This has been an issue on previous implementations of this feature.

### Screenshot

This example is from dv10

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/216683ec-66b9-4dcb-9061-10d4852b12a6)

## Proposed solution

Use the same modules and config as dv10, customized as needed for data-catalogue.

## Dev workflow

- [x] I have written functional tests against the UAT test cases
- [x] I have run the functional tests and they pass
- [ ] I have written integration tests on areas that may be affected by this feature
- [ ] I have written integration tests under conditions which the feature should not work
- [ ] I have run the Integration tests and they pass
- [ ] I have added a comment to this issue with steps the reviewer needs to follow when doing QA
- [ ] I have verified that the feature is ready for QA in the development environment.

## Definition of done (DoD)

As a regular user:
- [x] on the search page I have checkboxes beside each result
- [x] I  can select all results
- [x] I can select all results, then individually select results I do not want
- [x] I can download a csv
- [x] the csv rows match what I selected on the search page
- [x] the csv columns match the columns in the data-set content type
- [x] There are no HTML tags in the CSV output

## Manual testing

The automated tests do not do any tests on the content of the downloaded file.

**Comment by CraigClark** [comment]
@lkmorlan This was working the other day, but it's failing now. Could you please look into it? It would be great if it could be resolved by the demo on thursday

**Comment by lkmorlan** [comment]
It is failing only for anonymous users. This appears to be caused by this:
https://www.drupal.org/project/vbo_export/issues/3257067

**Comment by lkmorlan** [comment]
Drupal core issue filed:
https://www.drupal.org/project/drupal/issues/3371433

**Comment by lkmorlan** [comment]
Bug identified and reported in `vbo_export`:
https://www.drupal.org/project/vbo_export/issues/3378511

**Comment by CraigClark** [comment]
Reopening:

We need to get rid of the search export UI for anonymous users. Exporting a search creates a file on the server so it can be downloaded. This is something we don't want anonymous users, especially bots, doing.

**Comment by NicoledeGreef** [comment]
reviewed in dv21
