### ISSUE TITLE
metadata content model: Granularity

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#220]
**OP timer**

---

After discussion with business reps, we should keep Granularity in the content model since it is already there but we should not expose it in the UI for the time being.

- [ ] remove the hierarchical taxonomy values as they will be refined as and when we decide to use Granularity
- [ ] ensure Granularity is not exposed in the user interface
- [ ] remove Granularity from the Documentation **or** indicate that it is a placeholder for possible future incorporation (we can discuss at Backlog Refinement)

**Comment by CraigClark** [comment]
This seems straight forward, though I think if you aren't going to use it, it might be better to remove it all together and add it back when needed. There is danger of it becoming cruft. 

@lkmorlan thoughts?

**Comment by lkmorlan** [comment]
It's easy to add it back in. That would be easier than keeping it there but hiding it.

**Comment by CraigClark** [comment]
I'll remove it

**Comment by CraigClark** [comment]
Done https://github.com/bcgov/MFIN-Data-Catalogue/tree/220-metadata-content-model-granularity, waiting for approval and merge
