### ISSUE TITLE
Group similar elements under a sensitivity and significance heading

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#221]
**OP timer**

---
Add value to the metadata information by grouping elements that speak to sensitivity and significance under a single header.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/100699fd-fcc5-469c-bf2c-dbeb99b6e37a)

**Comment by CraigClark** [comment]
@NicoledeGreef this is different than what we have planned for badges. I'll park this as an idea for now, once that is ready for review we can circle back to this if it fails UX.

**Comment by NicoledeGreef** [comment]
I don't disagree with the idea of grouping these items together but for Alpha we are going with what the business users asked for when we engaged them on sorting.  We hope to hold UX focus groups in the new year that will further inform the evolution of UI.
