### ISSUE TITLE
Theme individial build section edit pages

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#222]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5476612407

---

This task refers to the page the user sees when they click 'edit' on the build page.

Much of this has been done on RSAMS, refer to that as a reference and any needed code.

### Remove extraneous elements

1. Remove the _About formats_ link that appears under each textarea field
2. Remove the _Publish_ checkbox
3. Remove the Drupal vertical tab menu  
   ![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/25a9a1c9-0c3c-4802-bfc9-4b19ac002073)

### Items to add
1.  Delete should be a Cancel button, clicking this takes user back to the build page without any changes being applied.

### functionality adjustments

- if a dropdown has 3 or less options, use buttons instead  
in this example, _Remove_ and _duplicate_ would be exposed as buttons
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/0d2c9e6c-4fa1-4cd5-ac1e-4ebf5844bac4)

## Theme adjustments

Apply the layout, colours and icons as per the prototype.

> **NOTE:** BC uses a customized bootstrap approach to icons. [read the wiki page on icons in the BC base-build](https://github.com/bcgov/bcbb/wiki/Using-icons)

- [mobile](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=390-26771&t=1vOqU2Mw0YjNWtFo-1&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167&mode=design)
- [desktop](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=567-8238&t=cjQMwHvpF3rL826Z-1&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302&mode=design)

## DoD

- [ ] About formats is removed
- [ ] publish checkbox is removed
- [ ] Drupal vertical tabs are removed
- [ ] Cancel button has been added
- [ ] Clicking _Cancel_ takes people back to the build pages without applying changes
- [ ] Layout looks like the prototype
- [ ] Icons added to buttons
- [ ] buttons are used instead of drupdowns if there are 3 or less options

**Comment by gurjinder12** [comment]
@CraigClark https://github.com/bcgov/MFIN-Data-Catalogue/pull/241 PR for all the points mention in ticket except the dropdown to btn in paragraph field. I found where to update the twig template the only issue is with the theme suggestion not working.
