### ISSUE TITLE
Drupal local tasks (tabs) are not displaying on page variants in page manager

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#223]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5478421451

---

## Describe the bug
When creating a page in page manager, the local tasks are not showing up at the top of the page on page variant.
This is the set of tabs with view/build/edit/revisions etc typical on Drupal nodes and terms.

See an example here https://dv21.openplus.ca/node/17/

There have been related issues reported to Drupal.org
 - [Local tasks on overrides node/taxonomy pages were disappeared](https://www.drupal.org/project/page_manager/issues/2850355)
 - [Local Tasks Menu are not showing on D10](https://www.drupal.org/project/page_manager/issues/3363310)

This is happening to all roles with permission to access the variant, including admin.

## Possible solution

Joel thinks we need to add routing to the yml. See RSAMS for an example

### References

- https://github.com/openplus/site-rsams/blob/dev/html/modules/custom/gcext/gcext.links.task.yml
- https://github.com/openplus/site-rsams/blob/dev/html/modules/custom/gcext/gcext.module
- https://github.com/openplus/site-rsams/blob/dev/html/themes/custom/gcext_wxt/config/schema/gcext_wxt.schema.yml

## Expected behaviour

I see the local tasks tabs on a page variant

**Comment by lkmorlan** [comment]
Fixed by #198.
