### ISSUE TITLE
Document: Assign TAC Lite ORG via form on user profile

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#225]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5484216479

---

Create a field on the user that is an entity reference to the org taxonomy.

Allow multiple values (check boxes is fine, we can re-visit if org ends up being a huge list or changes to a hierarchy)

When a value is assigned in this field, it automatically updates the user's tac lite settings. These are currently under the _Access by taxonomy_ tab, which the data catalogue admin does not have access to.

RSAMS does this, copy however it is done on RSAMS. 

- see [gcext module](https://github.com/openplus/site-rsams/blob/7347ef9d14720c502f607348c4ad33925bb52cf0/html/modules/custom/gcext/gcext.module#L408)
- see [gcext tokens](https://github.com/openplus/site-rsams/blob/7347ef9d14720c502f607348c4ad33925bb52cf0/html/modules/custom/gcext/gcext.tokens.inc#L8)

This will make it easier to business admin's to assign orgs to users and it provides a field on the user that tells us what org they belong to.

**Comment by lkmorlan** [comment]
Patch to `tac_lite` allowing configuration of which fields are used:
https://www.drupal.org/project/tac_lite/issues/3403235

**Comment by CraigClark** [comment]
This works in 1.0.x

**Comment by CraigClark** [comment]
Need to add documentation so DC admins know how to assign orgs and so DEVs know we are not using tac_lite page

**Comment by CraigClark** [comment]
Documentation for data catalogue administrators is here https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/user-management

Documentation for developers is here https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Features#restricting-access-to-a-metadata-record
