### ISSUE TITLE
Create MR with a webform

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#226]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5484530834

---

When an editor goes to the landing page, there is a block for them to create a _new_ MR. It has fields for a title and an OPR.

This block is a webform; the [webform content creator](https://www.drupal.org/project/webform_content_creator) module created the node.

When the node is first created, it is in the draft state and shows up in the _My unpublished records_ table.

## The webform

The webform has a field for the title and the Office of primary responsibility. 

To do this we will need the following:

- A view that will get the logged in users org (use the field created in #225 )
- A webform block with two fields, one for the MR title (Node title) and one for the OPR (the user's org field)

The org field is an entity reference to the view for the user's available orgs. There is something similar at https://hcdev.openplus.ca/en/admin/webform/manage/create_a_new_alert.

What we want is a block that has the title field, the org field is pre-populated. If the user belongs to more than one org, privide a select list.

A user **cannot** select an org they are not  member of.

related #215

**Comment by CraigClark** [comment]
@lkmorlan This worked for me as admin.

1. Changes needed

- [x] data catalogue editors, managers and admins need to be able to use the webform to create node
- [x] dc admin should be able to change the OPR in section 2 of the build page
- [x] remove existing button to create a node for all roles


![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/fcf3b53f-3ab3-4b79-a088-f534a2bb96fc)

- [x] on the build page, everyone with access should be able to see the opr, but not change it in form display. It is ok to hide this field on form display, no need to display but disabled

**Comment by CraigClark** [comment]
@lkmorlan I tested this and it works, a few change requests. 
For the field formatter on the webform and the build section, please use a select list (drop down)

If I do not belong to an org, I should not be able to add a MR here. This works, I don't have access to the form if I do not have an org. However, I can see the block title. Please make the title go away for people who do not have the correct role/org combination to create an MR

**Comment by joel-osc** [comment]
Maybe instead of making the block title go away you add text indicating that the user does not have an org and to contact an admin to fix it.

**Comment by lkmorlan** [comment]
- [x] Use select list for the OPR when both creating and editing MRs.
- [x] Error message when there is no org: "You need to belong to an organization to create meta-data records. Please contact [Use the site email address for now] to have an org assigned to you."

**Comment by CraigClark** [comment]
Documentation on using the webform to create content has been [added for staff](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/creating-and-editing-metadata-records)  and for[ developers](https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Features#creating-a-record).

**Comment by lkmorlan** [comment]
Bug found and reported:
https://www.drupal.org/project/webform/issues/3403835
