### ISSUE TITLE
Add help text to fields in edit mode

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#228]
**OP timer**

---
Using the descriptions from the documentation, add Help text to fields in the UI (metadata fields and data dictionary fields)

- [x] @CraigClark to provide a list of those to @NicoledeGreef 
- [x] @NicoledeGreef  refine the help text
- [x] @CraigClark incorporate into the field descriptions

**Comment by CraigClark** [comment]
@NicoledeGreef 

below is the help text I'll be adding to the form fields. If you want to make any changes:

1. edit this comment
2. strike out the help text I have here, to do that, wrap the  entire block of text I've written in double tildes like this `~~strike out the description Craig wrote~~`, it will render like ~~strike out the description Craig wrote~~.
3. below that paste the new help text.

This is the fastest way to do edits, I'll copy your block of text and replace mine.

- I have left out fields that I don't think need any further instructions
- links won't work from github, but they will work from Drupal
- **To discuss** There appears to be some inconsistency between use of tje word _column_ and _field_
- I am assigning this to you, once you refine and/or approve the help text, I'll get it into Drupal

---

# Help text for fields

## Metadata records

### field_authoritative_info

~~Data that is recognized through governance, law, or common acceptance as the source of origin for accurate data.~~

- [x] Authoritative Data is recognized through governance, law, or common acceptance as the source of origin for accurate data.

### field_columns

~~Values stored in the data dictionary.~~

- [x] Columns that make up the data dictionary.

### field_critical_information

~~This dataset contains information critical to the public interest or government business continuity. [more infornmation…](/node/72#critical-information)~~

- [x] This dataset contains information critical to the public interest or government business continuity. [more information…](/node/72#critical-information)


### field_data_quality_issues

~~Describe in plain language any known issues with the dataset quality.~~

- [x] Describes, in plain language, any concerns with the quality of the item.


### field_data_sets_used

~~Select other data sets used in creating this dataset.~~

- [x] Select other data sets used in creating this item.

### field_data_set_historical_change

~~Clearly document any known changes to the item, including name changes, definitions, or transformations.~~

- [x] Clearly document any known changes to the dataset, including name changes, definitions, or transformations.

### field_data_set_type

~~Select the product type, dataset type and format. [more information…](/node/67)~~

- [x] Classify the item according to type, sub-type and format as applicable. [more information…](/node/67)

### field_high_value_info

~~The information in this dataset supports decision-making for programs, services, evaluation, and accountability, benefiting a large number of users.~~

- [x] High Value Information indicates this item holds significant business value, enabling decision-making for programs, services, evaluation, and accountability, benefiting a large number of users.

### field_information_schedule

~~See the [documentation for the information schedule](/node/53)~~

- [x] Refer to the [documentation for the information schedule](/node/53)

### field_modified_date

~~Set for significant updates to this metadata record. Leave this alone for minor changes. _Subscribers will be notified of changes if this date changes_.~~

- [x] Only set for significant updates to this metadata record; do not modify for minor changes. _Subscribers will be notified of changes if this date changes_.

### field_published_date

~~The date the data set was first published.~~

- [x] The date the metadata record was first published.


### field_review_interval

~~The number of months between full reviews. [more information…](/node/74)~~

- [ ] The number of months between full reviews of this metadata record. [more information…](/node/74)

### field_series

~~Metadata records are grouped by series to help with searchability.~~

- [x] Metadata records are grouped by series to help with searchability.

### field_source_system

~~The source system that the dataset was extracted from.~~

- [x] The system where the data originated.

## Data dictionary columns

### field_column_allowed_values

~~Describe the values allowed in this field.~~

- [x] The values allowed in this column.

### field_column_data_quality

~~Describe in plain language any known issues with the data quality in this field.~~

- [x] Describes, in plain language, any known issues with the data quality in this column.


### field_column_description

~~In plain language, describe this field. If this is the primary key, show that here.~~

- [x] Describes, in plain language, this column; if it is the primary key, indicate that here.

### field_column_name

~~The name of the field in the source dataset.~~

- [x] The name of the column in the dataset.

### field_column_size

~~This can be in bytes, in characters etc, depending on the column type.~~

- [x] This can be in bytes, in characters, etc., depending on the column type.

### field_column_transformations

~~In plain language, describe any transformations that were performed on this field in the source dataset.~~

- [x] Describes, in plain language, any transformations that were performed on the source data to derive the column values.

### field_instance_of

- [x] These terms represent data that appear in more than one data set and can join data sets together. [more information…](/node/82)

### field_provenance_field_name

- [x] The form field name this data came from.

### field_provenance_field_number

~~The field number _eg: a21_~~

- [x] The field number _e.g.: a21_

### field_provenance_field_question

- [x] The plain language question that was asked for this field.

### field_provenance_form_name

~~The plain language name of the form. *eg: Foreign Income Verification Statement*~~

- [x] The plain language name of the form. *e.g.: Foreign Income Verification Statement*

### field_provenance_form_number

~~The form number. *eg: T1135*~~

- [ ] The form number. *e.g.: T1135*

**Comment by CraigClark** [comment]
@NicoledeGreef , I'm working through this. for this field `field_published_date`, we can set that pragmatically and make it so it cannot be changed if it's for a metadata record.

When this field was created, I think the intent was for when the data set was published. Is that useful info? There are no fields that give me this information. So for example, the info schedule tells me when a data set is no longer usable, but I don't know the starting point.

**Comment by CraigClark** [comment]
Help text has been added to data_set content type and data_column paragraph fields
