### ISSUE TITLE
Add a permalink that can be copied from the node view

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#229]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5486883942

---

Add a permalink to the bottom of the node view. This link should be to the nid, ie. https://example.com/node/1234. This can be copied to the clipboard so people can easily share. See the share functionality on https://catalogue.data.gov.bc.ca for similar finctionality

## DoD

- [x] there is a permalink field that shows the full URL to the node in the format `https://example.com/node/nid`
- [x] user can click to copy the permalink

**Comment by CraigClark** [comment]
@lkmorlan I have this as far as I can take it. I have added the field and placed it in the template.

There is a request to have a 'click to copy feature'. I tried installing [clipboard.js module](https://www.drupal.org/project/clipboardjs) but I could not get the library to install.

Could you please get this set up? when it's ready, please show me how to install libraries, I followed the installation steps, but t didn't work.

Work so far is in the branch [229-add-a-permalink](https://github.com/bcgov/MFIN-Data-Catalogue/tree/229-add-a-permalink)

**Comment by CraigClark** [comment]
@lkmorlan the theming is done and ready for review on this

**Comment by lkmorlan** [comment]
Bug in `clipboardjs` module reported and fixed:
https://www.drupal.org/project/clipboardjs/issues/3401677
