### ISSUE TITLE
Subscribe to search criteria with notifications when search changes

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#23]
**OP timer**

<https://openplus.monday.com/boards/4092908516/pulses/4608223347>

---

## User story

As a user of the data catalogue, I want to be notified when data sets relevant to my work change, are removed or added so that I can be sure the data I'm working with is up to date and accurate.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Additional context

The user needs to be notified on dashboard and via email when a search changes. The user also needs a way to unsubscribe from searches.

## Proposed solution

On the dashboard, there should be a section for saved searches. There should also be an indicator that the search results have changed, a way to stop receiving alerts and a way to dismiss the change alert.

Saved search is done (#56, #92)

**Reference**: EVRI (DV10) does something similar.

> ### NOTES
>
> Instead of dismissing alerts, maybe the date the search last changed? Changed since last visit? Need ideas for how this functions.
> Is it possible to get some sort of diff of what the change was? ie *ABC has been updated*, *DEF has been removed*, *GHI has been added*

## Dev workflow

- [ ] I have written functional tests against the UAT test cases
- [ ] I have run the functional tests and they pass
- [ ] I have written integration tests on areas that may be affected by this feature
- [ ] I have written integration tests under conditions which the feature should not work
- [ ] I have run the Integration tests and they pass
- [ ] I have added a comment to this issue with steps the reviewer needs to follow when doing QA
- [ ] I have verified that the feature is ready for QA in the development environment.

## Definition of done (DoD)

TBD

- [ ] TBD

**Comment by NicoledeGreef** [comment]
Relates to being notified when something related to a saved search, as opposed to subscribing to a specific dataset's changes.

**Comment by NicoledeGreef** [comment]
the implementation of saved search result set change detection is far more complicated than the benefit that would be derived
