### ISSUE TITLE
Rabbit hole settings

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#230]
Add rabbithole to all taxonomies except the information schedule.

Info schedule is the only taxonomy where people should be able to get to the term page

**Comment by CraigClark** [comment]
To test

- [ ] as an anonymous user, I get a 404 whenever I go to any term that is not information schedule
- [ ] as an anonymous user, I see a term page for terms in the information schedule taxonomy

@lkmorlan could you please review and merge this? https://github.com/bcgov/MFIN-Data-Catalogue/tree/230-rabbit-hole-settings

When you are done, please close this issue

**Comment by lkmorlan** [comment]
Tests added. Merged.
