### ISSUE TITLE
Theme node view for metadata record

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#231]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5511901331

---

as per figma prototypes

- [mobile](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=373-19561&t=0Ut73yC13KS6pI2d-0&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167)
- [desktop](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=381-19174&t=0Ut73yC13KS6pI2d-0&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302)

## Changes form prototype

1. Unique ID will not be used, it's replaced by a permalink at the bottom of the page
2. information schedule has changes, this work is in #192

**Comment by CraigClark** [comment]
@lkmorlan I am done this as far as I  can get it.

Please see branch [231-theme-metadata-record](https://github.com/bcgov/MFIN-Data-Catalogue/tree/231-theme-metadata-record)

To Do:

- [x] We need a pre-process to show the node visibility. I've commented what I think it should do on [line 137 of dc_theme.theme](https://github.com/bcgov/MFIN-Data-Catalogue/blob/c64437d9987ce75512bf7a1e4f2bef574ef363f5/html/themes/custom/dc_theme/dc_theme.theme#L137)
- [x] This should display in the template after _Series_. I have some place holder html with the correct classes at [line 65 of node--data-set--full.html.twig](https://github.com/bcgov/MFIN-Data-Catalogue/blob/c64437d9987ce75512bf7a1e4f2bef574ef363f5/html/themes/custom/dc_theme/dc_theme.theme#L137)

Bonus:

- [x] if we can get a class of `public`, `authenticated` or  `restricted` based on who has access around the field or field label for visibility it would be useful. I was thinking a coloured circle in a`:before` could be useful in quickly determining if a record can be distributed or not.

**Comment by lkmorlan** [comment]
To make this work, the access flag field needs to be set on the "Public" and "IDIR" (Authenticated) organization taxonomy terms.
