### ISSUE TITLE
Install entity_embed

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#232]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5517241651

---

People with permissions should be able to add blocks in ckeditor

Install the entity embed module. For the DC, this is needed to show the view of TIDs on the help page for importing a taxonomy, however it's a pretty common feature. We may consider for base-build.

**Comment by gurjinder12** [comment]
Entity Embed module added to base-build and configure it in Project 
https://github.com/bcgov/MFIN-Data-Catalogue/pull/242
https://github.com/bcgov/bcbb/pull/33

Gurjinder Singh

**Comment by CraigClark** [comment]
This isn't working as I expected it would. I want to be able to embed a views block in ckeditor, specifically [this one](https://dv21.openplus.ca/admin/structure/views/view/information_schedule_term_ids/edit/block_info_schedule_entities). 

I know we do this on other sites, but I'm not sure how complex it is. Lets commit this as is, as it does allow embedding other entities. Views block embed seems to be [outside the scope of the module](https://www.drupal.org/project/entity_embed/issues/3065252)

I'll test this locally https://www.drupal.org/project/views_entity_embed and if it works, do another ticket for it.
