### ISSUE TITLE
Fix visibility of local tasks tabs

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#233]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5523984318

---

- [x] Remove the edit tab for everybody except administrators.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/1a8ff41b-ff80-4544-9177-ee9c9d8a984f)

- [x] Remove the book outline on every content type except book

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/4272f033-525a-4e64-8cfd-2fa62dbf0094)

- [x] Also, it should only show if I have permissions to edit the book

**Comment by gurjinder12** [comment]
Removed Edit tab from node page except Administrator role.
https://github.com/bcgov/MFIN-Data-Catalogue/pull/244

**Comment by CraigClark** [comment]
approved on dv21

**Comment by CraigClark** [comment]
@gurjinder12 The book outline is still there. 

1. as admin, go to any content type `data_set`
2. click on the build tab
3. See that there is an outline tab

Not that you do not see this when you first go to the node, you need to click on the build tab to see it.

This isn't just about tab visibility, none of those book features should be there unless the content type is configured to be a book at https://dv21.openplus.ca/admin/structure/book/settings

**Comment by gurjinder12** [comment]
Outline tab removed except admin https://github.com/bcgov/MFIN-Data-Catalogue/pull/247
