### ISSUE TITLE
Fix breadcumb for tabbed pages in a metadata record

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#234]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5524049139

---

When a user is on one of the tabs in a metadata record, the breadcrumb is _Home /  / Node title_

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/587f90bf-8868-4473-b781-a3ab660e9628)

It should be _Home / Data sets_ the same as the node view

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/c2a1835d-2051-4f44-825d-15907c6a8a8e)

**Comment by gurjinder12** [comment]
PR is ready for review https://github.com/bcgov/MFIN-Data-Catalogue/pull/245
