### ISSUE TITLE
Set form mode control permissions

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#235]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5524083804

---

Set form mode control permissions so the following roles can edit content prioperly

- Data catalogue administrator 
- Data catalogue manager
- Data catalogue editor

- [ ] test as a user with these roles to verify access

**Comment by CraigClark** [comment]
branch submitted for review https://github.com/bcgov/MFIN-Data-Catalogue/tree/235-set-form-mode-control-permissions

**Comment by lkmorlan** [comment]
Merged
