### ISSUE TITLE
Subscribe to dataset

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#24]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4608587659

---

## User story

As a person responsible for 

I want to …

So that …

## This feature support the following requirements

Describe or link to the requirement

## Proposed solution

Any ideas you have on how the feature could be implemented.

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [x] #26
- [x] #27 
- [x] #28 

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
relates to #26

**Comment by CraigClark** [comment]
I'm going to close this and create a new issue related to setting up the notification system. I thought @NicoledeGreef did this at sprint planning, however I don't see the ticket.
