### ISSUE TITLE
identify opps to parameterize reports

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#240]
**OP timer**

---
identify opps to parameterize reports

relates to #137 and other linked issues

**Comment by NicoledeGreef** [comment]
@CraigClark please review. I will update individual tickets once we've discussed.

[Report_Parameterization.pdf](https://github.com/bcgov/MFIN-Data-Catalogue/files/13603684/Report_Parameterization.pdf)

**Comment by CraigClark** [comment]
@NicoledeGreef 

## Feedback

### Search terms in the last 12 months

This should be handled by analytics software, matomo in this case

### Saved search terms in the last x months

This is complex. Searches are not saved as field values, they are saved as url stings, ie `/search?search_api_fulltext=additional%20NOT%20metadata&f%5B0%5D=series%3A120`

To do this, we would need custom code that can parse the stored paths then do whatever tasks we need done with the values. 

Before proceeding with this, we should evaluate what we hope to get out of it. Search terms themselves, as well as their popularity can be tracked in motomo, but not if the search was saved or not.

### Metadata records by OPR

We can do this, there is a partial implementation now on the dashboard

### For admins only - info schedule

This is done and has been demoed at sprint review. There is  a business issue to solve, right now, only DC admins can access this report. If access is granted to any other role, this may be in conflict with visibility by org. 

### Data lineage - most consumed data

We can do this as a table

**Comment by CraigClark** [comment]
@NicoledeGreef Please review my comments, if there are questions go for it, otherwise please close this. Individual reports will have their own tickets
