### ISSUE TITLE
Improvements to collapsible blocks on search results page

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#243]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5556190276

---

Related: #214 

## Describe the bug

On the search results page, there are two collapsible sections. The 'save this search' block, which is part of the data catalogue, and the facet block, which is part of the base-build. 

These use the bootstrap method of collapsing blocks with JS, and over-rides the css so the block shows as expanded on desktop versions.

There are aria controls for accessibility that announce the block as being closed even though it is open. Aria should inform screen readers of the true state of the block.

### JS approaches

1. We could use JS to change the aria labels appropriately based on a media query using the BS variable in the shadow dom.
2. We have the blocks enabled by default then use JS to add all the html that controls block visibility

The disadvantage of JS is that you need JS. How big of an issue that it, I don't know, but relying on JS to expose content goes against principals of progressive enhancement. 

### Details approach

We could use a details element, and use JS to toggle the open attribute as needed.

Advantage of details is that it will work without JS. We would only need JS to open it on desktop. Even without JS, users could open it themselves.

Disadvantages of details element is that we are limited in how it can be styled. Of more concern, we have no way to animate the open state. Especially for long bits of content like facets, it's better UX and A11y to have the content animate in than it is to have it instantly appear.

**Comment by lkmorlan** [comment]
The `details` approach is implemented in branch `243-search-blocks` in `MFIN-Data-Catalogue` and `bcbb`.

**Comment by lkmorlan** [comment]
The `details` will now open when the window is made wider. When open on wide, there are no disclosure triangles and the "save bookmark" icon appears as before.

**Comment by CraigClark** [comment]
Tested on dv14. Looks good
