### ISSUE TITLE
Theme term page in information schedule

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#246]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5563498713

---

Theme the term page for information schedule to look like the Figma prototype.

- [mobile prototype](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=560-4393&t=KmlCelCVaV5ewm93-0&scaling=scale-down&page-id=291%3A12856&starting-point-node-id=373%3A19167)
- [desktop prorotype](https://www.figma.com/proto/QFQoyhpG1qvtBwVuuBVikk/design-prototypes?type=design&node-id=572-8364&t=KmlCelCVaV5ewm93-0&scaling=scale-down&page-id=381%3A19173&starting-point-node-id=381%3A19302)

This shouldn't require any special classes, it's mostly getting the fields displaying correctly.

By default a term page will show a list of all nodes using the term, we don't want this.

If it's reasonable to do so, use the `field_abbr_full_name` in an abbr tag, so you would have something like `<abbr title="Calendar year>CY</abbr>`. 

Note that term pages except for information schedule are restricted by rabbit hole.

**Comment by mjmcclung** [comment]
The prototypes show a reference to "Schedule number" but on the referring metadata record page this combination of codes is referred to as "Schedule code":
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/1115892c-54cb-4cf9-b962-946b2bb2eb90)

- [x] The theme term page should be consistent and wording should be changed to match.  **Note that the proper wording is actually "IM classification code" so all references should be changed to this.** (see #248) The schedule code only represents the first part of this concatenation of codes.
