### ISSUE TITLE
Do not set moderation_state for edits from default form display

### ISSUE THREAD

**Issue by lkmorlan** [bcgov/MFIN-Data-Catalogue#257]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5623911383

---

## Describe the bug

When an edit is done using the default form display, do not set the `moderation_state`. Normally, `_bc_dc_form_node_data_set_edit_form_submit()` sets `moderation_state` to draft for all edits. 

## Expected behaviour
When the default form display is used, which administrators may do, it should save without setting `moderation_state`.

**Comment by CraigClark** [comment]
tested on dev and passed
