### ISSUE TITLE
Notifications when Bookmarked datasets change

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#26]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/stuck pending GC Notify config #111 

---

**OP timer**

<https://openplus.monday.com/boards/4092908516/pulses/4608593453>

---

depends on: #111 

---

## User story

As a  user of the data catalogue, I want to know when a dataset changes so that I can make downstream updates as needed.

> ## NOTE
> We need to discuss what constitutes an update. Do I get notified for every change? This could be annoying if I'm alerted to typo fixes for example. Maybe send the email when the last updated date changes?

Based on field_modified_date as a trigger for notification we want to send an email to the subscriber and put an updated flag/icon on their dashboard where the metadata record appears.  The flag/icon appearance is based on field_modified_date  being more recent than last_viewed_date.

Note: field_modified_date is updated not by the system but by the metadata author who must decide if it is appropriate to ensure that people interested in their metadata should be notified because the changes are significant and possibly impacting their business.

Email notification draft
subject: Dataset you've bookmarked has been updated
body:  <Title of data set> [link] has been updated

Example reasons for a metadata author to update the field_modified_date and trigger notifications to users that have subscribed.

- Metadata Record level:
  - Data Classification
- Data Dictionary
  - attribute names changing
  - attributes being removed
  - data type changes

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Additional context

Users need to have a way to subscribe to data-sets. A flag could work here, it should go in the UI near bookmarks. Subscribing sends an email when the data-set is updated. The same UI widget should allow people to unsubscribe. There should also be a dashboard where users can see a list of updated data-sets, from the dashboard users can stop subscribing to the data-set or dismiss the notification that the alert has been updated.

On the email implementation end of things, please look at this common component:
https://digital.gov.bc.ca/bcgov-common-components/notify/

## Proposed solution

Any ideas you have on how the feature could be implemented.

## Estimated level of effort

- 1 day

## Definition of done (DoD)
- [x] user receives email when a bookmarked dataset has been updated
- [x] indictor in dashboard when there has been an updated and the last viewed is older than last modified date
- [x] indicator goes away once the item is viewed and the last_viewed is newer than last_modified

### Automated functional tests

- [x] I have written functional tests for this feature
- [x] I have run the functional tests and they pass

**Comment by NicoledeGreef** [comment]
Subscription is considered synonymous with Bookmarks.  So if a bookmarked dataset changes, a user will be notified.

**Comment by CraigClark** [comment]
I've [submitted a request](https://digital.gov.bc.ca/bcgov-common-components/notify/) to GC Notify, confirmation ID is 379D7F2B

**Comment by CraigClark** [comment]
I'm going to list this as stuck until we get info on GC Notify #111
