### ISSUE TITLE
Main dataset page does not have footer located at bottom of page

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#265]
**OP timer**

---

## Describe the bug
The main dataset page has the footer content located in the middle of the page, obstructing the list of datasets.

## To reproduce
Steps to reproduce the behaviour:
1. Log In
2. Click on any data set in your dashboard
3. Click on Data sets in the bread crumb
4. Scroll down
5. Home, disclaimer, privacy, etc appear in the middle of the page.

## Expected behaviour
Footer information should appear at the bottom of the page.

## Screenshots
Problem page:  ![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/abe68756-c72a-4a6b-90f0-69aa3b4d8a96)
Expected look and feel: ![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/d37d1753-8d1c-4fd6-806a-ca4a8cf03179)

**Comment by NicoledeGreef** [comment]
i saw this as well a few days ago. things are very much in flux with the page that was previously called Dashboard. in the current build, users don't land there and there is no way of getting there without a backdoor. i suspect it will all be sorted soon - by end of Sprint 10 / alpha (dec 31).

**Comment by CraigClark** [comment]
@NicoledeGreef this was fixed in a build yesterday, you can [test on Openshift](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set) and close this of you approve
