### ISSUE TITLE
Have search facets link to definitions

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#266]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a catalogue user I want to understand the terms used as search facets so that I can better narrow down the search results for my purposes.

## Describe the idea
Catalogue users, especially public users, might not know or understand government terminology.  To help them get the most out of the data catalogue it would be helpful if the search facets could be hyperlinked to their definitions.  This way the user can better understand the search criteria they are applying and whether it reflects their search needs.

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
Hyperlinking is not feasible because the search facets in Drupal are filters so you click them you refine your search.

We'll include this in focused user testing to see how folks do.
