### ISSUE TITLE
Update MR delete and unpublish permissions

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#268]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5664145375

---

Currently Admin can do all the admin things we need.

Editors can only create/edit their org, cannot delete or unpublish.

DC managers can currently unpublish in any org. 

Typically Drupal handles permissions by Role. The introduction of an Org into the mix requires custom code. We have a partial implementation of this using `tac_lite`, however further refinement is needed the permissions.

>[!NOTE]
> related #219 

## DoD

  - [x] DC editor: delete own MR that has never been published if the org matches
  - [x] DC manager: delete any MR that has never been published if the org matches
  - [x] DC admin: delete anything
  - [x] DC editor: unpublish own published MRs if the org matches
  - [x] DC manager: unpublish any published MRs if the org matches
  - [x] DC admin: unpublish anything

**Comment by joel-osc** [comment]
We should discuss where in the UI we are going to allow the "delete" and "unpublish" actions - at least for the roles that do not have access to admin/content. For the DC Admin which does have admin/content we will need to ensure that they have an unpublish action which actually does the correct operation which is moderate the content to 'archived'.

**Comment by lkmorlan** [comment]
Those also appear as tabs on the content.

**Comment by joel-osc** [comment]
Yeah, that might need to go.

**Comment by CraigClark** [comment]
## TESTS

### Delete

- [x] as DC  editor:  CAN delete own NR that was never published
- [x] as DC editor:  CANNOT delete own MR that has been published
- [x] as DC editor:   CANNOT elete other user's MR that has never been published
- [x] as DC manager: CAN delete MRs in my org by any user, if they have never been published
- [x] as DC manager: CANNOT delete MRs in my org that have been published
- [x] as DC manager: CANNOT delete MRs in other orgs that have never been published
- [ ] as DC admin: CAN delete anything

### Unpublish

- [x] as DC editor: CAN Unpublish my published records in my org
- [x] as DC editor: CANNOT unpublish records in my org where I am not the author
- [x] as DC editor: CANNOT unpublish records where I am the author but my org has changed
- [x] as DC manager: CAN unpublish records if org matches
- [x] as DC manager: CANNOT unpublish records if the org does not match
- [x] as DC admin: CAN unpublish anything

**Comment by CraigClark** [comment]
Issues discovered while testing
- #292 
- #294

**Comment by CraigClark** [comment]
One test failed _as DC editor: CANNOT unpublish records where I am the author but my org has changed_

**Comment by CraigClark** [comment]
tested on dv21,  all cases pass now

**Comment by CraigClark** [comment]
documented here https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/creating-and-editing-metadata-records
