### ISSUE TITLE
Set conditional fields

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#269]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5664417903

---

As set in #84, some fields are conditional, see [the required fields spreadsheet](https://bcgov.sharepoint.com/:x:/r/teams/06981/_layouts/15/Doc.aspx?sourcedoc=%7BB7916BF2-A2B1-470A-8A5E-5BCDC4C93EB7%7D&file=BC_MFIN_DC_fields.xlsx&action=default&mobileredirect=true).

- [x] Show/hide fields on each edit page.
- [x] Show/hide fields on the build page.
- [x] When `field_columns` is hidden, hide Section 5 entirely on the build page.
- [x] Add selecting the root value for `field_data_set_type` to the creation form.
- [x] Make it not possible to change the root value for `field_data_set_type` in `shs`.
- [x] Validate that the root value for `field_data_set_type` has not changed.

Use `conditional_fields` module. The control field must be on each page; add it in a hidden element.

**Comment by NicoledeGreef** [comment]
The fields are documents in the linked spreadsheet. I am happy with them; please advise if there are any questions @CraigClark

**Comment by CraigClark** [comment]
@lkmorlan 

There is a module for conditional fields. One issue we have run into on other projects is that the field that sets the condition has to be on the same page as the conditional field(s). We got around this on other projects by putting the control field in a fieldset and hiding the fieldset.

**Comment by lkmorlan** [comment]
@NicoledeGreef Currently, `field_data_sets_used` will be hidden on metadata records of type "Form". It occurred to me that sometimes a form may in fact use a data set. So, perhaps this field should not be hidden. 

For example, if a person is designing next year's form, they may refer to last year's report to help them make design decisions. If a form has a field that has several options plus "Other", the person may want to refer to what people wrote in "Other" and add popular values to the form the next time it is issued.

**Comment by NicoledeGreef** [comment]
verified in dv14
