### ISSUE TITLE
give menu permissions to catalogue admin role

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#273]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5673199858

---
Ability to edit the footer and the user menu

**Comment by CraigClark** [comment]
Change is here https://github.com/bcgov/MFIN-Data-Catalogue/tree/273-give-menu-permissions-to-catalogue-admin-role

@lkmorlan please merge when you can.

**Comment by NicoledeGreef** [comment]
verified in dv21
