### ISSUE TITLE
Enable edit for text block on home page

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#276]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5682284478

---

The blurb on the home page, it's in a text block in a panels page. That's hard for the dc admin to update, we need something better

**Comment by CraigClark** [comment]
I created a custom block,
added it to the page variant
added permissions for dc admin to edit custom block

on export, variant and permissions export, not the custom block

**Comment by lkmorlan** [comment]
Joel wrote:
WxT does this... you can just bring it in with migration
You can look at profiles/wxt/modules/custom/wxt_ext/wxt_ext_migration/config/install

**Comment by lkmorlan** [comment]
`default_content_deploy` might be good for this.

**Comment by CraigClark** [comment]
Just a note, once this is done, I recommend removing `The Finance Data Catalogue is built on Drupal` from the homepage. It's extraneous information that I doubt most people will care about.

**Comment by NicoledeGreef** [comment]
Yes, I am waiting for this feature to be implemented and will be making edits including that.

**Comment by NicoledeGreef** [comment]
@lkmorlan - would you please tackle this ticket next?

**Comment by lkmorlan** [comment]
@NicoledeGreef Ready for review
