### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#28]
**OP timer**

<https://openplus.monday.com/boards/4092908516/pulses/4608608231>

---

depends on: #111 

---

## User story

As a data custodian, I want to be alerted when it is time to update a dataset so that I can make sure information is up to date and accurate for users of the system.

As a data catalogue editor, I want to know when a dataset is supposed to be updated so I know the information is timely.

Idea:
When editing a metadata record, include an unchecked checkbox for the author "Check this if this is a complete review." Checkbox is not setting a value, it's just a trigger for other things.

data_review_date field will be updated based on the checkbox activity.

duration field; defaults to 1 year but can be changed to 3 months, 6 months, 1 year, etc. (can be a taxonomy with number, units)

Send a notification email to author 15 days ahead of the date so they have time to action it.  Please make the number of days configurable to be changed by a drupal admin user.

Visual flag in dashboard as well.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

 2 days

## Amendment

This feature assumes that there will never be a high volume of alerts being sent out. Our assumption is less than 1000 every week. If it turns out that there is a high volume of alerts being emailed, a queue worker will need to be implemented. Documentation about this potential issue needs to be added to the [Features page](https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Features#information-schedule) of the Wiki. Include the symptoms that will occur if there are more requests than the system can handle and what will need to be done to fix the situation.

## Definition of done (DoD)
- [x] editors can select `this is a full review`
- [x] editors can set an update interval in months
- [x] when a record is updated, I see a label in my dashboard that it's been updated if I have it bookmarked. 
- [x] When I look at an record after it has been updated, the update label goes away
- [x] an alert appears on a record when a review is pending
- [x] an alert appears on a record when an update is overdue
- [x] in the dashboard, a badge tells me an update is pending
- [x] in the dashboard, a badge tells me the update is overdue
- [x] Every Sunday I receive an email telling me what needs to be reviewed within the next 30 days and what is overdue
- [x] There is documentation in the wiki explaining what will happen if cron sends too many alerts and how it needs to be remediated if this happens 

### Automated functional tests

- [x] I have written functional tests for this feature
- [x] I have run the functional tests and they pass

**Comment by NicoledeGreef** [comment]
date field with a default of last_modified + one year.  gives the metadata editor user a default date.  if the metadata record has been un modified for that length of time user gets notified.  user can override the date if there is something more business specific (e.g. Nov 15th).  can be used to theme a warning of approaching the date.  need some way to dismiss notifications; perhaps as simple as if they leave the date blank then the notifications are off for that record so there is always an option (it is opted in by default).

documentation should cover intent: to inform and re-engage metadata editors so that they keep their records current

**Comment by CraigClark** [comment]
@NicoledeGreef At this point, this works on requiring two things. 1) the complete review box is checked and an interval in months is entered. We will show you next week how this works.

What we don't have is a specific date people can select to trigger update reminders. Before we do that, I'd like to look into the business case for this. We can do it, I want to make sore it's not going to be an extraneous field.

**Comment by CraigClark** [comment]
@NicoledeGreef the way we are setting this up for now is:

1. An email will go out to editors every Sunday with a list of data sets that will need reviews within the next 30 days and data sets where the review period is past due
2. A notification will appear on the data set view that the public notifying if a review is pending or is past due
3. pending and overdue data sets are also on the dashboard.

**Comment by CraigClark** [comment]
I am assuming message will be sent Sunday, I see it in the logs, but I don't believe it's currently set for weekly

**Comment by CraigClark** [comment]
Renaming to match the field names and docs

**Comment by CraigClark** [comment]
Documented in the following places:
1. https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/data-set-fields#review-interval
2. https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/node/74
3. https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Features#update-interval

**Comment by CraigClark** [comment]
Confirming that emails are being sent out on Sunday. This was received Sunday October 22


![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/1cd1853c-9aad-403a-a2a1-6a94d19d4aac)

**Comment by NicoledeGreef** [comment]
I am getting one email at 12:00/12:01 each night.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/fdfb6801-5844-4319-9abc-32bddf779c61)

They are identical:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/9d06915e-79dd-4c9a-af9c-33381ca23e21)

"Colours" is a record in dv21, not our private Cloud environment. Could it be that the latest config/code has not moved to our Opensihft yet?
