### ISSUE TITLE
configure Analytics for the Finance Data Catalogue

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#285]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5695620214

---
Analytics desired

Reference tickets for use cases: #209 and #212

**Comment by NicoledeGreef** [comment]
We have options for analytics: Matomo and GDX Analytics Snowplow.  A decision has been made on a similar project to adopt Snowplow and I have some experience with the same in my previous portfolio. It seems likely we will follow suit and adopt Snowplow given that it is a viable option.  I watch [this repo](https://github.com/bcgov/GDX-Analytics-Drupal-Snowplow) and they have been making changes to support Drupal 10 as of late.

**Comment by NicoledeGreef** [comment]
Meeting scheduled on April 17th with internal devs that have experience in implementing Snowplow for Drupal.

**Comment by NicoledeGreef** [comment]
@NicoledeGreef to reach out to the GDX team ASAP in Sprint 17.

**Comment by NicoledeGreef** [comment]
@NicoledeGreef met with rep from GDX analytics team on April 30. GDX Analytics is creating a ticket that they expect will be actioned within 2-3 days. The details they provide will be actioned by developers of the Digital Services team. This is a candidate for inclusion in the base-build.

**Comment by NicoledeGreef** [comment]
@chrislaick to configure https://github.com/bcgov/GDX-Analytics-Drupal-Snowplow into the bcbb

**Comment by chrislaick** [comment]
Update on Snowplow:
I've submitted a PR to the GDX Analytics Drupal Snowplow repo on May 1st (https://github.com/bcgov/GDX-Analytics-Drupal-Snowplow/pull/22) to composerize the module and fix some PHPCS issues. I'm waiting for their team to review it and merge it in. Without composerizing the module, we can only install the module manually (copying the module into the MFIN Data Catalogue repo) and will not receive updates until we copy the module over again.

Alternatively, I've forked the GDX Analytics Drupal Snowplow repo and merged my PR in already in a personal repo: https://github.com/chrislaick/gdx_analytics_drupal_snowplow and plan to switch over the repo source once GDX finishes reviewing the changes. On the application side (MFIN Data Catalogue) all we need to do is composer require:
`    "bcgov/gdx_analytics_drupal_snowplow": "dev-main",` and ensure installer paths are setup correctly for custom drupal modules:
```
      "docroot/modules/custom/{$name}": [
        "type:drupal-module-custom"
      ],
```

@NicoledeGreef @CraigClark 

Do we want to wait for GDX to review the PR and merge it? Or do we want to use the forked repo like I did for FINtranet and plan the change of repo source after they've merged the code?

**Comment by chrislaick** [comment]
@NicoledeGreef I'm currently blocked on this because I'm having issues getting my local dev environment setup. I have DDEV installed, cloned the repo, run composer install, but I'm unsuccessful in importing config or importing the database from ea352d-prod. I'm hoping to have this resolved on Monday when we have another support session with OpenPlus.

**Comment by chrislaick** [comment]
@NicoledeGreef  PR https://github.com/bcgov/MFIN-Data-Catalogue/pull/493 submitted.

**Comment by chrislaick** [comment]
Here are instructions to test the Snowplow module with the [Snowplow Inspector Chrome extension](https://chromewebstore.google.com/detail/snowplow-inspector/maplkdomeamdlngconidoefjpogkmljm?hl=en-US&utm_source=ext_sidebar) after this gets merged and deployed:

1. Install Snowplow Inspector Chrome extension
2. Visit the MFIN Data Catalogue site
3. Once the page is loaded, open Chrome inspector (CTRL + SHIFT + I)
4. Select Snowplow tab
5. Browse site
6. View events being tracked in left column of the Snowplow tab e.g. SD Event: link_click

**Comment by chrislaick** [comment]
@NicoledeGreef Snowplow has been deployed to DEV.

**Comment by chrislaick** [comment]
@NicoledeGreef Snowplow has been deployed to TEST and PROD.

**Comment by NicoledeGreef** [comment]
Dashboard access confirmed; Prod analytics screen output is viewable and downloadable by both configured accounts.
