### ISSUE TITLE
Users are losing their roles when Admins change their Org

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#286]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5695693239

---

## To reproduce
Steps to reproduce the behaviour:
1. As a DC Admin user
2. Go to the User page
3. Change the Organization the user belongs to
4. Save
5. See the DC Admin user loses all their Roles

## Expected behaviour
When I change the Org(s) it has not impact on my Roles.

**Comment by CraigClark** [comment]
@lkmorlan applied a patch ti fix this, tested and passed on dv21
