### ISSUE TITLE
Improve appearance of data dictionary columns page

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#287]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5696952741

---

The data dictionary edit page could be improved by reducing clutter in the middle column and adding context to the column name

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/dd4f53b8-fb04-4ae9-bcfe-13edb27c895a)

## Expected Behavior

1. [x] "Data column" should be the name of the paragraph/field
2. [x] No need for description column/values
3. [x] Keep the Edit and Remove buttons

**Comment by lkmorlan** [comment]
Feature request created as part of implementing this:
https://www.drupal.org/project/paragraphs/issues/3414400
