### ISSUE TITLE
add ability to filter by Organization on the People admin screen

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#288]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5706206797

---
When an Admin user visits the People admin page they have the ability to filter the list of users. It would be helpful to add Organization to the available filters:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/63f5c2ce-014c-4da5-90f7-e6392c0d6829)

and ideally see the Org values for a user in the list:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/ae3ad1da-c45d-43fe-84e6-13bdaea275ea)

**Comment by CraigClark** [comment]
@lkmorlan please review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/288-filter-users-by-org

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified in dv14
