### ISSUE TITLE
Add age of metadata records to dashboard

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#29]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4608608231

---

## User story

As a Metadata Author, I want to have an overview of the metadata records I'm responsible for
so that I can be aware of records that are outdated.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Proposed solution

Create a view on the dashboard at `/user` of the data sets where author matches the logged in user. The view should initially have the following:

- title, plain text, no link
- last_updated_date (oldest to newest); last updated is set manually whereas Drupal has last_modified_date which is updated every time you make a minor change; the date and the relative date (calculated - e.g. 2 years 3 months ago)
- under a column called actions, have links to view or build the data set

Call the view 'My published metadata'

put it under the existing 'My unpublished metadata'

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] there is a dashboard view at `/user` that shows the data sets I have published, with the last_updated_date

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
Is it important to know the age of a metadata record (this ticket), or is it important to notify metadata authors that their datasets are approaching the update interval date so that they can take action  as specified in #28 , or both?  This is a good question for the user reps.

**Comment by NicoledeGreef** [comment]
I think that perhaps this is covered through #28 . We are not explicitly showing the age of metadata records but we are establishing an interval when users will be notified that a review has not been done.  We may make this mandatory and set a max months value to promote metadata utility (quality).

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/979d21c5-d2dd-4b02-b0c1-a19ec2a4cdeb)

**Comment by CraigClark** [comment]
@NicoledeGreef is it safe to close this then?

**Comment by NicoledeGreef** [comment]
i think so!
