### ISSUE TITLE
Dashboard and Manage links for user with no roles

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#290]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/question

---

## What's your Question?
Should a user with no roles applied to it be able to see a Dashboard link at all? 

Example:
Test de Greef account: https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/user/151/edit has no roles and no Org

When I go Incognito and don't log in there is no Dashboard link present.  
When I log in as "Test de Greef" there is a Dashboard link present but perhaps there should not be given my lack of roles. What does this account have other than the fact that I logged in?  

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/d27f9d41-a5de-45ac-b783-c3fe601f8fe8)

If the answer to question above is "yes", I also noticed the "Manage" tab is empty. Should it display for users with nothing to manage?

**Comment by CraigClark** [comment]
@NicoledeGreef 

Yes. Everyone who logs in with IDIR is assigned the role _DC user_. While they can't manage any content, they can use their dashboard for saved searches and  bookmarks. TBD, can _DC users_ see any of the reports, which are also on the dashboard.
