### ISSUE TITLE
Add ability for users to include more than one info schedule per metadata record

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#291]
_Originally posted by @NicoledeGreef in https://github.com/bcgov/MFIN-Data-Catalogue/issues/180#issuecomment-1745869552_
            
--> adding support for more than 1 schedule being applied to a metadata record

**Comment by NicoledeGreef** [comment]
We met to discuss this item among other in October 2023.  Notes indicate:

_In terms of applying more than one schedule it's not too bad UI wise if we are hiding most of the detail on the View and linking to more information_

This item was raised again recently by @mjmcclung and the dev team should discuss it in early 2024.

**Comment by NicoledeGreef** [comment]
Draft collection of info/impacts around this request to inform my decision. Open to comment.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/1700ec0c-7592-40f4-b152-4001f35985d8)

**Comment by mjmcclung** [comment]
Clarification line 1: business areas are required by legislation to manage their information in accordance with approved information schedules.  While IM specialists make use of the information within an information schedule during IM activities, the accountability rests with the business.  One of the biggest delays during IM activities (e.g. decommissioning) is having to sleuth out the applicable schedule.  This can cause considerable delay and increase costs.

Clarification line 2: I believe auditors were mentioned as one of the initial use groups of the catalogue.  As Christa mentioned, use of data for auditing could be a scenario where a secondary schedule applies.  Also, an IM Education & Awareness program is launching and Information Schedules will be a key part.  There may be more uptake on this as a result.

**Comment by NicoledeGreef** [comment]
Auditors will be onboarded eventually. FREDA and PTB are targeted before May 31.

When is the IM Ed & Awareness launch?

**Comment by mjmcclung** [comment]
I crafted a communication for HB to send out earlier this month and Tamara has taken it forward to him.  I will report back once I hear back.

**Comment by NicoledeGreef** [comment]
iceboxing for now
