### ISSUE TITLE
Dashboard: Autofill for owner shows IDIR account

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#293]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5713139179

---

On the [Meta data records management page](https://dv21.openplus.ca/user/1/manage), entering a name shows First Last User name. The user name is an IDIR string that is not human readable. This should show First, Last, email address.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/bc10bc9d-0dda-42b9-8177-c04f0a9b4260)

**Comment by lkmorlan** [comment]
Bug found and fixed during this work:
https://www.drupal.org/project/auto_username/issues/3410578

**Comment by CraigClark** [comment]
tested and depoyed
