### ISSUE TITLE
MR managers and admins need a way to find MRs that are not published

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#294]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5713223421

---

Currently, there is no way in the UI for Catalogue managers and Catalogue admins to find unpublished MRs.

## Proposed solution

On the view for _Meta data records management_, add a filter for state and a column in the table

**Comment by NicoledeGreef** [comment]
verified in dv21
