### ISSUE TITLE
Information schedule report sorting seems off

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#296]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5723148171

---

## Describe the bug
When I visit the Information scheduled report and sort by OPR I don't get the results I expect.

## To reproduce
Steps to reproduce the behaviour:
1. Go to Dashboard
2. Click on Reports
3. Click on Information schedule tab
4. Change parameters to:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/fc0f70ba-086d-4b63-af95-804114d8f468)
5. Click apply
6. Review the output, specifically the OPR column:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/ddbf4de3-20f0-4f53-b9c6-08542474e198)

## Expected behaviour
For Sort by OPR Ascending, it is expected that blank OPRs should all be listed together at the top and "Consumer Taxation Audit Branch" records should be listed before "Information Management Branch" records.

## Additional context
Same sort of thing occurs when you specify Descending. "Property Taxation Branch" should be at the top, followed by "Information Management Branch", followed by "Consumer Taxation Audit Branch", and then all the blank OPR records.

**Comment by CraigClark** [comment]
This could be an empty term. I've seen that happen

**Comment by CraigClark** [comment]
This has been resolved. There were blank terms in the vocabulary, likely brought in at an early stage of development.  I have gone through all taxonomies and removed blank terms and their children.

@NicoledeGreef please review and close

**Comment by NicoledeGreef** [comment]
It's better but the records where OPR  = Consumer Taxation Audit Branch are not showing up in the list where I would expect them.

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/480764c8-51e0-44b9-845d-75c6756543e5)

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/af64a7d0-e15e-4e1c-ae46-54b1476406e4)

**Comment by CraigClark** [comment]
Hi @NicoledeGreef 

I cannot duplicate this. I downloaded the csv on dev, sorted on the OPR column and it worked fine.

Can we screenshare what so I can see what is happening for you?

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/b94254ce-f5b2-46d9-a22f-a299b7ded5ed)

**Comment by NicoledeGreef** [comment]
It's possible it's sorting on term ID rather than label.

**Comment by NicoledeGreef** [comment]
Let's ensure we test all sorting options as needed.

**Comment by CraigClark** [comment]
@NicoledeGreef This is ready for review on https://dev.cat.data.fin.gov.bc.ca

Could you please review and close if you are happy with it?

**Comment by CraigClark** [comment]
Assigning to Nicole to test

**Comment by NicoledeGreef** [comment]
Looks good in dev - thanks!
