### ISSUE TITLE
Update to Drupal 10.2

### ISSUE THREAD

**Issue by lkmorlan** [bcgov/MFIN-Data-Catalogue#297]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5724419177

---

**Comment by lkmorlan** [comment]
Issues reported/fixed as part of doing this:
https://www.drupal.org/project/drupal/issues/3410098
https://www.drupal.org/project/form_mode_control/issues/3409223

**Comment by CraigClark** [comment]
Done, screenshot from prod environment


![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/3fbe493c-2433-4e9d-846f-bc7f8d0f3ab0)
