### ISSUE TITLE
new role for Information Management

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#298]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5731078104

---
- [x] create a new role: IM Specialist.  This is expected to be a very small group of users from the IMB; it is fine for this role to see all metadata records regardless of Visibility.
- [x] users with the role should have access to Info Schedule report(s)

For now, metadata editors users can edit the Information schedule values in their own metadata records.  We will assess this once we onboard a couple of groups; an alternative approach would be to restrict those fields and only let IM Specialists populate them.

**Comment by lkmorlan** [comment]
I have created the role "Data catalogue information management specialist". This role has the same permissions as DC user plus the access permissions of DC admin and access to View `information_management_report`.

**Comment by CraigClark** [comment]
tested on dv21 using IDIR account with info manager role, was able to see the report and download the csv.
