### ISSUE TITLE
links in custom footer content should target new browser tab

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#299]
**OP timer**

---
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/8e85a2c3-3962-45c4-bc9f-42923490a673)

**Comment by CraigClark** [comment]
@NicoledeGreef 

We may want to carefully consider why we want to do this. Opening links in new tabs usually introduces usability and accessibility issues.

## Resources

- UX info: Nielsen Norman Group [Opening Links in New Browser Windows and Tabs](https://www.nngroup.com/articles/new-browser-windows-and-tabs/)
- Accessibility info: W3C WCAG [G200: Opening new windows and tabs from a link only when necessary](https://www.w3.org/TR/WCAG20-TECHS/G200.html)

**Comment by NicoledeGreef** [comment]
That's a good point, @CraigClark. I don't want to adversely impact accessibility. We can educate folks about that and how they can right click to open in a new browser tab. Closing ticket.

**Comment by lkmorlan** [comment]
Even better than right-click is to middle-click, usually by pushing down on the scroll wheel without turning it. That directly opens the link in new tab.
