### ISSUE TITLE
Flag issue or question with dataset to dataset custodian

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#30]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4608677933

---

## User story

As a user of a specific data-set, I want to be able to raise issues, or ask questions about the data-set so that I can be sure the data I'm using up to date, accurate and timely.

> ## NOTES
> The immediate solution to this is to have the author's email address readily available. There is a plan to do this in the first iteration of the dev release. We could have the `NID` in the email subject, though that is easily over-ridden by the sender.
> Do we want something more advanced? As a team we need to characterise what this looks like. There should be an obvious way for users to submit a comment. Possibly a form. Custodians need to be alerted via email when there is an incoming question. 
> Do we want to keep a record with the dataset of incoming questions?
> If so, how long to keep them?
> What does the UI look like for the user?
> What does the UI look like for the custodian?
> What about back and forth communication (dialogue)?

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Proposed solution

Any ideas you have on how the feature could be implemented.

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
same as #77
