### ISSUE TITLE
Exclude user 1 from having their username updated by auto_username

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#302]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5772505542

---

Patch `auto_username` module so that it does not update the username of user 1. This allows them to login using `admin`. Follow-up of #293.

**Comment by lkmorlan** [comment]
Issues opened as part of implementing this:
https://www.drupal.org/project/auto_username/issues/3412418
https://www.drupal.org/project/auto_username/issues/3412423
