### ISSUE TITLE
Test search and configure accordingly

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#303]
**OP timer**

<https://openplus.monday.com/boards/4092908516/pulses/5793365757>

---

Validate search functionality.

### Search Indexing

- [x] Search is being indexed as scheduled via cron; when one or more new MRs are created they are incorporated into the search results within 30 minutes.

### Search functionality

- [x] search should include title
- [x] a single word or phrase should return results based on what's in the description field
- use of boolean operators (must be capitalized)
  - [x] OR
  - [x] AND
  - [x] +
  - [x] NOT
<s>- [ ] search using field:value pairing, for example *Title:"folio"*
- [ ] search with quotes. For example,  "traffic light" would return "the *traffic light* is red", but not "The traffic is light today"</s>

### Reference

>[!NOTE]
> **Reference**
> ![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/4c2936c4-63de-4d31-8a24-6bcb67c69a91)
>
>![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/38cd9d19-8901-4ec1-a37c-9d11b4259395)
>
>![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f6f15fc5-8829-4481-b0cc-1571f61b220f)
>
>Attachment sourced from: <https://heinonline.org/HeinDocs/AdvancedSearchSyntax.pdf>
>
> - Users can enter a term (single or phrase as defined above) in the search box and results returned should be based on matches in the *description* field of the MR
> - Users can enter more than one term (single or phrase as defined above) in the search box with operators and results returned should be based on the *description* field of the MR
> - Users can specify the scope of a search by specifying a field name and a term (single or phrase as defined above) using syntax, e.g. *title: "folio"*
> - Users can specify the scope of a search by specifying more than one term (single or
> - phrase as defined above) using syntax, e.g. **title: "folio" AND description: "full address"** enter more than one term or phrase (as defined above) in the search box with operators and results returned should be based on the field(s) of the MR that were specified

**Comment by NicoledeGreef** [comment]
@NicoledeGreef to check all the ways searches are done and log any issues/items in this ticket

**Comment by CraigClark** [comment]
- `OR` tested and passed on [test](https://test.cat.data.fin.gov.bc.ca/search?search_api_fulltext=Property+OR+Regulation). Finds results with any of the search terms, *This is the default operator, 'property regulation' will return the same thing as 'property OR regulation'*
- `AND` tested and passed on [test](https://test.cat.data.fin.gov.bc.ca/search?search_api_fulltext=Property+AND+Regulation) Finds results where both search terms are present
- `NOT` tested and passed on [test](https://test.cat.data.fin.gov.bc.ca/search?search_api_fulltext=Property+NOT+Regulation) Include the first search term, but exclude results that also contain the second search term
- `+` tested and passed on [test](https://test.cat.data.fin.gov.bc.ca/search?search_api_fulltext=Property++%2Bregulation) search terms with `+` are required, other search terms are optional

**Comment by CraigClark** [comment]
for fields, there is no operator, however people can use the facets to narrow results by field. @NicoledeGreef , with that in mind, I would like to pass this one based on the facets functionality.

**Comment by CraigClark** [comment]
Search is now indexing on cron. 

There is an [issue](https://www.drupal.org/project/search_api/issues/3274158) that causes indexing on revision save to fail.

We disabled index on save. Instead the site will be indexed every 5 minutes on cron run.

**Comment by NicoledeGreef** [comment]
> for fields, there is no operator, however people can use the facets to narrow results by field. [@NicoledeGreef](https://github.com/NicoledeGreef) , with that in mind, I would like to pass this one based on the facets functionality.

There's no question there is value in facets but enabling field based searching on title and description in particular is important. There are no facets for these as they are not discrete values like OPR, Series, Modified date, Source system, Metadata type, etc.

It would be advantageous to enable searching such as:

title:"leads" {OPERATOR} description:"refund"

**Comment by NicoledeGreef** [comment]
Questions: 
How do we specify a multi-word phrase as a search term that returns only hits with all the words in that order?  Google uses double-quotes for example.

**Comment by CraigClark** [comment]
@NicoledeGreef title is fixed. We boosted title in search results.

@lkmorlan please merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/303-boost-title

**Comment by CraigClark** [comment]
> > for fields, there is no operator, however people can use the facets to narrow results by field. [@NicoledeGreef](https://github.com/NicoledeGreef) , with that in mind, I would like to pass this one based on the facets functionality.
> 
> There's no question there is value in facets but enabling field based searching on title and description in particular is important. There are no facets for these as they are not discrete values like OPR, Series, Modified date, Source system, Metadata type, etc.
> 
> It would be advantageous to enable searching such as:
> 
> title:"leads" {OPERATOR} description:"refund"

@NicoledeGreef I talked with Joel about this today. Search API doesn't do this. We wound need to write a custom module that would allow this type of query.

Typically what we do for the use case you mentioned is develop an advanced view that people with a certain role can access. This would have many more filters than what is available in search. We can export results to csv or JSON.

**Comment by NicoledeGreef** [comment]
Let's hold off on custom development for now.  We just need to ensure that Solr/Search API is configured optimally. and that we document the options for advanced users.

**Comment by NicoledeGreef** [comment]
Title is boosted to 21
body (description)  is boosted to 1

**Comment by NicoledeGreef** [comment]
verified in dv14
