### ISSUE TITLE
saved search links from Dashboard failing

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#304]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5801069400

---

## To reproduce
Steps to reproduce the behaviour:
1. Go to https://test.cat.data.fin.gov.bc.ca/
2. Ensure you are logged in
3. Click on Dashboard
4. Scroll down to **Saved searches**
5. Click on one of your saved searches
6. See error msg as included in screenshot below

## Expected behaviour
Link doesn't fail; instead results in the list of items that are returned as a result of that saved search

## Screenshots
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/86e86532-9289-495e-9107-696b67276c73)

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/161d9a77-ae34-4b16-8853-5b7e3e1fa9bb)

**Comment by CraigClark** [comment]
@NicoledeGreef this could be happening because we changed the search path form `/search/site` to `/search`. In that case, previously saved searches won't work.

Could you please confirm if this is happening with old saved serarches or new ones?

**Comment by NicoledeGreef** [comment]
It looks like old ones fail and new ones work.  Can we purge old ones?

**Comment by CraigClark** [comment]
@lkmorlan 

is there a way to purge old saved searches?

If we do this, we will need to let people know that's what we are doing.

**Comment by lkmorlan** [comment]
Maybe a VBO? Might have to be a custom entity query or custom SQL query.

**Comment by CraigClark** [comment]
Is it possible to find out how many, and who has saved searches? @lkmorlan

**Comment by lkmorlan** [comment]
@CraigClark I'm sure we can get that information with either an entity query or an SQL query. Is finding that information what needs to be done for this ticket?

**Comment by NicoledeGreef** [comment]
On hold for now pending decision on whether we are migrating to postgres.  Moving to postgres will nullify this issue.

**Comment by lkmorlan** [comment]
It has been decided to move to Postgres; see #333.
