### ISSUE TITLE
Configure deployment to different OpenShift environments

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#306]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5809673061

---
This relates to how we trigger builds to various environments. 

1. Dev | Stable Git Tag (1.0.0)
2. Test |  Workflow Dispatch (manual) option in GitHub Actions
3. Prod | Workflow Dispatch (manual) option in GitHub Actions 

~~That being said, we should align with existing BC practices where it makes sense.~~

>[!NOTE]
> References:
>  * https://github.com/bcgov/fin-pay-transparency/tree/main/.github/workflows
>  * https://github.com/bcgov/quickstart-openshift

**Comment by NicoledeGreef** [comment]
Internal discussion happening on Jan 9

**Comment by NicoledeGreef** [comment]
Using helm and GH Actions is desirable and we already have that in place fir the Finance Data Catalogue.

Consensus is the proposed pattern is clear and simple. Recommended change: deployment to Test should be manually triggered through GitHub Actions, similar to Production.

Everyone agrees that if a change is needed, the change must go through Dev before Test, and Test before Production.

**Comment by CraigClark** [comment]
@NicoledeGreef I'm going to reopen this as a deployment ticket.

**Comment by NicoledeGreef** [comment]
Agreed to proceed with:

Dev | Stable Git Tag (1.0.0)
Test | Workflow Dispatch (manual) option in GitHub Actions
Prod | Workflow Dispatch (manual) option in GitHub Actions

**Comment by NicoledeGreef** [comment]
@CraigClark to verify with WH

**Comment by NicoledeGreef** [comment]
can we close this one @CraigClark ?

**Comment by sylus** [comment]
This can be indeed be closed as it has been implemented :)
