### ISSUE TITLE
Determine the purpose of each OpenShift environment

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#308]
https://openplus.monday.com/boards/4092908516/pulses/5810581267

There are three OpenShift instances of the data catalogue; dev, test and prod.

While prod is straightforward, we need to document the difference between test and dev so we all undterstand those terms the same way.

OpenPlus recommends

1. **Dev** is a stable tag pointing to say 1.0.0 but config/sync might have more options enabled for that environment and tools like devel*
2. **Test** is a complete clone of what will be in Prod and config sync will reflect that, this is the environment where features are reviewed before deploying to prod
3. **Prod** is Prod

**Comment by NicoledeGreef** [comment]
relates to #306

**Comment by NicoledeGreef** [comment]
Agreed to proceed.
