### ISSUE TITLE
Move panels patch from data catalogue to base-build

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#310]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5829142753

---

There are two patches in `composer.json` in the data catalogue repo that should be in the base-build repo. The brick layout in the bcbb layout module requires these.

The patches that need to be moved are:

```json
         "drupal/page_manager": {
                 "2756613 - Avoid harcoded prefex and suffix in block region": "https://www.drupal.org/files/issues/page_manager-avoid_prefix_suffix-2756613-8.patch"
            },
            "drupal/panels": {
                 "2820617 - Avoid harcoded prefex and suffix in block region": "https://git.drupalcode.org/project/panels/-/merge_requests/12.diff"
            }
```

**Comment by lkmorlan** [comment]
I added the patches to `bcbb`. I cannot find any place in MFIN-Data-Catalogue where these patches are added.

**Comment by CraigClark** [comment]
Thanks @lkmorlan They are in a development branch that I have.
