### ISSUE TITLE
Update taxonomy vocabulary names via config

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#313]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5834028300

---
If there is no technical reason for not updating these names/labels, please proceed as attached.

[Taxonomy_term_edits.pdf](https://github.com/bcgov/MFIN-Data-Catalogue/files/13895360/Taxonomy_term_edits.pdf)

**Comment by CraigClark** [comment]
merged into 1.0.x
