### ISSUE TITLE
Spike: decision on migration to postgres as the database backend

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#314]
**OP timer**

---
postgres has become the opensource DB of database at BCGov and it is available via the BC Openshift Container Platform (OCP). OCP is the Ministry IMB's preferred platform for application hosting and it offers Crunchy Postgres. 

Strategically, postgres is the database flavour to align with. Within the Ministry we intend to grow our capacity for administering OCP hosted apps and postgres.

This ticket is a spike to decide if we should pivot to postgres. 

- How much work is involved?
- What needs to be recreated or loaded manually post-site creation? e.g. taxonomy values
- Are there other aspects that will require more time and effort if we were to migrate?

**Comment by CraigClark** [comment]
@NicoledeGreef 

I talked to @sylus about this. Here is what's involved:

1. change helm so it uses postgres
2. build process would build the site using a new DB
3. any content has to be migrated into the new DB or created manually

As far as I know, content would be:

- any existing metadata records
- taxonomies
- help guide
- front page content

If we have any features that depend on content, they will need to be addressed as well. @liam would know more about that than I would.

**Comment by NicoledeGreef** [comment]
Here is an analysis to aid me in decision-making. Please advise if there are additional considerations to take into account or recommended changes to the ratings (e.g. features dependencies on content or ratings applied in the table).

@lkmorlan  - any concerns based on [this list](https://www.drupal.org/project/drupal/issues/2564307)?

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/4e6974bd-0974-4901-b9a7-1bf707e1e066)

**Comment by NicoledeGreef** [comment]
As discussed, let's plan to spin up a site in the dv environment with postgres backend in Sprint 12 and do some assessments. Decision will be based on what we find.

**Comment by NicoledeGreef** [comment]
@CraigClark Based on the initial success of the dv14 environment and demonstrated progress with content-deploy, as PO I greenlight the move to postgres.  Let's plan accordingly; we'll pivot if we need to.
