### ISSUE TITLE
Documentation for footer around hyperlink targets and accessibility

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#315]
That's a good point, @CraigClark. I don't want to adversely impact accessibility. We can educate folks about that and how they can right click to open in a new browser tab. Closing ticket.

_Originally posted by @NicoledeGreef in https://github.com/bcgov/MFIN-Data-Catalogue/issues/299#issuecomment-1885961152_
            
In documentation we should mention that, in support of accessibility, the footer links in the Data Catalogue are intentionally not targeting new tabs but that a user can open a link in a new tab by right-clicking and choosing that option.

**Comment by CraigClark** [comment]
@NicoledeGreef 
I wouldn't bother. You get into that and you are going to end up documenting a pile of 'why does this do it this way' that is explaining how websites work.  Keep docs specific to tasks people need to accomplish.

If you look here, https://catalogue.data.gov.bc.ca/ footer links open in the same window. I think most people know how to use either 'open in a new tab' or the back button. The expectation is that when you click a thing, you go a place.

**Comment by CraigClark** [comment]
@NicoledeGreef can I close this?
