### ISSUE TITLE
Document tac_lite settings

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#316]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5841509811

---

Much of the access control is done with `tac_lite`. These settings do not get exported as config because they depend on taxonomy terms that are content. This configuration is done on `admin/config/people/tac_lite` and the tabs on that page. 

Document how this is to be configured.

**Comment by lkmorlan** [comment]
@CraigClark I am unable to reproduce this. I set my IDIR account to be a DC manager with one org. If I visit either MR build page or the record management page I only see the unpublish links for the org I am in.

**Comment by CraigClark** [comment]
@lkmorlan we can wait for the next build and see if it remains an issue. On dv21, this is working for me as expected. 

On dev, it isn't.

Check [user 100](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/user/100/edit), that's my IDIR account. 

I am  role: dc manager and org: Information management branch.

When I log in with the IDIR account, I see unpublish for orgs that are not IMB

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/9d37f387-8eae-4981-b8f1-9ec0edc6703c)

If I choose to unpublish an MR for an org other than my own, it works.

**Comment by lkmorlan** [comment]
The problem was that the `tac_lite` settings were not correct. They were correct on `dv21`. This issue will become about documenting the settings.

**Comment by CraigClark** [comment]
These settings are content, not config. In addition to documentation, Liam had the following idea

> One option would be to have something that just checks the settings and displays what it thinks is wrong. They can still change it and just make note that certain differences are expected.

**Comment by CraigClark** [comment]
Done see https://cat.data.fin.gov.bc.ca/documentation/permissions
