### ISSUE TITLE
Add collapsible navigation to taxonomy edit page

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#318]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

https://openplus.monday.com/boards/4092908516/pulses/5849192212

---

## User story

As a data catalogue admin I want to be able to quickly find and edit a taxonomy term so that I use my time efficiently.

## Describe the idea
Taxonomy terms are currently displayed as an exhaustive list.  As our taxonomies grow (specifically the Information Schedule taxonomy) there will be much scrolling needed to find a given taxonomy term to edit.  If the taxonomy hierarchies had the ability to be collapsed in the display then this would bring the term of interest closer to the top.  Collapsibility would need to extend past the first hierarchy.

E.g. if I was looking for an ORCS term I would first have to scroll through all 600+ ARCS terms to get to the beginning of the ORCS terms.  If the ARCS hierarchy was collapsible, I could simply collapse it and the ORCS hierarchy start on the next line.

E.g. if I was looking for an ORCS term in the Property Taxation ORCS I would first need to scroll through all 600+ ARCS terms plus all the terms in the 7 ORCS schedules that precede the property taxation schedule.

**Comment by NicoledeGreef** [comment]
@CraigClark  - is this part of Drupal core?  I'm assuming we cannot change the admin UI for taxonomies.

**Comment by CraigClark** [comment]
@NicoledeGreef You can use the taxonomy manager for an easier way to see taxonomies, go to manage > structure > taxonomies. 

This is a module that improves the experience of working with taxonomies.

direct link https://cat.data.fin.gov.bc.ca/admin/structure/taxonomy_manager/voc

**Comment by mjmcclung** [comment]
@CraigClark Is this the same as what you see when you go to Manage > Structure > Taxonomy > Information Schedule?  If so, then the difficulties mentioned in the original post still apply.

**Comment by NicoledeGreef** [comment]
@CraigClark please enable Taxonomy Manager for _Catalogue admin_ role

**Comment by CraigClark** [comment]
Fixed in https://github.com/bcgov/MFIN-Data-Catalogue/tree/318-taxonomy-manager-permissons

Grants DC admin permission to use taxonomy manager module

@lkmorlan please merge



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/30b5e8bc-9fcf-4cd3-bfa1-9ae36928f7f0)

**Comment by NicoledeGreef** [comment]
verified in dv14
