### ISSUE TITLE
Update record life cycle duration taxonomy

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#319]
**OP timer**

Update record life cycle duration taxonomy as follows:
Current:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/938d40db-e56c-4e20-9048-7ba69a4d9420)

Changes:
CY should read Calendar Year
nil (No retention period) should be added
SO full name spelling should be updated to "Superseded" not Superceded
---

**Comment by NicoledeGreef** [comment]
In dev:

CY and SO modified as noted.
NA changed to nil - should NA be there as well?
FY left as it was.

**Comment by mjmcclung** [comment]
Yes, both nil and NA should be represented.  Both are present in the Information Schedules we are going to load.  Values should read as:

CY (Calendar year)
FY (Fiscal year)
**NA (Not applicable)
nil (No retention period)**
SO (Superseded or obsolete)

**Comment by NicoledeGreef** [comment]
Each environment reflects the following now:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/92d45fee-831b-4086-bb77-4ca8bc0c8f13)
