### ISSUE TITLE
Bulk re-assign data custodian process

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#32]
**OP timer**

<https://openplus.monday.com/boards/4092908516/pulses/4608689391>

---

> ## NOTE
>
> Somebody mentioned in the workshop that they would to see the lineage of data custodians.
> Is this something we want to do?
>
> Each node in Drupal has an author. We are using this author field as the data custodian. We will have to make sure that we change the build in author label as necessary and make sure anybody working on the admin side knows that author and data custodian are the same thing when it comes to the dataset content type.

## User story

As a data catalogue administrator, I want to be able to re-assign data custodians to data sets so that as staff come and go, each dataset always has someone responsible for it.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Additional information

The Data custodian is the node author.

## Proposed solution

- [x] verify that vbo is available, see <https://github.com/bcgov/bcbb/issues/5>
- [x] add vbo to the content overview page
- [x] make sure the ability to change authors is a vbo option
- [x] make sure data catalogue administrator role can access content page and run VBO actions

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)

- [x] VBO dropdown is available on the content overview page
- [x] Data catalogue managers can use the VBO to re-assign the node author

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
relates to #202
