### ISSUE TITLE
Update record disposition taxonomy

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#320]
**OP timer**

Remove the following value:
> OD (Other disposition) - have never seen this referenced or used, can add back in if/when it comes up
---

**Comment by NicoledeGreef** [comment]
'OD' removed in dev, test, and prod

https://dev.cat.data.fin.gov.bc.ca/admin/structure/taxonomy/manage/record_disposition/overview
https://test.cat.data.fin.gov.bc.ca/admin/structure/taxonomy/manage/record_disposition/overview
https://cat.data.fin.gov.bc.ca/admin/structure/taxonomy/manage/record_disposition/overview
