### ISSUE TITLE
Explore using a custom ID to solve duplicate problem when importing taxonomies

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#322]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a Catalogue admin user 
I want to be able to import taxonomies without manual work 
so that I can use my time effectively.

## Describe the idea
Currently the import tool used for taxonomies will not import terms with duplicate names.  This is problematic as there are duplicate secondaries in every information schedule (e.g. Policies & Procedures, General).  In ARCS alone there are over 200 instances of this.  The current work around is to uniquely rename the term before the import and then rename it back afterwards.  This will be a significant effort with so many instances.

Options:
1) Don't import the Policies & Procedures or General secondaries for ARCS.  Risk: chance that some catalogued assets might need these classifications.  This doesn't solve the problem of duplicate term names for ORCS though as there are 18 other types of duplicates to contend with.

2) Discuss the possibility of adding a field to the taxonomy to capture a unique code which would be used to specify the parent upon import.  This could be the IM classification code  (e.g. PTAX-43000-03 would be the unique code for the lower level, PTAX-43000 the unique code for the higher level, and PTAX the unique code at the schedule level).  This could be auto-calculated for any manually entered taxonomies, or be provided as part of a bulk upload.

3) Just spend the time and do the manual edits.

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
Re: **Option 1)** Don't import the Policies & Procedures or General secondaries for ARCS.  
Risk: chance that some catalogued assets might need these classifications.  This doesn't solve the problem of duplicate term names for ORCS though as there are 18 other types of duplicates to contend with.

_If we imported everything except the known duplicates (e.g. "Policies and procedures" and "General") we could add those missing ones manually once.  This is half the work of editing a load file and then re-editing the items once it's loaded._


**Option 4:** Intentionally don't bulk load anything below the Primary level primary; then manually add the Secondary schedule items into the taxonomy on an _as required_ basis. Rationale: ARCS and ORCS don't apply to the items our first intake group will be cataloging. It is assumed that our second intake, PTB, will be mostly ORCS (PTAX). Pros: we furnish what is needed when it is needed. Cons: we won't have a complete list with all items for users to peruse. May be minor lag between time when an option is needed and when it can be furnished in the taxonomy.

**Comment by CraigClark** [comment]
There is something else we can try. If, for child terms, we label them 'Policies and procedures 1', 'Policies and procedures 2' etc we might be able to export the taxonomy, edit it again then import it. Once we figure out #329 we should get a JSON file for the info schedule, should be easy to get rid of the numbers.

**Comment by mjmcclung** [comment]
> There is something else we can try. If, for child terms, we label them 'Policies and procedures 1', 'Policies and procedures 2' etc we might be able to export the taxonomy, edit it again then import it. Once we figure out #329 we should get a JSON file for the info schedule, should be easy to get rid of the numbers.

I like this this idea - like an update to the terms after they are initially imported.  It should be easy to append the unique code to the term name in Excel, and just as easy to strip that out using Excel for the re-import.

Re: Nicole's comment: _If we imported everything except the known duplicates (e.g. "Policies and procedures" and "General") we could add those missing ones manually once. This is half the work of editing a load file and then re-editing the items once it's loaded._
This is actually more work as there will be 11 fields to manually enter for each duplicate vs 1 field to manually edit (twice) using the renaming method.

**Comment by mjmcclung** [comment]
@CraigClark - I thought if a term name changed the importer would consider it as a new term?  If we export the taxonomy and edit the term names and re-import - won't it add all the edited items as new terms?

**Comment by CraigClark** [comment]
With the approach we are going to test, a UUID is exported. So it wouldn't matter what the label is, as long as the UUID matches. Give us a few days to run some tests and I'll get back to you.
