### ISSUE TITLE
Rename Information Schedule Report

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#323]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5850957241

---
Please rename the Information Schedule report from "Information schedule missing" to "Information schedule incomplete"

**Comment by CraigClark** [comment]
Done, @lkmorlan please merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/323-rename-information-schedule-report

**Comment by CraigClark** [comment]
done and deployed
