### ISSUE TITLE
User's ability to edit the title/name of their metadata record

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#325]
**OP timer**

---

I can create a metadata record. On Jan 15th, I created "Nicole Jan 15" but seemed unable to edit the name/title of the metadata record after clicking "Create". This is either a gap functionality or an education issue as to where this functionality is available to users.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/8c8b65e9-7945-4595-99a3-5c4c4c81e6bb)

**Comment by CraigClark** [comment]
@NicoledeGreef you can edit the title in section 1 of the build page

**Comment by NicoledeGreef** [comment]
@CraigClark thank you! i figured there had to be a way.

When I scanned the build sections it's not listed but indeed when I choose to edit Section 1 there it is! I realize it's kind of redundant to list it twice given that it's at the top but perhaps business users will also encounter this. We can make it part of the UX testing script.

In any case, it's an item for training so I've tagged it as such.

**Build Section 1:**
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/57c7337e-9deb-4538-8ad8-1e8d5c3c6e51)


**Edit Section 1:**
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/863a3e79-1e83-4e6f-bcba-45e833aa41f8)
