### ISSUE TITLE
Set up default content deploy

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#329]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5866318782

---

This started as an investigation on how to move content from a MySQL DB to Postgres. [Default Content Deploy](https://www.drupal.org/project/default_content_deploy) will allow us to move content between environments. This is useful because it means we can have matching content on prod, test, and dev. Also, some features depend on content values. Since content is not tracked in git the way config is, it can be problematic to rely on for functionality. This can get around it because the content export uses UUIDs.

- [x] tested moving content from dv21 to dv14 (OpenPlus MySQL and Postgres dev environments)
- [x] test moving taxonomies, book pages (the help guide) and metadata records from prod to test and dev.

**Comment by lkmorlan** [comment]
Issue to fix exception thrown when config is not in place:
https://www.drupal.org/project/default_content_deploy/issues/3415392

Issue to fix poor documentation:
https://www.drupal.org/project/default_content_deploy/issues/3415378

**Comment by CraigClark** [comment]
This has been tested and works to our satisfaction. I will create new issues if any arise
