### ISSUE TITLE
change 'view profile' to 'Dashboard' in the taskbar

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#331]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5874099980

---

<img width="882" alt="screen cap indicating where the dashboard link should be" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/bbdd1d4d-93e9-4f54-9de9-1c128664dd49">

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified in dev
