### ISSUE TITLE
Changes to Information Schedule details page

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#332]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5877731188

---
The Information Schedule details page will need some adjustments to reflect recent conversations regarding the Information Schedule taxonomy.  Currently the details page looks like this:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/599d1271-dcc1-4cf9-b40e-1baa6cd9b88e)

To improve clarity, understanding, and align with upcoming IM education outreach I'm proposing to update the details to show:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/2c2be919-38ba-4f46-a12b-34d4ad01f647)

@CraigClark this relates to your recent comments in #321.  This may be easier then implementing code to show term lineage?

**Comment by mjmcclung** [comment]
Updated original image to show the full term name also displayed in brackets (as discussed this morning).

**Comment by NicoledeGreef** [comment]
closing this as #343 handles it
