### ISSUE TITLE
Prepare for using Postgres instead of MySql for DB

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#333]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5879253987

---

## notes

1. Empty all the content out of dv14
2. Freeze content work (coordinate this with Will's availability), maybe put site in maintenance mode for this
3. export content from prod
4. import to dv14
5. Will sets up postgres on dev/test/prod using the DB from dv14
6. get rid of dv21
7. back to where we were with dev tasks

Postgres needs more storage, it is HA by default. Will will look into this and get more details.

### References

https://imagedelivery.net/lPM0ntuwQfh8VQgJRu0mFg/f7ac6b3b-a1e2-4169-b774-4d87ce652000/public

## Prepare dv14 postgres DB for move to prod

- [ ] freeze content on prod
- [ ] get content from prod and put in on dv14
- [ ] rebuild help guide book pages
- [ ] where there are links in field help text, relink to the help guild
- [ ]  make sure menus match what is on prod

## After postgres prod build

- [ ] visual inspection of content
- [ ] add files back to media entities  
  - go to the media overview page
  - open the media entity you want to work with
  - remove the existing image 
  - add the replacement image (Get them here [bc_images.zip](https://github.com/bcgov/MFIN-Data-Catalogue/files/14055584/bc_images.zip))

**Comment by NicoledeGreef** [comment]
exploratory work completed in Sprint 12
