### ISSUE TITLE
Permissions issues on the dashboard

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#335]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5887916145

---

The dashboard is not appearing as expected for IDIR users who do not have any other role.

## To duplicate

1. login as a user who only has _Data catalogue user_ role.
2. go to the dashboard
3. refer to screenshot for issues

![dashboard-issues](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/b102af2b-abaa-4439-89f0-f52b842f7e65)

Fixes
- [x] 1. only the DC admin, DC Manager and DC editor role should have access to the manage tab
- [x] 2. (Craig) remove left padding on right block if there is no left block
- [x] 3. only the DC admin, DC Manager and DC editor role should see the metadata record summary block
- [x] 4. (Craig) only people with edit MR permissions should be able to see records that need review block
- [x] 5. (Craig) all authenticated users can access bookmarks
- [x] 6. (Craig) all authenticated users can access saved searches

**Comment by lkmorlan** [comment]
@CraigClark I have done part of this. The rest of the items are marked with your name.

**Comment by CraigClark** [comment]
- [x] @lkmorlan please [review merge this branch](https://github.com/bcgov/bcbb/tree/335-dc-fix-make-brick-layout-robust), fixes top region right not aligning correctly when there is no top region left

**Comment by CraigClark** [comment]
@lkmorlan 4, 5 and 6 are fixed with https://github.com/bcgov/MFIN-Data-Catalogue/tree/335-dashboard-appearance-access, please review/merge

**Comment by CraigClark** [comment]
@lkmorlan #3 isn't quite fixed, as IDIR user, I still see this. Joel mentioned we need an access check on [this block](https://github.com/bcgov/MFIN-Data-Catalogue/blob/1.0.x/html/modules/custom/bc_dc/src/Plugin/Block/BcDcContentSummary.php) 

I think an access check for _Create metadata record_ would work, since all editors, managers and admins can do that. Save us having to update the block if a role changes

**Comment by lkmorlan** [comment]
@CraigClark The fixes were on a branch so that is why it did not appear fixed to you.

**Comment by CraigClark** [comment]
This all looks good on dv14. moving to review

**Comment by NicoledeGreef** [comment]
verified in dv14
