### ISSUE TITLE
Theme book pages

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#336]
**OP timer**

---

The book pages used for documentation need some general theme clean-up. 

- [x] get rid of bold in subway nav
- [x] fix appearance of tables example https://cat.data.fin.gov.bc.ca/documentation/permissions
- [x] fix appearance of TOC example https://cat.data.fin.gov.bc.ca/documentation/information-schedule
- [x] general clean-up

**Comment by CraigClark** [comment]
these changes should be deployed next time there is a `composer update` and a build

**Comment by NicoledeGreef** [comment]
reviewed in dev after postgres migration.
