### ISSUE TITLE
Move to Postgres

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#340]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5931916917

---

## Prepare dv14 Postgres DB for move to prod

- [x] freeze content on Prod
- [x] ND: notify users of Prod freeze (not a big deal as no one is using it); deploys to Dev and Test are expected in the next week and we will communicate prior to that happening so that users are informed in case they are using or planning to use those environments--> migration will blow away Test metadata content
- [x] get content from Prod and put in on dv14
- [x] rebuild help guide book pages
- [x] update user roles is needed
- [x] where there are links in field help text, relink to the help guild
- [x]  make sure menus match what is on prod

## After Postgres prod build

- [x] visual inspection of content

**Comment by CraigClark** [comment]
closing, will merge with #333

**Comment by CraigClark** [comment]
@NicoledeGreef All the content is on dv14 now. I'll clean it up today and tomorrow, then you can review. Once that's done, we will schedule builds to the other environments.

**Comment by NicoledeGreef** [comment]
Login with IDIR first attempt: Page not found
Login with IDIR second attempt: worked as expected

I created 3 new metadata record stubs but they didn't show up under the "Draft metadata records" section on my Dashboard.  I can see them if I move to the "Manage" tab:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/d5491f4b-cf7d-4da1-9e0a-5a842bc5f850)

**Comment by NicoledeGreef** [comment]
In Edit more there are hyperlinks "Read more...", "Refer to documentation...", etc. and these are resulting in "Page not found"

**Comment by NicoledeGreef** [comment]
If a MR is still Draft, should there be an Unpublish button?
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/17a8995d-4f46-4f04-83d8-db24a01053e4)

**Comment by CraigClark** [comment]
The fix for the help text will be config, please submit a bug report for that @NicoledeGreef

**Comment by CraigClark** [comment]
> I created 3 new metadata record stubs but they didn't show up under the "Draft metadata records" section on my Dashboard. I can see them if I move to the "Manage" tab:

@NicoledeGreef , @lkmorlan will look into this. I'm having the same issue as DC admin with Multiple orgs. As an editor in IMB, (one org) it works as expected

**Comment by lkmorlan** [comment]
> I created 3 new metadata record stubs but they didn't show up under the "Draft metadata records" section on my Dashboard. I can see them if I move to the "Manage" tab:

@NicoledeGreef please try it now.

**Comment by lkmorlan** [comment]
Feature contributed to `tac_lite`:
https://www.drupal.org/project/tac_lite/issues/3420249

**Comment by NicoledeGreef** [comment]
> > I created 3 new metadata record stubs but they didn't show up under the "Draft metadata records" section on my Dashboard. I can see them if I move to the "Manage" tab:
> 
> @NicoledeGreef please try it now.

Original Draft records are now showing up as are new Draft records.

**Comment by NicoledeGreef** [comment]
> The fix for the help text will be config, please submit a bug report for that @NicoledeGreef

https://github.com/bcgov/MFIN-Data-Catalogue/issues/358

**Comment by NicoledeGreef** [comment]
In Build page, I don't see Sections 4 & 5 any more.  I saw them earlier.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/9ef901c6-d20b-44f5-8616-e253bec5658f)

**Comment by CraigClark** [comment]
I am going to close this. Everything has been moved to postgres. There are still time out issues, see #154.
