### ISSUE TITLE
Theme global reports dashboard

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#341]
https://openplus.monday.com/boards/4092908516/pulses/5933453609

related issue #213 

make it presentable

Mockup:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f16b0991-90e3-438d-af58-068baadc8d64)

**Comment by CraigClark** [comment]
@lkmorlan Ready for review / merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/341-theme-global-reports

**Comment by lkmorlan** [comment]
Merged

**Comment by CraigClark** [comment]
done and deployed. If there are changes we will make new tickets.
