### ISSUE TITLE
Duplicate terms found

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#342]
**OP timer**

---
When reviewing the terms and associated Term ID's a duplicate term was found:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/9929b6c0-d0a8-4b57-8608-698d1377a300)

This looks to be because there is a NA term in both the Record Disposition and Record Life Cycle Duration taxonomies.  The NA term should not be included in the Record Disposition taxonomy as such a disposition does not exist.  Please remove.

**Comment by NicoledeGreef** [comment]
NA has now been removed from record_disposition in dev, test, and prod.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/250aa47e-3158-413b-8526-3c444e909800)
