### ISSUE TITLE
Build page updates

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#344]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5974417202

---
## Describe the idea

_Logging here for future consideration. These are my thoughts; we'll see what comes out of the UX sessions._

Taking a critical look at the Build page for a metadata record, some of the labels should be altered.  There is some use of the phrase "data set" that should be changed as it is an artifact of an earlier point in the dev team's understanding. "Data" in some cases is appropriate, however.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/ac81badc-919a-40b9-be87-03d537747925)

Under **Section 1: Details**

- [x] **Data set type** --> **Item type** or **Record type**

- [x] Under **Section 2: Data description** --> **Section 2: Description**

- [x] [**Data set description** --> do we need this header? seems redundant
- [x] **Data set historical change** --> **Historical change**

- [x] Under **Section 3: Data usage** --> **Section 3: Utility**

- [x] Under **Section 4: Data value** --> **Section 3: Significance**

- "Information schedule" and "Security classification"  could be moved to Section 3 from Section 4
OR 
"Security classification"  could be moved to Section 3 from Section 4 AND Section 4 could be re-ordered to include  "Information schedule" last in the list

**Comment by CraigClark** [comment]
@NicoledeGreef I think we should keep the description label in section 2. 

I know its redundant, but the purpose of this section isn't so much to provide content, it's to let editors know what fields have values and which don't. If there is no value here, you get a notice that description is required.



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/757ab0e6-146b-4b47-ae03-22e6fc93b936)

**Comment by CraigClark** [comment]
@NicoledeGreef would it make sense to call the description field 'summary'?

**Comment by NicoledeGreef** [comment]
**Data set description** --> **Summary** works for me.

**Comment by CraigClark** [comment]
@lkmorlan please review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/344-build-page-updates

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified in dv14
