### ISSUE TITLE
Update global dashboard to specify security classification

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#347]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5981688078

---
Please update the global dashboard to change the 'Records by classification' title to 'Records by security classification' to reduce confusion and increase clarity.
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/aa18e3f2-09d4-46e9-a51f-ff05c20a7cb0)

There is ongoing confusion with staff when 'classification' is mentioned as there are multiple ways to classify information (security and IM classifications being two, amongst others).  Being specific in our heading will reduce confusion and create clarity when having conversations with business areas.

**Comment by NicoledeGreef** [comment]
We'll change the title to "Security classification" due to lack of screen real estate.

**Comment by CraigClark** [comment]
@lkmorlan for merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/347-rename-security-classification-chart

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified in dv14
