### ISSUE TITLE
Data lineage and viewability restriction

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#348]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a party responsible for one or more data assets 
I want to be aware of dependencies on the assets I manage regardless of viewability restriction
so that I can inform dependent parties as part of change management.

## Describe the idea

Currently, the graphical representation of data lineage in a metadata record respects viewability restriction applied to metadata records. 
That is to say that:
When metadata record A has visibility set to a specific Organization (a branch within Ministry of Finance) 
AND metadata record B has visibility set to Public
AND metadata record B is built using metadata record A, only members of the specific Organization will see the relationship when they look at **Data lineage** under metadata record B

**Example of user with less group membership - compare with screenshot below**
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/b617679e-32fe-44e9-9a56-92fbff4d3ea9)

**Example of user with more group membership - compare with screenshot above**
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/7da0ac11-733c-4fe3-9dac-a934580c75f7)

## Actions

**Facts:** 
- An administrator or a user with multiple group membership will have non-restricted view of data lineage.
- Best practice is that metadata records should be visible to Public or IDIR if public is not appropriate (in other words, _default to open_). Only in very rare occurrences, will viewability be restricted to an Organization (e.g. FREDA, etc.)
- There are notifications to subscribers (based on items Bookmarked) that occur when changes of significance are logged in a metadata record.

**Discussion:**
In the case where a user does not have viewing permissions because of a gap between their group membership and the viewability restriction on the metadata record:

- is it feasible to characterize that there is a dependency but that it is restricted from view? 
      - if so, what could that look like?

- if an analytical model is built using a data asset and that data asset has a potentially impactful change, how critical is it that the owner of the analytical model is notified in advance of the change? **Note**: if the owner of the analytical model Bookmarks a data asset because they use it, they will get notified of changes that impact their model as the change should be documented in metadata itself (requirement #26). When they are notified they can self-serve access the revisions of the metadata record to determine the differences and assess their touchpoints with the change.

- is it warranted to invest in characterizing that there is a dependency but that it is restricted from view, given the low probability of this happening?

- [ ] Hurrah! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
Currently, when a non-authenticated user searches MRs they can only see MRs that have their visibility set to Public and this carries through to **Data lineage**.

A Report might be Public but it might be based off data with a higher degree of restriction.  In this case we currently see:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f180e3bb-8c3c-411e-b9de-868f32dbf3bb)

Non-authenticated users are not our target user-base; we should consider suppressing **Data lineage** for non-authenticated users.

Same issue as #354

**Comment by CraigClark** [comment]
@NicoledeGreef This has been sitting around for a while. Can we have a mini sprint review sometime in the next few days and make sure this is on the list of things to look at? Off the top of my head, I'm not sure how this could work. an asset listed as 'A protected asset relies on this asset' or something similar may not provide any useful info. Maybe something like `A protect dataset owned by - name with email link' would be useful. That would definitely be custom code, I'm not sure how much.

I may have misunderstood, I thought anything protected would be rare and temporary. If that's the case, not sure about the ROI for this feature

**Comment by NicoledeGreef** [comment]
We are going to monitor the restriction of data as it is populated in the Finance Data Catalogue (the Metadata metrics screen has a wonderful, at a glance visual representation of this) and assess whether this case requires more investment given that restriction to Organization is considered to be rare and mostly temporary. We'll also keep tabs on the user experience end of things through ongoing UX review.
