### ISSUE TITLE
People with Editor role cannot access the Build page

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#349]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5989812587

---

## To reproduce
The Build tab is not showing up and you cannot get to the Build page via URL as an Editor

## Expected behaviour
Build resolves

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/ebe9e4e3-72fe-409f-8c2f-776ee719be7a)

**Comment by lkmorlan** [comment]
@NicoledeGreef I have noticed in consistencies in `tac_lite` config between test/dev/prod. I have fixed those. Please check if there is now the correct access. If not, please provide the URL of an example page that is not working. As a general rule, always provide a full URL of any problem so I know what server to look at.

**Comment by CraigClark** [comment]
@NicoledeGreef The correct settings for `tac_lite` are documented here https://cat.data.fin.gov.bc.ca/documentation/permissions

**Comment by NicoledeGreef** [comment]
User confirmed issue is fixed.
