### ISSUE TITLE
change description of current item in Data Lineage

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#350]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5989919265

---
Graphic representation of Data lineage has a label for the current MR in the lineage that indicates "(This dataset)". Ideally should be changed to "(This Form)", "(This Data)", or "(This Report)" depending on the highest-level value of the field_data_set_type vocabulary.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/ec5aa5dc-bf5a-4258-8c26-a0de6053e8a2)

**Comment by CraigClark** [comment]
@lkmorlan review/merge please https://github.com/bcgov/MFIN-Data-Catalogue/tree/350-data-lineage-description

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified in dv14
