### ISSUE TITLE
Modify label on the "Most viewed" tab

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#351]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5991642498

---
Currently labeled "Most viewed"

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/72d91a5d-aee6-455a-82a2-97f0a41565b3)

please change it to "Metadata metrics"

**Comment by CraigClark** [comment]
@lkmorlan please merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/351-modify-label-on-the-most-viewed-tab

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified in dv14
