### ISSUE TITLE
field for data asset location/name

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#352]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

https://openplus.monday.com/boards/4092908516/pulses/6002168402

---

## User story

As a potential consumer of data, 
I want to discover specifics about the data asset 
so that I can locate and use the asset.

## Describe the idea

Currently, the content model has elements where the nature of the data asset can be described but a remaining question is: is there value in separating out a placeholder element to store, for example: location and filename OR schema_name.object_name?

We already have a hierarchical taxonomy for `record_type` in place with Data, Form, and Report at the top level. 

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/359bbace-ae37-4b06-bbf4-29af80570e72)
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/fb3bacb1-6dcf-4b3b-9fb6-9a930af70e39)

**Data**, for example, allows users to specific whether the assets lives in a file or in a database, and the subtypes of those things. What we don't currently have is a specific placeholder for the filename and location OR the schema/object name.  These things can be included in the description (body) of the metadata record but then to be used for any other purpose they would have to be parsed out which is not small feat without some sort of standardized input (body is free form text).

If we stored the name/location of the data asset in one or more fields then it's easy to grab the value when/if needed.

These are field(s) we would want to display for logged in users. They would be irrelevant to public users.

**Comment by NicoledeGreef** [comment]
To do: figure out the list of likely locations (fileshares, DB name, sharepoint?)

**Comment by mjmcclung** [comment]
Since this Catalogue is public facing there may be security considerations.

**Comment by CraigClark** [comment]
> Since this Catalogue is public facing there may be security considerations.

Good point. We can control access to the field. Similar to what we do for visibility

**Comment by mjmcclung** [comment]
I'm not sure we can get as specific as schema_name.object_name in all instances as the catalogue is cataloguing collections of things.  These collections may be represented as more than one table in the database (e.g. a collection of tables).   A group discussion is needed on this subject before getting too far into planning/implementing.

**Comment by NicoledeGreef** [comment]
@CraigClark 
Non-mandatory text area as a placeholder

Section 2 below Summary on the Build page
On the Record view, below the Summary

**Comment by CraigClark** [comment]
@lkmorlan ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/352-asset-location

@NicoledeGreef , I added this field to the docs ~~https://dv14.openplus.ca/documentation/metadata-fields#location-01~~
https://cat.data.fin.gov.bc.ca/documentation/metadata-fields#location-01

**Comment by CraigClark** [comment]
@NicoledeGreef for now this is just a test area, you can type a location, add a link, that type of thing. This field is not available to the puiblic

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified placement, use, and visibility in dv14
