### ISSUE TITLE
Confusing information presented to users in data lineage when there are access issues

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#354]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6020503848

---

## Describe the bug

The data lineage widget on a node view shows the MRs that are consumed by the MR the viewer is looking at. It is displayed by  list of MRs in a box with an arrow pointing down to the MT the user is viewing. The issue is that if `field_data_sets_used` has values, but the values are not accessible to the viewer, they see the arrow and the current node under _Data lineage_

## To reproduce
Steps to reproduce the behaviour:
1. As an editor, create an MR _test 1_, leave it unpublished
2. Using the same account to create a second MR, _test 2_
3. in _test 2_, in `field_data_sets_used`, select _test 1_
4. publish _test 2_
5. See that when you view _test 2_, you see _test 1_ in the lineage map
6. Logout
7. as anonymous, go to _test 2_
8. see that here is an arrow, with nothing above it pointing to the current MR box.

## Expected behaviour

To see the MRs used

1. it has to be published, I need to have access via visibility
2. If it is unpublished, and I am in the same org as the unpublished MR, I see it, but [unpublished] is appended to the node title.

If neither of those conditions are met, I don't see the lineage.

## Screenshots

As admin, dc editor in property taxation branch,  DC user in  property taxation branch and IDIR user with no org I see this. 

<img width="1131" alt="image" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/746404a9-ac17-4909-a1d0-4c2aa9aafe56">

>[!WARNING]
> -  IDIR users should not be able to see unpublished MRs, regardless of org

As anonymous, I see this

<img width="804" alt="image" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/bbecd1b7-1f32-4546-ac72-8300abb38020">

## TBD

- test if this also affects _used in datasets_, it might be different since that's a view

**Comment by NicoledeGreef** [comment]
https://github.com/bcgov/MFIN-Data-Catalogue/issues/348#issuecomment-1936653187

**Comment by CraigClark** [comment]
Tested and passed on dv14
