### ISSUE TITLE
Display data catalogue version on the status page

### ISSUE THREAD

**Issue by lkmorlan** [bcgov/MFIN-Data-Catalogue#355]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6020732089

---

## User story

As anyone who can see the status report 

I want to see the data catalogue version number

So that I know what version I am on.

## Proposed solution

Write a custom `hook_requirements()` implementation

## Estimated level of effort

- Less than 1 day

## Definition of done (DoD)
- [x] Version number appears as an item in the status report

### Automated functional tests

- [x] I have written functional tests for this feature
- [x] I have run the functional tests and they pass

**Comment by lkmorlan** [comment]
It turns out the `composer_deploy` is not suitable for this because the `bc_dc` module does not come in via Composer. We can get the information needed using Git.

**Comment by lkmorlan** [comment]
The current approach does not work in our environment. I have discussed another solution with @sylus .

**Comment by lkmorlan** [comment]
The code now gets the version from the info file of `bc_dc`. @sylus will adjust the deployment script so that it adds a `version` key to this file.

**Comment by sylus** [comment]
@CraigClark I can get this done Monday night it just takes some finagling with yq.

**Comment by sylus** [comment]
I believe I have addressed this now by writing to the bc_dc.info.yml file during the dev build.
