### ISSUE TITLE
Links to Documentation broken 

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#358]
**OP timer**

---

## Describe the bug
During dv14 validation (postgres DB backend), there are links resulting in resulting in "Page not found".

In Edit mode for a MR there are hyperlinks "Read more...", "Refer to documentation...", etc. and these are broken.

**Comment by CraigClark** [comment]
this was done in branch 340-update-field-help-text and has been merged

**Comment by CraigClark** [comment]
Assigning to @NicoledeGreef to review

**Comment by NicoledeGreef** [comment]
Verified links are no longer broken in dv14. 

Filing another ticket re: link adjustments and whether there should be more links in **Edit** mode.
