### ISSUE TITLE
Filter the auto-complete values for "Data sets used" 

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#360]
**OP timer**

---
Currently when users are editing metadata, under Section 3: Utility --> "Data sets used" they can select the same dataset they are editing.  Can we filter this out of auto-complete? Otherwise we get data lineage relationship like this:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/7df9bb0b-5849-4b50-bc0b-b23d73584d16)

**Comment by CraigClark** [comment]
Closing. This is a duplocate of #205
