### ISSUE TITLE
GC Notify requirement re: API calls

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#363]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/question

---

## What's your Question?

Email from GC Notify received is below. Do we need to adjust Finance Data Catalogue calls to be in compliance?

_To enhance security, starting March 6, 2024, we’ll require the entire API key for every API call. If you send only 36 characters or a partial key, you’ll get a 403 error message and your job will fail.

A full key starts with “gcntfy”. If you no longer know your full key, you must create a new one.

Include the entire API key in the HTTP header when calling the API. For more information, read our API documentation.

We recommend forwarding this email to all developers on your team. If you have other questions or concerns, contact us.

The GC Notify team_

**Comment by CraigClark** [comment]
I'll ask @sylus about this

**Comment by CraigClark** [comment]
@NicoledeGreef 

confirmation from Will that the keys are good

```
export GCNOTIFY_TEAM_APIKEY=gcntfy-XXXX_team-XXXX
export GCNOTIFY_TEST_APIKEY=gcntfy-XXXX_test-XXXX
export GCNOTIFY_TEST_TEMPLATE=XXXX

```

We don't have a production key yet
