### ISSUE TITLE
Clean up development styles

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#366]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6074145451

---

There is a css file in the dc_theme for development styles. This should be cleaned up

- [x] add relevant styles to the `scss` files
- [x] remove irrelevant styles

**Comment by CraigClark** [comment]
@lkmorlan ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/366-clean-up-styles

**Comment by lkmorlan** [comment]
Merged
