### ISSUE TITLE
"Generate CSV" is not generating CSV

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#367]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6075778605

---

## Describe the bug
After a search is performed, a user can select one or more MRs for export as CSV. A file is generated but the contents of the file is not comma separated values, rather it seems the delimiter is a semi-colon. See attached file.
[site_search_2024_02_15_15_36-7a348467.csv](https://github.com/bcgov/MFIN-Data-Catalogue/files/14303487/site_search_2024_02_15_15_36-7a348467.csv)

## To reproduce
Steps to reproduce the behaviour:
1. Visit test.cat.data or dv14
2. Perform a search with no parameters which returns the entire list of MRs
3. Select All records
4. Scroll down and click "Generate csv...":
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/41927c29-4d50-40af-85cb-254228150cc4)
5. File link is generated; download the file and view in text editor or MS Excel (does not render well in Excel without telling Excel to import data from a file - all text ends up in Column A):
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/0d195195-fdc4-47f3-86e2-f8d55c1dc595)

## Expected behaviour
Downloaded file should be comma delimited not semi-colon delimited. When users download and doubleclick it or select Open in Excel the column headers and values should be in distinct columns).

## Screenshots
Downloaded file in a text Editor:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/235b12e5-8be0-4326-84cc-0f9b30aabb7a)

Having to import the data in Excel to get it to render properly is not end user friendly (not everyone knows how to do this):
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/09478eeb-b7f2-420c-a3ef-25bb0fe06deb)

**Comment by lkmorlan** [comment]
Simple config change. Config is done in the View.

**Comment by CraigClark** [comment]
tested on dv14 and passes
