### ISSUE TITLE
Gather sample data for testing

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#37]
## This feature support the following requirements

Enable realistic testing of addition/edit/presentation of content in the UI, etc.

## Additional context

Work with business reps to create a sample data file representing the breadth of the kinds of thing we might encounter in the real world.  Build it with relatively correct lengths for field, etc. not junk test data.

## Proposed solution

Gather and submit the test data to the dev team.

## Definition of done (DoD)
- [ ] file attached to ticket

**Comment by CraigClark** [comment]
Closing this as we now have sample data. What we do with it will be another ticket

**Comment by CraigClark** [comment]
Re-opening to accommodate @sangtrinh 's request for examples of products that use data-sets

**Comment by NicoledeGreef** [comment]
Files are in MS Teams/Sharepoint under 'architecture'
