### ISSUE TITLE
CSV export button differences

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#370]
**OP timer**

---

It would be ideal to ensure that all "CSV" or "Generate CSV" options within the Data Catalogue match (UI wise and what they generate)

Example on Search screen: 
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f7093e4e-36c5-48c5-a9ca-83695567590b)

Example on Manage Reports screen: 
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/7ddabd0c-6710-4348-8224-9d1a14a6e9ea)

**Comment by CraigClark** [comment]
@lkmorlan please merge this this into the base-build theme https://github.com/bcgov/bcbb-theme/tree/add-wrapper-for-input

and merge this into the data catalogue https://github.com/bcgov/MFIN-Data-Catalogue/tree/370-theme-csv-download-links

**Comment by lkmorlan** [comment]
Merged
