### ISSUE TITLE
enable an API user role

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#372]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6119939878

---
User role

- [x] role has permissions to create/edit metadata for any Org (it bypasses taclite)
- [x] user has same permissions as DC Editor + viewReports

**Comment by CraigClark** [comment]
- [x] This needs work, as a DC admin, I  cannot add _ Data catalogue API user_ role to a user. It needs to be added to role delegation.
- [x] Add _view site reports_ to DC admin role, DC admin should be able to do anything other DC roles can do

@lkmorlan

**Comment by lkmorlan** [comment]
[Documentation](/bcgov/MFIN-Data-Catalogue/wiki/Using-JSON:API)

**Comment by NicoledeGreef** [comment]
Verified in dv14 that Catalogue admin can assign API user role to a Drupal user account.
