### ISSUE TITLE
bulk taxonomy term delete

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#373]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6127706806

---

In tests, I had to take a few runs at importing the info-schedule. This generated a lot ot terms I had to delete. This was easy for me working locally, I could `ddev snapshot restore` to get back to my original state. Nicole can't do this working on Openshift.

## proposed solution 

install the [taxonomy delete](https://www.drupal.org/project/taxonomy_delete) module. We can remove it after the information schedule vocabulary is stable.

**Comment by CraigClark** [comment]
@lkmorlan please review merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/373-bulk-taxonomy-delete

**Comment by lkmorlan** [comment]
Merged
