### ISSUE TITLE
Assets used field is sometimes not available

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#376]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6195978334

---

Reported by @NicoledeGreef via email

I am logged into dv14 as my IDIR which is a Catalogue admin. I created 3 new metadata records today which are now in various states:
 
Report: https://dv14.openplus.ca/node/62
Data: https://dv14.openplus.ca/node/63
Form: https://dv14.openplus.ca/node/64

When I access https://dv14.openplus.ca/node/63/build/
And Edit Section 3: the data assets used flashes quickly and disappears.  I noticed this before and I’m not quite sure why this is happening.

## Further investigation

Tested wit my IDIR account | roles: DC admin, editor and user | org: Information Management Branch

1. I tested this and there is an issue with those nodes. 
2. If you disable JavaScript, the field appears as it should
3. I created a test node, it works as expected see https://dv14.openplus.ca/node/66
4. I tested on prod as admin (user 1) and had the same issue on [this record](https://cat.data.fin.gov.bc.ca/node/35/edit?display=section_3&destination=/node/35/build)
5. The problem is intermittent, I tested /node/62 a few minutes ago and it didn't work, now it does. node/63 still has the problem
6. I tried clearing caches, no effect
7. Some older records do not show the field, even if they have values, see https://dv14.openplus.ca/node/28/edit?display=section_3&destination=/node/28/build

**Comment by CraigClark** [comment]
## Update

I am seeing this issue on prod https://cat.data.fin.gov.bc.ca/node/35/edit?display=section_3&destination=/node/35/build

**Comment by lkmorlan** [comment]
This should be working correctly now. The patch to `conditional_fields` had worked on just one type of field. I re-wrote it to put the code in a different place so that it works on all types.

**Comment by CraigClark** [comment]
@lkmorlan reviewed on dv14, this looks good. Ready to merge

**Comment by NicoledeGreef** [comment]
same ^
