### ISSUE TITLE
new vulnerability assessment

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#378]
**OP timer**

---
Security Team has posted a Critical vulnerability regarding Drupal: https://www2.gov.bc.ca/assets/download/7C8A249665B14D1BBBFCDFD904E041B2

Please assess in the context of the MFIN Data Catalogue and bcbb. We can discuss mitigation as applicable.

**Comment by lkmorlan** [comment]
This part is critical:

> The module has a logic error when handling sites that upgraded code and **did not run the Drupal update process** (e.g. update.php).

We have always run the updates, so this is not a problem.
