### ISSUE TITLE
test env search results not as expected after postgres and code deploy

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#380]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6216032054

---
Pre-requisite: @sylus  to deploy the postgres DBs from dv14 to all Openshift envs

**Comment by lkmorlan** [comment]
@NicoledeGreef a build was done earlier today.

**Comment by NicoledeGreef** [comment]
Thanks @lkmorlan  - did this go to dev, test, and prod? I'm not seeing #379 in dev

dv14: https://dv14.openplus.ca/node/46/build
dev:    https://dev.cat.data.fin.gov.bc.ca/node/46/build


Something is off in dev:


![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/4a9f947f-d724-4f54-89fb-6bb3a5107d19)

**Comment by NicoledeGreef** [comment]
test and prod environments also have this ^^ issue .

**Comment by lkmorlan** [comment]
@NicoledeGreef This should be fixed now. The deploy did not happen correctly because of running out of quota.

**Comment by NicoledeGreef** [comment]
reviewed in dev, test, and prod - code deployment looks to be in order as i can now find latest features in those envs.

**test env search results is still 28 (expected 22)**

**Comment by NicoledeGreef** [comment]
Oddly, if you select all 28 results as per the UI and export, the file includes only 22 and they are confirmed to be all the published metadata records.

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/9ed529ba-83d2-4754-92f4-78ce7e58fdfd)

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/3556dcf4-fcc8-450a-9b90-43ea1978ad37)

**Comment by lkmorlan** [comment]
@NicoledeGreef Will has re-created the core. That seems to have fixed it.

**Comment by NicoledeGreef** [comment]
verified search results returning as expected in test.
