### ISSUE TITLE
dev: Report MR has a section 6: Data dictionary

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#381]
**OP timer**

---
https://dev.cat.data.fin.gov.bc.ca/node/62/build

I went looking for Section 4: Related Documents and found section 6: Data Dictionary

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/9cad7d3b-8ec8-4edf-afa3-342b2c967994)

In light of other issues noted (see #380), maybe there was an issue with the build/deploy to dev?

Form MRs also have this issue: https://dev.cat.data.fin.gov.bc.ca/node/64/build

**Comment by lkmorlan** [comment]
@NicoledeGreef This should be fixed now. The deploy did not happen correctly because of running out of quota.

**Comment by NicoledeGreef** [comment]
verified in dev, test. not enough content to verify in prod but i'll assume it's in line with dev and test.
