### ISSUE TITLE
investigate chart libraries to replace Google

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#382]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6269315189

---
Currently we're using Google Charts as a prototype charting capability. That is not ideal.

- [x] Install and configure new module @lkmorlan 
- [x] Create "Records by restriction" graph as a View @CraigClark 
- [x] Create "Records by security classification" as a View @CraigClark

**Comment by CraigClark** [comment]
@lkmorlan: I was talking to Robin, mentioned D3JS as a good candidate

**Comment by lkmorlan** [comment]
Issue opened during this:
https://www.drupal.org/project/charts/issues/3437496

**Comment by CraigClark** [comment]
@NicoledeGreef some FYI

This is going to take a few deployments to implement. The build we fail if we try to do everything all at once. First we will deploy to enable the module, then we can do another to bring in the config.

**Comment by lkmorlan** [comment]
Issue opened during this:
https://www.drupal.org/project/charts/issues/3436590

**Comment by lkmorlan** [comment]
`charts_billboard` is installed. Commit "Switch from charts_google to charts_billboard" in branch `382-replace-google-charts` switches to it. After that change, to appear correctly, the charts need config adjusted in `BcDcClassificationChart` and `BcDcRestrictionChart`.

After that is deploy, `charts_google` can be uninstalled using the other commits on that branch.

**Comment by CraigClark** [comment]
@lkmorlan is there somewhere I can look at this?

**Comment by lkmorlan** [comment]
In `dv14`, `charts_billboard` is installed, available to be used. The charts can be switched and configured.

**Comment by CraigClark** [comment]
@lkmorlan I was looking into this. We can use views to make charts, which is better than doing it with a module. Unless of course the module is doing something with the chart that views can't.

I have made a view for the _Records by restriction_ and added it to the reports page. This is working except in the view there are settings to set colours for the values in an entity reference, look in the settings for chart in the view. There is a problem however, the colours I selected are not applying. Billboard is using classes in the svg, so we can override with css. It would be better though to set these in the UI as designed.

Could you please look into why we can't get coloured slices in the pie chart for the entity values?

This branch has the view and adds the block to the reports page. https://github.com/bcgov/MFIN-Data-Catalogue/tree/382-records-by-restriction

**Comment by CraigClark** [comment]
Marking as stuck until the colour issue is resolved.

**Comment by CraigClark** [comment]
@lkmorlan assigning to you to sort out the [colour problem](https://github.com/bcgov/MFIN-Data-Catalogue/issues/382#issuecomment-2037514944)

**Comment by lkmorlan** [comment]
Getting colors to work in pie charts required this change:

https://www.drupal.org/project/charts/issues/3442641

**Comment by lkmorlan** [comment]
Colors are working.  Records by restriction graph View is merged. Passing to @CraigClark to complete the other graph.

**Comment by CraigClark** [comment]
@lkmorlan I have adjusted the colours and added a view for the security classification chart on the reports page.

These changes are ready to review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/382-adjustments-to-metrics-charts

If we are using views for charts, we might want to get rid of the custom module we had that was doing it. Not sure.

**Comment by lkmorlan** [comment]
Merged. I removed the unused chart blocks.

**Comment by CraigClark** [comment]
Closing. New libraries working as expected
