### ISSUE TITLE
Rename Section 3 on Build Page

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#383]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

https://openplus.monday.com/boards/4092908516/pulses/6270835743

---

## User story

As a metadata editor
I want to easily find the section that has the metadata I want to edit
so that I can efficiently spend my time updating metadata records

## Describe the idea
Rename Section 3 from Utility to something that is more intuitive and encompasses the content in this section.
Suggestion: 'Lineage, quality and classification'

**Comment by NicoledeGreef** [comment]
We will change the Section 3 header to "Origin and classification". We try to avoid repeating the names of the fields within a section in the header.

**Comment by CraigClark** [comment]
@lkmorlan ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/383-rename-build-page-section-3

**Comment by lkmorlan** [comment]
Merged
