### ISSUE TITLE
Data quality section improvements

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#384]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a metadata editor
I want to fill out my metadata once
so that I can use my time efficiently.

As a user
I want to metadata records to be clear and concise
so that I can easily find and locate the information I am looking for on the page.

## Describe the idea
When filling out the Data Quality text box for the first time it didn't save.
When filled out the second time, it did save but the header title is not differentiated from the data quality text on the View page:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/950ca937-3558-42f6-99b5-dd95c3a95e04)

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by CraigClark** [comment]
@mjmcclung 

Could you please explain this in detail:

> When filling out the Data Quality text box for the first time it didn't save.

That looks like it might be a bug

**Comment by mjmcclung** [comment]
@CraigClark I just tried it again and it worked this time so not sure what happened last time. Here were the steps I took last time:

- I am logged in.
- I create a new metadata record, scroll down to list draft metadata records at the bottom of my dashboard and click on the Build button.
- I click on Edit for the Utility section (section 3).
- I put some data quality issue text in the Data quality issues box
- I set the Personal Information indicator to Yes
- I set the Security classification to Public
- I choose an Information schedule
- I hit Save

**Comment by CraigClark** [comment]
Thanks @mjmcclung 

We will keep an eye on it and issue a bug report it it happens again

**Comment by NicoledeGreef** [comment]
I did not experience the saving issue.

Is the issue that there is not a lot of differentiation in the sidebar (gray box)? 

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/6cd06cc0-6043-45e4-a5ce-935204be521b)

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/c0a604ac-46eb-4f59-a070-3d2333204883)

We will keep an eye on this one during user experience testing and re-open if there is a trend identified.
