### ISSUE TITLE
Go to metadata record after creation

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#385]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a catalogue editor
I want to go straight to the metadata record I just created
so that I can fill out the rest of the metadata details.

## Describe the idea
Currently, when a metadata record is created the user hits the 'Create' button, the screen flashes and then the user is brought back to default dashboard page with the 'Create a new metadata record' box at the top.  This is not intuitive for the user to know that there record has in fact been created and is now waiting to be further edited.  The record displays in the draft metadata record list further down the page but this may not be visible to the user from the top of the page.

Suggestion:
After the user hits the 'Create' button a second dialog box could pop up saying 'Record Created!'.  This box could have 2 options:
1) Take me to the new record
2) Return to my dashboard

## Actions

- [ ] Hooray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
The current workflow is:
- create a stub metadata record (give it a title and a type)
- it becomes a Draft metadata record
- do this as many times as you need to; each one becomes available in the **Draft metadata records** list.  
- From there choose which record you want to continue editing

Originally we can a create button that lead to editing all the attributes.  Overwhelming and not recognizing that most people will, at least initially, be creating more than one record at a time.

This is being closed; it can be re-opened when UX testing reveals a need.
