### ISSUE TITLE
Add modified_date to search facets

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#39]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4658082673

---

Add last updated date as a facet to the search page. Thus should display as a list of years , YYYY
clicking on a year exposes a list of months followed by a year , Use full word, 'January 2023, February 2023 etc. We do not need day granularity. Show a results count beside the facet.

[RSAMS search](https://recalls-rappels.canada.ca/en/search/site) is a reference for how this should work.

## Definition of done (DoD)
- [x] I see date facets on search page for last updated date
- [x] Clicking a year, I can refine to the month level
- [x] I can remove facets I've selected

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by CraigClark** [comment]
There is some style work to be done here. The months look horrible on a narrow screen


![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/35ca8b36-f3b5-4b32-9c88-76dbe7662c3c)

**Comment by CraigClark** [comment]
I took a look at this and it isn't a style fix we need. It's layout. There are two problems. 

1. I think facets should go before results in the DOM, we can discuss this @lkmorlan @NicoledeGreef 
2. the right column needs to break at a wider width. This is related to the layout settings, currently `bootstrap_layouts` which we may be getting rid of. That will be another issue

**Comment by NicoledeGreef** [comment]
This feature is already built :)
