### ISSUE TITLE
suppression of Authoritative flag on MRs

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#390]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6298348201

---
For Phase 3 we will be suppressing the `field_authoritative_info` attribute in the metadata record attribute model. There should not be ability to edit or display the Authoritative attribute but it should remain in the model for future use. 

- [x] remove field from Build page
- [x] remove the Authoritative widget from the Metadata metrics report
- [x] ~~remove authoritative info from view site_search~~ we don't need to do this
- [x] adjust tests as needed (@lkmorlan )
- [x] #396

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/fcbea020-20fb-47f7-94e3-992d7b158100)

#194 for background info on this decision.

**Comment by CraigClark** [comment]
- [documentation changes for users](https://cat.data.fin.gov.bc.ca/documentation/metadata-fields#authoritative-info)
- [documentation changes for developers](https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Disabled-fields#authoritative-info)


@lkmorlan this is ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/390-supress-authoritative-field

Could you please make whatever adjustments are needed for the tests?

**Comment by lkmorlan** [comment]
Tests adjusted.

**Comment by NicoledeGreef** [comment]
Reviewed and closing
