### ISSUE TITLE
Can we adjust labels in the Information Schedule section of a record?

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#391]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/question

---
Hi @mjmcclung

I'm looking a the IM section on a record view.

<img width="539" alt="image" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/39eff6e3-02d2-4462-94d1-41829c764edd">

- I'm not nuts about _Information schedule type_ wrapping.
- is there inconsistency in the labels?

Would it work if we had

**Information management**

Schedule type: value
Classification code: value
Business category: value

Because of the heading and common region, the information hierarchy makes it clear that these are all related to the Information schedule.

If that doesn't work, could we:

**Information management**

IM schedule type: value
IM classification code: value
IM business category: value

This is outside my area of expertise. Looking for your opinion.

**Comment by CraigClark** [comment]
To clarify, this should not be changes just because of wrapping, there is no way to absolutely control that, a lot if variables outside our control. This is about the labels.

**Comment by mjmcclung** [comment]
I like your second suggestion best:

> **Information management**
> 
> IM schedule type: value
> IM classification code: value
> IM business category: value

We've had too much confusion between security classification and records classification to simply call it 'classification'.  We need to be specific as to what type of classification this represents.

And while an Information Schedule is called just that, I think calling it an IM schedule is fine as these schedules are intended to govern how records are organized and managed.

I also think prefixing 'Business category' with 'IM' provides helpful context (and hopefully dissuades users from thinking we somehow came up with business categories on our own).

Concurrent changes should also be made to the IM details page for consistency:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/33aef339-c488-4f7f-bdb1-645203938790)

Please keep the tab stops after the labels.  I find them helpful for readability.  Could we also add these tab stops to the IM details page to increase readability there too?
