### ISSUE TITLE
Modifications to the display of the IM schedule

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#392]
**OP timer**

---

## Layout

Change the layout of the label/value. Labels should all align left and the values should all have the same left alignment. Similar to how tab stops would look in a word processor document.

Once that is done, test removing the bold font weight. This is to comply with gestalt contrast design principals. We are replacing weight for proximity to differentiate labels and values. 

Originally this was a discussion about labels

<details>
<summary>original discussion about labels</summary>
### Node view

change

> Information schedule type: value
> IM cassification code: value
> Business category: value

to 

> IM schedule type: value
> IM classification code: value
> IM business category: value

### Information schedule term page

change

> Information schedule type: value
> Information schedule name: value
> Business function: value
> Business category: value
> IM classification code: value

to 

> IM schedule type: value
> IM schedule name: value
> IM Business function: value
> IM Business category: value
> IM classification code: value
</details>

**Comment by CraigClark** [comment]
This comes from #391 

@mjmcclung, does this accurately reflect what was discussed?

@NicoledeGreef , I would like your thoughts on this before we proceed.

**Comment by mjmcclung** [comment]
Yes, you've summarized it correctly.  While all the 'IM' prefixes may seem redundant, it adds significant value in terms of clarity and context given our organizations maturity in this space.  Having these, and having this consistency, will make the education and awareness piece much easier, so thank you for accommodating this.

Should we add requirements to adjust the layout/bold font weight for the second piece of the Information schedule term page as well, for consistency?
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/52ead7d0-13a1-4130-91fe-df05e2b604cc)

**Comment by CraigClark** [comment]
> Should we add requirements to adjust the layout/bold font weight for the second piece of the Information schedule term page as well, for consistency?

Nah, that goes without saying. Just didn't document it.

**Comment by NicoledeGreef** [comment]
The redundancy of "IM" is not great. It makes it challenging to read and takes the eye away from what really matters...the words after IM.  Would be much better to express "IM" or "Information Management" in the header and leave it at that.

In general, shorter descriptions are better, as are non-repeated labels.

**Comment by mjmcclung** [comment]
Not sure where to go from here - should we just leave it as-is then?

Classification code **must** be prefixed by 'IM' until our maturity improves.  I deal with this point of confusion regularly (weekly/monthly) and have no desire to perpetuate this confusion in this space as well.

**Comment by CraigClark** [comment]
Let's leave the labels alone. I can change the label/value layout of term page easy enough, It would make it look more modern. Are you ok with that @NicoledeGreef ?

**Comment by NicoledeGreef** [comment]
Sure, let's try that. Can you please mock something up, @CraigClark ?

**Comment by CraigClark** [comment]
@NicoledeGreef sure

**Comment by CraigClark** [comment]
@lkmorlan ready fore review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/392-update-info-schedule-term-page-layout

**Comment by CraigClark** [comment]
@NicoledeGreef to approve

**Comment by NicoledeGreef** [comment]
@mjmcclung  - please review in Test

For example: https://test.cat.data.fin.gov.bc.ca/node/46

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/63a0cdf3-9eab-47b3-873f-009749c99303)

https://test.cat.data.fin.gov.bc.ca/information-schedule/orcs/property-taxation/property-taxation-general/general

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/e5770785-ccc5-4a81-a0fd-c382652e9251)

**Comment by mjmcclung** [comment]
Is it possible to have a larger gap between the IM classification code and Active period on the term page to help differentiate these two sections?  There was a large gap before, but with the changes it seems to have gone away.  Having a larger gap will help users differentiate that these are separate chunks of information, rather than overwhelming them with everything all at once.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/28bd20d1-7d13-486c-8ca2-073ffc4f5de9)

**Comment by CraigClark** [comment]
@mjmcclung yes, we can do that

**Comment by CraigClark** [comment]
@mjmcclung Useless trivia. 

Drupal programmatically assigns every piece of content a unique ID (called a node id) that cannot be changed.

Amusing coincidence in the node IDs:
-  node 1 is the help page for the information schedule
- Node 100 is the field information for info schedule

**Comment by CraigClark** [comment]
@mjmcclung I've added the spacing fix task here #410 , If you are happy with this ticket other than that, could you please close it?

**Comment by NicoledeGreef** [comment]
Closing #392; outstanding styling change is in #410
