### ISSUE TITLE
Remove use of private use Unicode character for search icon

### ISSUE THREAD

**Issue by lkmorlan** [bcgov/MFIN-Data-Catalogue#393]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6304210320

---

## Describe the bug
The `value` attribute of the search button is a Unicode Private Use Area character to display the search symbol. This causes an HTML validation warning.

## To reproduce
Validate any page with the search box.

## Expected behaviour
Add the character using CSS.

**Comment by CraigClark** [comment]
@lkmorlan 

ready for review/merge

there are two branches to fix this

1. https://github.com/bcgov/bcbb/tree/dc-393-replace-unicode-icon-in-search-submit
2. https://github.com/bcgov/bcbb-theme/tree/dc-393-theme-icon-in-search-submit

**Comment by CraigClark** [comment]
Hold on that, I dont like the scaling. let me try to fix it

**Comment by lkmorlan** [comment]
Merged
