### ISSUE TITLE
Change order of elements on build page

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#394]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6304228436

---

Currently the desktop view of the page has the build sections on the left and the publish options on the right. While this is visually ok, the actual order in the DOM is: 
1. Last review date
2. Modified date
3. Publish options
4. Build sections

The problem with this is that a screen reader will read things in that order and they display on mobile in that order. It is nit intuitive to make changes in build sections then go backwards to publish the changes.

## Proposed solution

Change order in the DOM to:

1. Last review date
2. Modified date
3. Build sections
4. Publish options

Fix the styles.

There are currently classes controlling the order of elements. they need to be removed. We can do this better with grid.

The desktop display remains visually unchanged.

**Comment by CraigClark** [comment]
@lkmorlan ready for review/commit https://github.com/bcgov/MFIN-Data-Catalogue/tree/394-change-order-of-elements-on-build-page

**Comment by lkmorlan** [comment]
Merged
