### ISSUE TITLE
Build a report builder

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#395]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6313583751

---

on the reports section of the dashboard, create a 'Report builder' tab.

This will be a view with exposed filters. The filters allow people to create their own reports and export to csv.

This should be done as a view and discussed with Nicole before refining. I am not confident that this will offer much more than what the search page does now. Some experimenting will help determine that.

**Comment by CraigClark** [comment]
@NicoledeGreef 

First version of this is done at https://github.com/bcgov/MFIN-Data-Catalogue/tree/395-report-builder.

This is using 'out of the box' views features. If this is approved, there are some things that should be done to improve it.

## To do

- [ ] Theme filters
- [x] For record type, show term parents in view
- [x] For record type filter, show children in the hierarchy. So if I select *Data*, I would see everything that has the child terms, *Database*, *SQLServer* etc. (@lkmorlan)
- [x] For critical information filter, use `Yes/No` values instead of `True/False`
- [x] For personal information filter, use `Yes/No` values instead of `True/False`
- [x] Add Workflow State for view and filter
- [x] add Publish State for view and filter

## Issues

- [x] **Duplicate results:** The view is generating duplicate results, this is caused because the columns and assets used fields are using deltas. Debug steps: remove those fields from the view, no more duplicates (@lkmorlan)

**Comment by CraigClark** [comment]
Example export
[report-builder-example.xlsx](https://github.com/bcgov/MFIN-Data-Catalogue/files/14934204/report-builder-example.xlsx)

**Comment by CraigClark** [comment]
Sample of exported report
[report-builder-example.xlsx](https://github.com/bcgov/MFIN-Data-Catalogue/files/14934281/report-builder-example.xlsx)

**Comment by NicoledeGreef** [comment]
Please remove the item in the list related to Review status value "Active" and
remove the count of records that use the asset being reported on.

**Comment by CraigClark** [comment]
@lkmorlan as part of this, There is are custom buttons to scroll the table because the browser scrollbar isn't always obvious. When it is, you need to scroll from the bottom of the table of your mouse does not support swiping left or right. 

There is an addition to the costom module that needs to be reviewed/merged here https://github.com/bcgov/bcbb/tree/395-dc-table-scroll

I have attached the library to the base theme here https://github.com/bcgov/bcbb-theme/tree/395-dc-report-builder, this was an arbitrary decision. If you think it better to attach to dc theme that's fine.

**Comment by CraigClark** [comment]
Related #439 

This has been deployed to dev for review

**Comment by NicoledeGreef** [comment]
reviewed in dev. closing ticket
