### ISSUE TITLE
document the existence of the Authoritative Info field and why it is not currently being used

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#396]
https://cat.data.fin.gov.bc.ca/documentation/metadata-fields#authoritative-info

**Comment by CraigClark** [comment]
@NicoledeGreef I didn't catch this task and [documented](https://cat.data.fin.gov.bc.ca/documentation/metadata-fields#authoritative-info) it already. Unless you want to add to it, you can close this ticket.
