### ISSUE TITLE
Ability to set contact for metadata record

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#401]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a user I want the ability to change the contact listed for an individual metadata record so that questions can be directed to the right contact/team.

## Describe the idea

Add an option to the "Build" screen for a metadata record that allows the OPR contact to be overridden.

The contact is currently only configured (presumably) by administrators information is setup to describe the Office of Primary Responsibility (OPR).  In some cases though a specific record, or type of records associated with a single OPR might be better suited for different teams.

For example, in FREDA there is a Data Engineering team that creates most of the datasets, where as the Data Science team would create most of the Reports.

**Comment by NicoledeGreef** [comment]
New ticket created to define this: #416
