### ISSUE TITLE
Move the record type and location together

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#405]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a metadata editor I want to be able to identify the 'location' once I'd identified the 'record type' in Section 1 because I'm thinking about the location as I'm identify why type of record I'm describing.

## Describe the idea

Move the 'Location' field from Section 2 to Section 1 so that it can be provided once a user fills in the record type.

**Comment by NicoledeGreef** [comment]
It's easy to move but we'll make this part of future user testing before making the change. We'll be looking at the icebox for testing prompts.
