### ISSUE TITLE
Clarify help text for the 'Assets used'

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#406]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6378952064

---

## Describe the bug
Help text for the 'Assets used' field in Section 3 says the user should select an item, but they need to type the name of the item before select is available.  Help text needs to be clearer so users understand what they need to do.

## To reproduce
Steps to reproduce the behaviour:

1. Go to Catalogue 'Dashboard'
2. Click on 'Build' for a metadata record
3. Scroll down to 'Section 3: Origin and classification'
4. Click on 'Edit'
5. Scroll down to 'Assets used'

## Expected behaviour
Help text should clearly communicate the user needs to type the name of the metadata record they want to identify as an asset used by the current metadata record, or a drop down option should be available so the user can see the available options immediately.

## Screenshots
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/e0d1e116-b3d2-4eef-b5f8-5205d793762f)

**Comment by CraigClark** [comment]
@NicoledeGreef how about 'Start typing the name of the data, form or report used in this item. Only assets that currently exist in the Data Catalogue are available'

**Comment by NicoledeGreef** [comment]
complete
