### ISSUE TITLE
Reorder columns in sample data column import file

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#408]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6379034553

---

## User story

As a metadata record editor/creator I want the columns in the sample file for data columns to be arranged in the same order as the screen so it's easier to understand.

## Describe the idea

Update the sample file so that the order in the CSV matches the order each field is shown when editing directly in Section 6.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/f7d776f8-9adb-4379-a40b-4e7ffee3f824)

Currently the fields in the sample CSV file are ordered in a strange order that makes it hard to enter (e.g. the first thing I want to identify is the name of the column I'm describing) and compare to the edit column screen.

**Comment by CraigClark** [comment]
@lkmorlan This is a reasonable request. Right now, the sample download file and the current data file have the columns in alphabetical order. I imagine this is what the module does by default. Is it feasible to have the downloaded file columns to be in the same order of whatever is set on the paragraph?

@NicoledeGreef The other option would be to order the columns alphabetically on the form. I'm not sure if that makes sense.

**Comment by lkmorlan** [comment]
We can certainly do this. We may need to have a list in order in the code.

**Comment by NicoledeGreef** [comment]
@lkmorlan please proceed with the re-ordered sample file. Please ensure this works when users download the data dictionary from the node view as well.

**Comment by NicoledeGreef** [comment]
verified in dv14
