### ISSUE TITLE
Look at UX for placement of field help text

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#409]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6379086519

---
## User story

As a editor or creator of metadata records I want to be clear about what I need to enter into each field of the record.

## Describe the idea

Currently the help text for fields shows up after the field input.  When looking at this initially it took me a moment to disconnect the field name and help text as they had a close relationship visually.  The relationship would be clearer to me personally if the help text was moved directly below the field name creating a clear relationship between the three pieces (field name, help text and field input).

Idea is to engage UX team (potentially IMB resources) to determine standards and/or test if this is an issue other users have.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/06aea169-d853-4489-babb-e88dfd30ab12)

**Comment by CraigClark** [comment]
We will increase the space between the input fields. This has been done on the record form, I see it was overlooked for the data dictionary. This will help users better understand related items (rule of proximity). We can decide on moving the help text later. See #410

**Comment by CraigClark** [comment]
Closing, this has been fixed in #410
