### ISSUE TITLE
Documentation for Deployment and DevOps

### ISSUE THREAD

**Issue by sylus** [bcgov/MFIN-Data-Catalogue#41]
## Overview

The current documentation surrounding the Deployment and DevOps can be found in the private `tenant-gitops-ea352d` repository which houses the application manifests.

* https://github.com/bcgov-c/tenant-gitops-ea352d (Private Repository)

Everything is stored in markdown in the `docs` folder but also published to the wiki section in the github repository.

This allows for the following benefits:

* track all documentation changes in code
* single source of truth for both wiki pages and generated PDF
* enable peer review for documentation changes

> **Note**: The `tenant-gitops-ea352d` repository was chosen over `mfin-data-catalogue` as some information is assumed private and hence a private repository is better suited for the documentation as well as the wiki page which would otherwise be public.

## Blocker(s)

- [ ] Grant access to `tenant-gitops-ea352d` for @smulvih2 

Right now only BCGov Employees and 2 external collaborators are allowed to access the `tenant-gitops-ea352d` repository.

I would like @smulvih2 to have access to the `tenant-gitops-ea352d` repository.

Currently only myself @lkmorlan have access to it.

## Work

Markdown files in the `docs` folder will be generated automatically into corresponding wiki pages:

![Markdown Files](https://github.com/bcgov/MFIN-Data-Catalogue/assets/984304/01f15d3f-90f0-4c1e-ba03-2b518e0f75e6)

![Wiki Pages](https://github.com/bcgov/MFIN-Data-Catalogue/assets/984304/651dd5c3-2aed-4a21-a5cf-c8f27fab75d5)

In addition on a stable release tag a generated PDF using pandoc will be generated and attached to the release.

> **Note**: This can also be done manually simply by running the `scripts/build.sh` file.

**Comment by CraigClark** [comment]
thanks for this @sylus , I would like to see the documentation my self that's in the private repo. Could you please send me a copy? BTW, I like the idea of keeping the docs in a wiki. 

As for the private repo, Do you think we will need to keep it private, or is this something that can be public once the vault is sorted out?

**Comment by CraigClark** [comment]
@NicoledeGreef @chrislaick This documentation is now in a public repo and ready for review at https://github.com/bcgov-c/tenant-gitops-ea352d

**Comment by NicoledeGreef** [comment]
As a Gov, we are to be open by default (unless there is a reason not to be).  We did review the content- is there any reason we couldn't move this to **bcgov**, our public Organization in GitHub?

bcgov-c is a private Organization.  If the repo needs to be in a private organization, we will need to migrate to another Organization as bcgov-c is only a temporary Organization for start-up purposes (the policy is not to have code reside there for longer than 11 months).  

If needed, we are in the process of setting up a new private Organization in github for other business needs and this repo could be migrated there.

**Comment by CraigClark** [comment]
@NicoledeGreef at this point it isn't needed. the repo is public, it's been reviewed by Will, Liam, you, Chris and myself. We have used the public repo for successful builds.

**Comment by CraigClark** [comment]
@NicoledeGreef I talked to @sylus  about moving this repo to bcgov.
There is an issue doing that at the moment. Right now, ARGO CD is configured to read from https://github.com/bcgov-c/tenant-gitops-ea352d. If we move the repo, builds won't work. We need to find out from the platform team how to make ARGO read from a different repo.

**Comment by CraigClark** [comment]
@chrislaick will follow the documentation to set up an instance of Matomo and report back any issues.

**Comment by CraigClark** [comment]
@chrislaick , do you know how we go about having ARGO read from a different repo? Right now it's public, so it can move to bcgov, however ARGO reads from bcgov-c, so if we just move it,  the build process will break

**Comment by chrislaick** [comment]
@CraigClark I don't have any experience with ArgoCD, but scanning through the [tech docs](https://docs.developer.gov.bc.ca/) it looks like there is somewhere in the ArgoCD UI that pertains to the Source repository URL such as: `git@github.com:bcgov-c/tenant-gitops-abc123.git`
My guess is that this needs to be updated?
See below:
https://docs.developer.gov.bc.ca/argo-cd-usage/#create-the-application

**Comment by NicoledeGreef** [comment]
Closing this; can be re-opened if there are issues with the tech docs.

Note: The Org will be changing to bcgov from bcgov-c.  We will be putting in a request to Platform Services around Argo needing to point to the repo in bcgov.  We will clone the repo into bcgov when that request is in flight.
