### ISSUE TITLE
Include published metadata records on dashboard

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#413]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a metadata record editor I want to be able to find published records I've summitted or my team has submitted so I can edit them.

## Describe the idea

Consolidate the draft, review and published metadata records into one section on the dashboard that filters by default to records that were either edited (last?) by the user, or the organization(s) the user is part of.  Items requiring review should be listed at the top so they're visible.

Alternatives ideas:

- only consolidate draft/published metadata records and show metadata records needing review next to the create a new metadata record list or above consolidated list.
- Add another section for published records

## Background

I got used to being able to view/edit from the dashboard and when I published the record I initially I thought it was no longer visible for me to edit.  It took me a moment to figure out where I needed to go to edit it again, and even longer to notice there's a "Manage metadata records" button on the dashboard.

## Proposed Solution

- [ ] move Search box on Dashboard back to the site header @lkmorlan 
- [ ] move the Manage metadata button and text up to where Search was @CraigClark 
- [ ] reverse order of Manage metadata button and the descriptive text @CraigClark

**Comment by mjmcclung** [comment]
+1 for this idea

**Comment by NicoledeGreef** [comment]
We want to make access to the **Manage** view more prominent. We don't want to move all metadata records in various states to the Dashboard as it will be too cluttered.

**Comment by CraigClark** [comment]
Closing this. How to manage records will be covered in on-boarding, training and documentation.
