### ISSUE TITLE
Add option to edit published metadata record from Manage screen

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#415]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6385329527

---

## User story

As a user I want to be able to edit published metadata records easily

## Describe the idea

When looking at the Manage screen there doesn't appear to be an option to immediately edit a record.  Add a new button after the "View" button and remove "Unpublish" if there's not space for all three as this will be the less used action.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/d91db5ca-93f0-4991-9343-c7110d14d744)

**Comment by NicoledeGreef** [comment]
We will add a "Build" button to the Manage screen to reduce the number of clicks to get to editing.

**Comment by CraigClark** [comment]
Ready for review / merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/415-add-build-button-to-manage-page



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/a33bdf42-4aa9-4425-819c-63f05d22364b)

**Comment by CraigClark** [comment]
Assigning to @lkmorlan 

NVM. There's a peirmssion issue. I'll see what I can sort out and assign to Liam if needed.

**Comment by CraigClark** [comment]
Ready for review / merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/415-add-build-button-to-manage-page @lkmorlan

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
reviewed in dev
