### ISSUE TITLE
Create a Contact field on the metadata model

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#416]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6385787205

---
Dataset should have a Contact field available that supports capture of Name and Email address.
- [x] It is not a required field.
- [x] For Build, it should be in Section 2 under the **Office of primary responsibility**.
- [x] For node view, it should be located under **Office of primary responsibility** using a new bolded header "Contact"
- [x] turn off Required for the "Additional Information" field in the taxonomy

- [ ] edit the exiting OPRs to remove the Additional information values @NicoledeGreef
- [ ] add Documentation for the new field @NicoledeGreef

**Comment by CraigClark** [comment]
Tested the field on dv14 and it looks good. There are some style adjustments, I'll look after those

**Comment by CraigClark** [comment]
@lkmorlan I made some style adjustments, we can merge then Nicole can review

**Comment by CraigClark** [comment]
@NicoledeGreef to review
