### ISSUE TITLE
Allow editors to unpublish any of their organizations records

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#417]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a metadata record editor I want to be able to unpublish records created by other members of the organization

## Describe the idea

Show the "Unpublish" tab/button options if a user is an editor the organization that is responsible for the metadata record.  This helps the organization continue to maintain records on their own when people aren't available or have left the organization.

**Comment by NicoledeGreef** [comment]
The `Catalogue manager` user role can do this for their Organization.  Users with this role can see and manage all records whose OPR matches the user's Organization.
