### ISSUE TITLE
Allow related documents to have a title

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#419]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6387803536

---
## User story

As a metadata editor I want to be able to communicate the difference between two different documents of the same type so that users know what they are clicking a link to view

## Describe the idea

Some of the related document types (e.g. related legislation) could have more than one resource that should be highlighted.  In these cases it would be helpful to be able to provide a "Document title" in addition to the "Document link" so it's clear to users viewing the catalogue what each link represents without clicking on the option.

Below is an example where I created a record that links to the Speculation & Vacancy Tax Act, and two of its regulations (there's more).

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/22d8ab3c-e289-43df-9da0-66cbc7d0f53f)

## Proposed Solution

- [x] Add a title field for Related documents
- [x] link text is the combination of the selected **term** and the **Link title**

See #402 for acceptable link protocol patterns

**Comment by NicoledeGreef** [comment]
marking this as stuck behind #402

**Comment by NicoledeGreef** [comment]
- [x] ND to test it in dv14 (fileshares are challenges; use extra long paths) 
- [x] ND to update the Documentation to reflect current state

**Comment by NicoledeGreef** [comment]
This relates to: https://github.com/bcgov/MFIN-Data-Catalogue/issues/402#issuecomment-2070630231

@ChristaBull  - please review

**Comment by ChristaBull** [comment]
Seems to work how you proposed the solution.  When a title is entered it will show up after the "[DOC TYPE]:" prefix, otherwise just "[DOC TYPE]" is displayed for the link text.  When a title is removed there are no unexpected issues.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/6e38fcab-c57e-4b69-a8b0-a2d83507c975)
source: https://test.cat.data.fin.gov.bc.ca/node/87
