### ISSUE TITLE
Re-order tabs when viewing a metadata record

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#420]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6393069830

---

## User story

As an editor I want to see the tab options I usually need on the left-side of the page to manage a metadata record so I don't find myself wanting to or clicking on less used items (e.g. the 'Unpublish' tab) as often.

## Describe the idea

Move the Unpublish tab to the right so it's less likely be clicked on.  When users come to this page their main goal is usually to change the metadata record, not unpublish it.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/a6986dc3-c14f-4b14-89ae-ea580a5aaf14)

**Comment by NicoledeGreef** [comment]
verified in dv14
