### ISSUE TITLE
Separate fields documentation into individual book pages.

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#421]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6395356233

---

Currently, there is not a reliable way to directly link to information about a specific field.

- [x] Separate all the fields in the documentation in their own pages under appropriate parent pages for MR, term and Data dictionary
- [x] On the parent page for fields, include a list of fields that are not publicly available
- [x] go through the help text mr content type and any paragraph types and if there is a link to field documentation, update it to link to the newly created page for the field

>[!NOTE]
>There is a comment on another ticket related to this, I can't find it. @NicoledeGreef, if you come across it, please reverence this ticket.

**Comment by CraigClark** [comment]
@lkmorlan The updated field help text is ready for review/merge here <https://github.com/bcgov/MFIN-Data-Catalogue/tree/421-update-field-help-text>

Note that the updated links are to documentation pages on prod.

**Comment by lkmorlan** [comment]
Merged

**Comment by CraigClark** [comment]
done
