### ISSUE TITLE
Reorganize build page and sections to align with MR view page

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#422]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a catalogue editor
I want to be able locate the section containing the metadata I want to edit
so that I can edit my record.

## Describe the idea
The MR view page is grouped and ordered in a specific way:
- Some details on the left
- data usage, value, IM and related documents in a grey box on the right, in a specific order

When I go to edit my page the build sections presented to me do not correlate to the sections I just saw on the MR page.  I am unable to find the piece I want to edit, and edit what I want without clicking through multiple sections to find where it is located.

E.g. 1:
On the MR page Personal Information, Security Classification and Critical Information are all grouped under a "Data value" heading.
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/1a7ead70-1484-48bc-843a-aeb7deb240a3)

On the build page Personal information and security Information are found in Section 3 titled Origin and classification.  Critical information is found in Section 4 called Significance.
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/7bad67a9-b274-45a5-b24d-468e21f69b07)

E.g. 2:
On the MR page there is a large group of information that appears together on the left
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/85309ea3-ec96-4407-9fce-5c7a8327f319)

On the build page this information is found in both Sections 1 and 2
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/d97694a5-8907-4713-acf4-b786b13dd4d2)

Proposal:
- Reorder/regroup the Build page so that it aligns with the content on the view page:
  - Group the main MR info into one section called Details and description
  - Group Source system, Assets used (lineage) and Data quality issues under one section called 'Data usage'
  - Group Personal Information, Security Classification and Critical information under one section called 'Value'.
  - Split Information schedule into it's own section called Information Management

## Actions

- [ ] Hurray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
closing for now (icebox)
