### ISSUE TITLE
Remove field_high_value_info from documentation since it's no longer in the content model

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#423]
Something to be aware of: the Documentation is content and we are only consistently updating Documentation in Production since the postgres migration completed. I see it in Production: https://cat.data.fin.gov.bc.ca/documentation/metadata-fields#high-value-info

_Originally posted by @NicoledeGreef in https://github.com/bcgov/MFIN-Data-Catalogue/issues/195#issuecomment-2040202790_

**Comment by CraigClark** [comment]
@NicoledeGreef Closing this. I'll omit it while doing #421
