### ISSUE TITLE
The UI on book edit page is confusing for managing pages and paths | Other book fixes

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#425]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6413684344

---

## Describe the bug

Currently on a book content type page, there is a block to manage where the page fits in the structure, but there are no options.

## To reproduce
Steps to reproduce the behaviour:
1. On prod, go to any page in the documentation
2. Click edit tab
3. scroll to down to bottom of the page
4. see that there is a book outline section, but no way to place the current page in the book 
5. see that there is a block for managing URL aliases, but no way to add an alias.

## Additional adjustments

There is no need for the book navigation to appear on an edit page. Removing it will be less clutter and, without the sidebar in use, it should allow editors to allow the fill screen width for editing.

## DoD

- [x] Remove the blocks on node edit for managing book
- [x] Remove the block on node edit for managing aliases (let pathauto deal with it)
- [x] Add page in the administration section of the docs explaining how to use the outline tab and the book manager page @CraigClark 
- [x] Configure pathauto for book. path should be `/book-title/page-of-the-book-that-i-am-on`
- [x] remove book index in the side bar.

## Expected behaviour

I can easily manage a pages position in a book or create a new book without having to use book admin.

## Screenshots

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/fd238ca1-9b3c-4935-8147-4ed4c9a280e0)

**Comment by lkmorlan** [comment]
Most of this is merged; over to @CraigClark for the rest.

**Comment by CraigClark** [comment]
@lkmorlan I just noticed that the local tasks tabs are not available on a book edit page

This is what i see

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/b0e2a919-cb69-4137-8522-76f5c3b04051)

This is what I expect to see



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/1cb7d8c8-16d8-4168-bf0a-f3464b8d695b)

**Comment by lkmorlan** [comment]
Local tasks are hidden on all edit pages in their block config.

**Comment by lkmorlan** [comment]
Local tasks are now hidden only on `data_set` edit pages in a non-default form display mode.

**Comment by CraigClark** [comment]
This looks good now. Moving it back to 'to do' until docs are done

**Comment by CraigClark** [comment]
Documentation is added here https://cat.data.fin.gov.bc.ca/documentation/managing-documentation

Closing
