### ISSUE TITLE
Add ability to search documentation

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#426]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6413878020

---

## User story

As an editor,  I want to quickly find items in the documentation so that i can work quickly and accurately with minimal disruption.

## Describe the idea

Currently the documentation page has 5 top level pages and close to 80 sub pages. This means that a user would have to have some idea where in the tree they can find the information they need.

If we add a search block above the side index on on internal pages and on the front page of the index page, it could help people find things.

## Actions

- [x] A new search index for the documentation
- [x] a block with the search field in it
- [x] a view to display results (Title, link and summary if present)
- [x] Add Documentation book outline to results page
- [x] theme adjustments @CraigClark 
- [ ] ~~while not necessary, it would be a good idea if someone when through and added a summary for each help page.~~ not necessary as we are using a search snippet on the results page
- [x] Document new block `bcbb_book_navigation` in `bcbb` @CraigClark 

## Example of search box

![search-docs](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/a1cd89f1-89a3-4b91-958f-0fcc4029d50d)

**Comment by lkmorlan** [comment]
[Instructions for creating a `search_api` processor](https://www.drupal.org/project/search_api/issues/3009668#comment-14410607), which is needed for limiting the search to a single book.

**Comment by lkmorlan** [comment]
For now, we will not limit to a single book. This has been documented as a known issue in the wiki.

The rest of this ticket is for @CraigClark.

**Comment by CraigClark** [comment]
Blocked, pending #460

**Comment by CraigClark** [comment]
@lkmorlan ready for merge/review https://github.com/bcgov/MFIN-Data-Catalogue/tree/426-search-docs

**Comment by CraigClark** [comment]
Currently the book content type is used exclusively for the documentation pages. If, at some point in the future, there is a need for more _books_ , more development work will be required. This is mentioned in the [user documentation](https://cat.data.fin.gov.bc.ca/documentation/managing-documentation) in the [wiki for developers](https://cat.data.fin.gov.bc.ca/documentation/managing-documentation).

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
reviewed in dv14

**Comment by CraigClark** [comment]
We have added a reset button that needs to be themed. @CraigClark

**Comment by CraigClark** [comment]
@lkmorlan reset button is themed here https://github.com/bcgov/MFIN-Data-Catalogue/tree/426-reset-button-search-docs
please review/merge

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified in dv14.

tried **security classification** and **"security classification"**. results were as anticipated.
