### ISSUE TITLE
Add 'active' to review status

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#429]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

on the field 'field_review_status' add a value called 'Active'. If a record is not withing a month of needing the review date (needs review), and is not passed the due date (Review overdue) it would be 'active'. 'Active' would not appear on the node view because a record is assumed to be active. It could be useful for reports.

This idea came from work on #395 

If a record does not need a review, the field for review status is empty. For reporting, it might be nice to have something more explicit.  I tried setting 'Active' for 'no results', which works in the results table, but it's confusing in the filters.

**Comment by NicoledeGreef** [comment]
Decided not to pursue this.
