### ISSUE TITLE
Improve CI to run drupal-test-traits etc

### ISSUE THREAD

**Issue by sylus** [bcgov/MFIN-Data-Catalogue#43]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6509122573

---

## Overview

Right now the CI just performs a standard Drupal site install along with phpcs before it builds the container and then pushes them to Artifactory.

We instead should be grabbing a minimized test DB with limited data so we can run drupal-test-traits etc in our CI and ensure all of our test cases pass in an automated fashion.

We weren't able to do this for RSAMS due to the sheer size of the DB but for MFIN Data Catalogue this should be doable.

## Blocker(s)

- [x] Waiting for a DB to perform tests against @lkmorlan 

## Work

- [ ] Retrieve a minimized / cleansed DB @sylus 
- [ ] Establish automated process to get newer minimized DB @sylus 
- [x] Need to update phpunit.xml which references DV21 @lkmorlan 

The problem becomes where to host this DB so GitHub actions can pull it done. As a stop gap we could grab these databases from an Azure Storage Account but something official from BCGov would be idea.

Not sure how pressing of an issue this is but nonetheless I am documenting it.

**Comment by sylus** [comment]
Hi @CraigClark so this has never been actioned and right now the default CI tests are more for just linting and testing an install which are pretty small tests. I would need to work with @lkmorlan on this and there are problems above that need to be solved.

**Comment by CraigClark** [comment]
Thanks @sylus , I've added @lkmorlan to the ticket and moved it into sprint. Could you please work with him to do whatever needs doing?

**Comment by lkmorlan** [comment]
The references to `dv21` can be changed anytime. I run tests now on `dv14`. To make the tests work, I set environment variables that refer to `dv14`.

I can make a fresh minimal site install with just the content needed for the tests.

**Comment by lkmorlan** [comment]
@sylus A dump file containing a minimal database is on the `dv` server in `/home/ec2-user/dv14-pg_dump-2024-05-07.sql.gz`. I have successfully run ExistingSite tests on this site.

**Comment by sylus** [comment]
@CraigClark so the question is where can we store this db image such that the actions runner can use it?

I don't think we can put this image in a public location.

Does BCGov have a place like an azure storage account where we could put this such that they can pull from?

**Comment by NicoledeGreef** [comment]
Location for storage of DB image needed; I will request S3 object storage. I surmise that it will not be in place before June.

**Comment by NicoledeGreef** [comment]
Putting this ticket on hold until the object storage is established.

**Comment by NicoledeGreef** [comment]
S3 Object Storage bucket is now available (see #506).

**Comment by NicoledeGreef** [comment]
We need insight from a devOps expert on how to proceed if we are to set up the testing infrastructure using the github actions and minimized db in Object Storage.

**Comment by Ntirukovela** [comment]
@NicoledeGreef  - Can we update list of items to discuss . Our team can start reviewing internally and get back to you

**Comment by NicoledeGreef** [comment]
@Ntirukovela the dev team is meeting on Monday and we'll discuss this ticket and get back to you on what support we need,

**Comment by NicoledeGreef** [comment]
We're closing this ticket. We will consult and work up a list but nothing imminent required from AppOps at this time.

**Comment by chrislaick** [comment]
@chrislaick will add this to the questions list for Will Hearn.
