### ISSUE TITLE
Investigate possible solutions to extra wide tables

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#431]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6432298545

---
Wide tables have non-obvious horizontal scroll bar (bottom of table).

@CraigClark to look into what can be done

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by CraigClark** [comment]
We have a solution for this and have added it to the base-build.

See https://github.com/bcgov/bcbb/tree/395-dc-table-scroll

**Comment by CraigClark** [comment]
We have added a feature for side scrolling wide tables and added it to the base-build. see [this commit](https://github.com/bcgov/bcbb/commit/6804346b988c020816e9bdfb38884c3d12f3d04d)

Documentation on how to use [scrolling wide tables](https://github.com/bcgov/bcbb/wiki/scrolling-wide-tables) has been added to the base-build wiki.

**Comment by CraigClark** [comment]
@NicoledeGreef you will be able to see this when we demo the report builder. It only works on wide tables.

**Comment by NicoledeGreef** [comment]
the arrows look good
