### ISSUE TITLE
Weird line breaks for Special Schedules

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#432]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6441711416

---

Something weird is happening with line breaks in the Information Schedule content, and specifically the special schedules content.  The content is presenting like cells in a table instead of text on the page.  This was not present in the content prior to migrating to Postgres.

Example:
[https://cat.data.fin.gov.bc.ca/information-schedule/special/transitory-information](https://cat.data.fin.gov.bc.ca/information-schedule/special/transitory-information)
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/ce7d2113-f0fd-407b-8e69-02e46d12fd4f)

## Expected behaviour:
Content reads from left to right, in paragraphs.
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/e47011b4-6ade-4547-8fb8-0b89d261ee8d)

**Comment by CraigClark** [comment]
@lkmorlan please review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/432-info-schedule-term-page-layout-fix

That will fix this

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
reviewed at: https://dev.cat.data.fin.gov.bc.ca/information-schedule/special/transitory-information
