### ISSUE TITLE
Support Transition Plan

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#433]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6446800836

---

This ticket is meant as a laundry list of items to take care of in order to ensure smooth transition of support from OpenPlus to BC Gov staff.

- [x] ~~Openplus to transfer of admin credentials for Drupal instance (likely May 31)~~
- [x] ~~IMB to reset admin password~~
- [x] adjust contact for Finance Data Catalogue of the gcNotify service
- [x] adjust the Tech Lead contacts for the Finance Data catalogue in Silver @NicoledeGreef
- [x] adjust repo privileges @NicoledeGreef 
- [x] devOps Solr upgrade session (May 24)
- [x] devOps php upgrade session (May 10)
- [x] devOps (tech walkthrough) meeting (April 24/25ish)
- [x] facilitate sessions with Will to address questions
- [x] https://github.com/bcgov/bcbb/issues/40 @NicoledeGreef 
- [x] #452 @NicoledeGreef
- [x] #453 @NicoledeGreef and @lkmorlan 
- [x] ensure MFIN Devs and App Ops have been sent up in OCP, ArgoCD, Artifactory, etc, @chrislaick 
- [x] #307 ~~(api keys to vault)~~

**Comment by chrislaick** [comment]
@NicoledeGreef Dan Howard, Dan Hofman, Kunal Kardam have been added to OpenShift project access as Admins.

**Comment by chrislaick** [comment]
@NicoledeGreef Dan Howard, Dan Hofman, Kunal Kardam have been added to Artifactory as Project Admins.

**Comment by chrislaick** [comment]
@NicoledeGreef Dan Howard, Dan Hofman, Kunal Kardam have been added to ArgoCD as Admins. Marking task as complete :)

**Comment by CraigClark** [comment]
@NicoledeGreef We don't need to transfer credentials. From the meeting yesterday, Chris and Dan can manage this on their own.

**Comment by CraigClark** [comment]
@NicoledeGreef I'd wait to _adjust repo privileges_ until Monday. Just in case Will needs to do something on the weekend.
