### ISSUE TITLE
Use  HTML tags in the data dictionary

### ISSUE THREAD

**Issue by Rafael-hk** [bcgov/MFIN-Data-Catalogue#434]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6459581885

---

The data dictionary has several columns in it where a user can create rich text using CKEditor.
When a data dictionary is exported, it correctly exports the html.

The issue is that when you import the html, it is not rendering correctly.

For example, this is the value for `column_allowed_values` in the excel/csv file:

```txt
<p>One</p><p>Two</p><p>These are in a list</p><ul><li>one</li><li>two</li><li>three</li></ul>
```

Once you import it, and look a the source HTML, it renders as:

```html
<p>&lt;p&gt;One&lt;/p&gt;&lt;p&gt;Two&lt;/p&gt;&lt;p&gt;These are in a list&lt;/p&gt;&lt;ul&gt;&lt;li&gt;one&lt;/li&gt;&lt;li&gt;two&lt;/li&gt;&lt;li&gt;three&lt;/li&gt;&lt;/ul&gt;</p>
```

## To duplicate

1. Create a record of type data
2. in the columns section on the build page, add a column.
3. in one of the text areas, add some content using CKEditor
4. save
5. export the columns as csv or excel
6. import the file you exported in step 5
7. See that html is not rendering correctly

## Expectation

- [ ] Importing a csv/excel file with html in one of the text areas will render html correctly in accordance to whatever is allowed by the input format.

I tested this on <https://dv14.openplus.ca/node/68>
---

## Original authors post

> ## User story
> 
> When an entry in a data dictionary is inserted/edit, there are html tags that are added.
> Under "view draft", when visualizing the data dictionary, the tags are being displayed instead of being rendered (not sure this is the correct word). This can be confusing and make it for a worse UX.
> 
> Here is an example:
> When editing:
> ![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/166660833/2bd6d36a-064f-442a-a0e4-9d3242cbed03)
> 
> When viewing:
> ![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/166660833/52977ba9-5e95-4f0d-a6e3-e6f090b5d49a)

Idea: render the html tags.

**Comment by CraigClark** [comment]
Thank for for posting this @Rafael-hk. Could you please post a link to whee this is happening? I tested in our dev environment and I was not able to duplicate this.

Also, did this happen when you edited manually, or were you importing a file. If importing, could you please attach the file you are using?

**Comment by CraigClark** [comment]
relabelling as bug. This should not be happening

**Comment by Rafael-hk** [comment]
I have only seem this error when importing a data dictionary with the html tags.

Here is a way to replicate the issue:
- Download a data dictionary that use html to format the text (here is an example: https://test.cat.data.fin.gov.bc.ca/node/81). It can be either csv or xlsx.
- import it again (either on the same dataset or in a new one)
- In the validation screen, it will show the tags:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/166660833/140f8ff0-c9ce-4f07-9e70-5cf33e7c4ba5)
- When editing, the tags are used correctly:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/166660833/172fcb7e-30f5-41a2-99de-f1570f37c300)
- when viewing, the tags are not used correctly:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/166660833/75c93f05-24fb-4d4c-89e3-108353cc72ba)

Here is the file used: [log-release_ID_81.xlsx](https://github.com/bcgov/MFIN-Data-Catalogue/files/15001307/log-release_ID_81.xlsx)

**Comment by CraigClark** [comment]
Thank you @Rafael-hk I was able to duplicate this in our dev environment with the additional info you provided.

**Comment by CraigClark** [comment]
Tested and passed on dv14
