### ISSUE TITLE
Allow security classification to be unknown

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#435]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a user I want to be able to enter a metadata record without knowing the security classification.

## Describe the idea

Currently a user is required to provide a security classification, and if they select an option and save have no way to identify they don't actually know the security classification.  An option should be available to identify the classification is unknown.

**Comment by NicoledeGreef** [comment]
this is resolved by actioning #437
