### ISSUE TITLE
Simplify edit metadata record sections

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#436]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a metadata editor I want to click less to enter the details for a metadata record.

## Describe the idea

Having multiple sections to edit in a metadata record is confusing (they don't align with the view) and causes it take more time to enter the information.  It would be helpful if the core metadata record details (i.e. everything except the data dictionary) could all be edited on one page by clicking a single edit button.  The fields could still be broken down by section headings, but it would be preferable for it to be displayed on one screen.

**Comment by NicoledeGreef** [comment]
Couple of reasons it is set up this way:
1 - Drupal editing workflow
2 - there are required fields in each section and each section cannot be saved unless the required fields are completed so if there is just one big editable session that will be an issue
