### ISSUE TITLE
move "Data quality issues" edit field to Section 2

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#437]
**OP timer**

---
**Data quality issue**s is currently in Section 3 and we have resolved to move it to Section 2 because it is not necessarily Origin or classification related and it is a text area rather than a point and click selection. It is not required whereas other values in Section 3 are required and required fields prevent users from saving a section.

**Comment by CraigClark** [comment]
@lkmorlan ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/437-move-data-quality-issues-to-section-2

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
reviewed in dev
