### ISSUE TITLE
Clean up old test files when test run

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#438]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6466792260

---

When the automated tests are run they are writing files to the server. Each time the tests run, more files get created. 

We need a clean up process to make sure unnecessary files are not kept around.

**Comment by lkmorlan** [comment]
I have created the script on the `dv` server `~/bin/clean-test-files.bash`. This removes the test files.

**Comment by NicoledeGreef** [comment]
- [ ] add a wiki note with a reference to the script

**Comment by CraigClark** [comment]
passed on dv14
