### ISSUE TITLE
Theme the report builder

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#439]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6473946939

---

This task is for styling the report builder. It should not start until:

- [x]  #395 is approved
- [x] Order of filters is confirmed, see below

## Fiend and filter order

Theming the filters is going to be complex. We would like to ensure everything is in the right order before we proceed.

### Fields

These are the fields, in order, displayed on the table and the csv download.

1. **Title** | Shows value
2. **ID** | shows value
3. **Link to Content** | link
4. **Record type** | shows value
6. **Historical** change | show as yes/no
7. **Location** | show as yes/no
8. **Office of primary responsibility** | shows value
9. **Visibility** | shows value
10. **Source system** | shows value
11. **Series** | shows value
12. **Columns** | shows as a count of the number of items in the data dictionary, ie *8*
13. **Assets used** | shows as a count of the number of assets used, ie *5*
14. **Data quality issues** | show as yes/no
15. **Personal information** | show as yes/no
16. **Critical information** | show as yes/no
17. **IM classification code** | shows value
18. **Related documents** | shows as a count of the number of related documents, ie *5*
19. **Security classification** | shows value
20. **Published date** | shows value
21. **Modified date** | shows value
22. **Last review date** | shows value
23. **Review status** | shows value
24. **Content revision**| shows value
25. **Published** | show as yes/no
26. **Owner (author)** | shows value
### Exposed filters

These are the filters, in order, you can use to refine your report.

1. **Title** | input: text field
2. **ID** | input: number
3. **Record type** | input: select list
5. **Office of primary responsibility** | input: select list
6. **Visibility** | input: select list
8. **Source system** | input: select list
9. **Series** | input: select list
10. **Personal information** | input: yes/no
11. **Security classification** | input: select list
12. **Critical information** | input: yes/no
13. **Published date** | input: date picker
14. **Modified date** | input: date picker
15. **Last review date** | input: date picker
16. **Review status** | input: select list
17. **Moderation state** | input: select list
18. **Published** | input: yes/no
19. **Authored by** | input: auto complete

**Comment by CraigClark** [comment]
@NicoledeGreef to approve #395 and the order of the finters

Craig will do the theme

**Comment by NicoledeGreef** [comment]
Order confirmed as above. Thanks!

**Comment by NicoledeGreef** [comment]
"ID" should please be modified to "Record ID"

**Comment by CraigClark** [comment]
ready for review/merge @lkmorlan https://github.com/bcgov/MFIN-Data-Catalogue/tree/439-theme-report-builder

**Comment by lkmorlan** [comment]
Merged

**Comment by CraigClark** [comment]
@nicole to review
