### ISSUE TITLE
Scan container images for vulnerabilities

### ISSUE THREAD

**Issue by sylus** [bcgov/MFIN-Data-Catalogue#44]
## Overview

While the containers we build as part of docker-scaffold are run in restricted root and custom security contexts under OpenShift we still need to ensure that critical and high vulnerabilities don't make their way into the container images.

> **Note** We only extend on the official Drupal container images provided by Docker and only reference a major.minor specificity for our base images.

## Blocker(s)

- [ ] XRay Scanning issues

Currently when I am logged into Artifactory it looks like XRay is not functioning and not performing vulnerability scans.

## Work

- [ ] [Scan container images in CI using Trivy](https://github.com/aquasecurity/trivy-action)
- [ ] [Trigger scan in XRay in BCGov Platform](https://docs.developer.gov.bc.ca/image-artifact-management-with-artifactory/#xray-artifact-scanning)

I think the plan is to use Trivy in CI which will attach vulnerability assessments to builds, however we will also trigger XRay to scan the container images so that the BCGov Platform can also be made aware of any security events related to the container images.

**Comment by sylus** [comment]
Hi @CraigClark I can add the Trivy execution step to our pipeline but I won't be able to do the XRay one as that feature I don't think is currently enabled on the BCGov side but it is supposed to be at some point.

Do you want me to add the Trivy execution step in the CI?

Its relatively straightforward.

**Comment by CraigClark** [comment]
@sylus Whatever we need to make this happen:

> BCGov Platform can also be made aware of any security events related to the container images.

**Comment by sylus** [comment]
This has now been actioned using Trivy :)
