### ISSUE TITLE
Add advanced search link to home page

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#440]
## Describe the idea

It may be beneficial to include a hint on the landing page with respect to Search.
Something along the lines of:

"hint: an empty search box returns all records; including a search term narrows the results"

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/e35b4736-8cad-4893-adaa-c12a31c99d44)

## Actions

- [x] On the home page, add an "Advanced search" link under the search box that takes users to the search page. @lkmorlan 
- [x] Style as needed. @CraigClark

**Comment by NicoledeGreef** [comment]
After discussion, it will be better to add an "Advanced search" link under the search box that takes users to the search page with all the facets.

**Comment by CraigClark** [comment]
@lkmorlan I'm going to assign this one to you. I thought this was done in Twig, but it's not. It is a page, `/admin/structure/page_manager/manage/home/page_variant__home-panels_variant-0__content`

We need a link under the search box that says 'advanced search', but only on the home page

**Comment by lkmorlan** [comment]
Adding @CraigClark for styling.

**Comment by CraigClark** [comment]
Style is done

**Comment by NicoledeGreef** [comment]
reviewed in dv14
