### ISSUE TITLE
Add clarity to published/modified dates by including 'record' prefix

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#442]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6509566882

---

## User story

As a user
I want to know what the date in the metadata record applies to
so that I have clarity on what is being documented and how that applies to my work

## Describe the idea
Currently the metadata record dates indicate when it was published or modified but doesn't specify whether these dates apply to the metadata record itself or the data the metadata record is about.
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/6f9c909e-2d0b-4c65-882b-9fa201e380de)

In similar situations this had caused confusion to users - they think the _data_ was published or modified on this date.

## Actions
Prefix the Published and Modified dates with 'Record' to be more explicit and prevent confusion for users.  This would follow in the footsteps of the 'Record type' and 'Record visibility' labels that precede and follow the dates.

Alternatively, reorganize the information so that this linkage of dates to the MR record is more clear.  However, this may cause more change (both in behaviour/expectations and on the systems side) down the road if we choose to add published dates for datasets to the metadata model.

- [x] Hooray! I'm going to be a feature!

**Comment by CraigClark** [comment]
@lkmorlan ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/442-add-clarity-to-published-and-modified-date-fields

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
reviewed in dv14
