### ISSUE TITLE
Report builder updates

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#444]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6519662737

---

- [x] add a "No results" notification on screen
- [x] some way of indicating to users that results are limited to records they have access to (based on visibility)
- [x] Security classification filter is using incorrect taxonomy:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/695cf40a-9d30-44b0-a05a-aef240de19ea)
- [x] #449

**Comment by CraigClark** [comment]
Ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/444-report-builder-updates


>[!NOTE]
> @NicoledeGreef , the links in the access info box are to documentation pages and will only work properly on prod.
> Access info is:
>
> _Please note that results are limited to the metadata records you have access to. Access is determined by your [role](https://dv14.bc.dc.ddev.site/node/70) and the [organization](https://dv14.bc.dc.ddev.site/node/114) you belong to._
>
> No results is:
>
> **No Results Found**
> Sorry, we didn’t find anything that matches your search.

**Comment by lkmorlan** [comment]
Merged
