### ISSUE TITLE
"Metadata record management" screen updates

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#445]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6519677814

---
- [x] add a "No results" notification on screen

**Comment by CraigClark** [comment]
## Updated no results messages

1. on records by security classification chart | _No records have a security classification applied._
2. on records by visibility chart | _No records have a visibility value applied_
3. on most viewed data sets report |   _**No Results Found** Sorry, we didn’t find anything that matches your search._
4. on information management report |   _**No Results Found** Sorry, we didn’t find anything that matches your search._
5.  on information management report |   _**No Results Found** Sorry, we didn’t find anything that matches your search._
6.  on manage records page |   _**No Results Found** Sorry, we didn’t find anything that matches your search._

## Other changes

1. on metrics report page, rename _Most viewed data sets_ to _Most viewed records_

**Comment by CraigClark** [comment]
@lkmorlan ready for review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/445-update-no-results-message-on-views

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
tested in dv14.  "No results" messaging displays as anticipated but should a user still be presented with the "download CSV" link for an empty file?

**Comment by CraigClark** [comment]
Download link is now hidden with css if there are no view results. While it's not the best to hide things with CSS, this approach avoids the need for custom code.

@lkmorlan please review/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/445-remove-csv-download-for-no-results-in-view

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
verified in dev
