### ISSUE TITLE
update Reports documentation to reflect current state

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#446]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6525083772

---
https://cat.data.fin.gov.bc.ca/documentation/reports

a few changes have occurred so the screenshot in the Docs doesn't match the current state

**Comment by NicoledeGreef** [comment]
@craigclark to create replacement image and @NicoledeGreef to swap them in using Media Library

**Comment by CraigClark** [comment]
@NicoledeGreef please review https://cat.data.fin.gov.bc.ca/documentation/reports

**Comment by NicoledeGreef** [comment]
reviewed/edited https://cat.data.fin.gov.bc.ca/documentation/reports
