### ISSUE TITLE
on Edit screen, Section 2, update "Published date"

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#447]
**OP timer**

---
On the Edit screen, "Published date" should be "Record published date" to match the display on the View screen

**Comment by CraigClark** [comment]
@NicoledeGreef Could you please send a link to where you are seeing the discrepancy? 
[here](https://dv14.openplus.ca/node/18/build) and [here](https://dv14.openplus.ca/node/18/edit?display=section_2) I see _Record publish date_

**Comment by NicoledeGreef** [comment]
might have been a caching issue but it's there now.
