### ISSUE TITLE
Report builder not showing/exporting content in the IM classification code column

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#449]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6528068126

---

## Describe the bug
The report builder is not including the IM classification values in the report.
E.g. [https://test.cat.data.fin.gov.bc.ca/melindas-test-dataset](https://test.cat.data.fin.gov.bc.ca/melindas-test-dataset)
has the following classification:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/84a84238-4f05-47bf-b2f1-6471a3506aef)

but the Report builder preview shows it as blank:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/3d6d84b9-f0f3-4958-94bb-f9c1801d89ce)

and it is also blank in the resulting export file:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/f4f9e498-874c-43e6-97b4-6ef248eef101)

## Expected behaviour
The built report show show the values present in the metadata record.

**Comment by NicoledeGreef** [comment]
reviewed in dv14
