### ISSUE TITLE
Where do we store the script for making new cores?

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#451]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6530799629

---

https://github.com/bcgov/MFIN-Data-Catalogue/labels/question

---

## What's your Question?

@NicoledeGreef , Will has a script for making new cores. Where would you like this to be stored?

I don't imagine there is any sensitive info in the scripts, I have asked Will for confirmation.

**Comment by NicoledeGreef** [comment]
@NicoledeGreef to talk to AppOps team to determine where they would want to store this script. target repo bcgov/bcbb-gitops docs or somewhere else?

**Comment by NicoledeGreef** [comment]
Emailed App Ops

**Comment by NicoledeGreef** [comment]
@kardamk  - where would you like this script that Will prepared to be stored?

**Comment by kardamk** [comment]
Hello @NicoledeGreef,

What does the script do for generating new cores?  
Where is it generating the new cores?

I will discuss this with Will in today's meeting to finalize the location of the script.

Thank you!

**Comment by kardamk** [comment]
The script for generating the SOLR core has been placed within tenant-gitops-ea352d repository at tenant-gitops-ea352d/solr-drupal/scripts/deploy.sh by Will.

**Comment by NicoledeGreef** [comment]
Excellent - closing ticket.
