### ISSUE TITLE
Schedule training build

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#452]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6532618660

---

We need to schedule a build to all three environments for the app ops team to run through.

App Ops will do the build in a meeting with Liam. They will share their screen and Liam will walk them through the process.

@NicoledeGreef to organize the meeting.

**Comment by NicoledeGreef** [comment]
Meeting slated for May 8th
