### ISSUE TITLE
update to php 8.2

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#453]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6532634545

---
We need to test locally, then dev-ops to deploy to openshift under WIll's guidance
- [x] set up on dv14 (@lkmorlan)
- [x] arrange a late day meeting between Will and AppOps team (@CraigClark & @NicoledeGreef )

**Comment by NicoledeGreef** [comment]
scheduled for May 10 at 1pm Pacific Time

**Comment by lkmorlan** [comment]
The dv server has been updated to PHP 8.2.

**Comment by NicoledeGreef** [comment]
This was upgrade was migrated through to Production on May 10.
