### ISSUE TITLE
ensure that the search results export is exporting all the fields on a record

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#455]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6533978633

---
Since the search results export was built, we've added a number of attributes so these should all be included in the export. Order should be the same as the node view page with the main content area first followed by the data dictionary, followed by the righthand sidebar content.

- [ ] validate that no fields are exported that the user doesn't have access to (e.g. Visibility, Location, Related docs, etc.)

**Comment by lkmorlan** [comment]
Issue filed when working on this:
https://www.drupal.org/project/views_bulk_operations/issues/3444934

**Comment by NicoledeGreef** [comment]
There are some attributes that did not appear in the search results export files (highlighted yellow):



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/b9a46f16-e115-4954-a3d7-de34b3544eff)

Contact name, Contact email and Personal info would be good inclusions. The others not critical.

**Comment by lkmorlan** [comment]
@NicoledeGreef when I do a download on `dv14` or `dev.cat.data.fin.gov.bc.ca`, I see all the fields that are mentioned as being missing. Can you check again if this is still a problem?

**Comment by NicoledeGreef** [comment]
Reviewed in dv14. 

When logged in as an IDIR user that has the `Catalogue admin` role in the IMB Org:

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/0bdd1271-1911-41e6-9efa-c80425eb1ea1)


When logged in as a non-admin user that has the `Catalogue editor` role in the PTB Org: the results are as above.

When not logged in, I cannot export search results; confirmed that sensitive fields are not displayed when records viewed either.
