### ISSUE TITLE
VBO to change field values fails

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#459]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6554154734

---

## Describe the bug

As an administrator, using the VBO on the content overview page, I cannot change field values.

## To reproduce
Steps to reproduce the behaviour:
1. Go to https://dv14.openplus.ca/admin/content
2. Filter content type _Metadata record_
3. Click the checkbox beside _Title_ to select all metadata records
4. In the VBO at the bottom of the page, select _Modify field values_
5. click _Apply to selected items_
6. on the next screen, select the checkbox beside _Source system_
7. For the _Source system_ value, select `- None -`
8. Click apply
9. See that nothing happens

I get the same failure if I try using this technique to change other field values

## Expected behaviour

When I hit apply, there is a screen that shows me all the changes that will be made, I confirm the selection. There is a progress bar while the changes are applied and then the changes are there. At least that's how I remember this working.

**Comment by lkmorlan** [comment]
This appears to be caused by this bug:

https://www.drupal.org/project/views_bulk_edit/issues/3024419

The patch in comment 57 does not fix it for us.

**Comment by CraigClark** [comment]
Closing. This is a non-critical upstream bug and the issue has been reported.
