### ISSUE TITLE
load test the app with 500 concurrent users

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#461]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6562784412

---
The number of initial anticipated users is fairly low while we populate metadata content but, in a few years, we will have a lot of useful info in it and there may be significant interest in our holdings, generating more concurrent users. 

@sylus noted that the same setup has been load tested using jmeter and is fairly solid. Let's set up a test for up to 500 concurrent users (far more than we’ll need anytime soon).

Question from App Ops: are we going to be integrating jmeter scripts in the Test environment?

**Comment by sylus** [comment]
I only mentioned what we did for a few sites at statscan using jmeter.

I don't think there was mention of actually doing it.

Assigning back to you to get more info and see if priority given the others.
