### ISSUE TITLE
Add docs for working with a data dictionary

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#463]
**OP timer**

---

add content https://cat.data.fin.gov.bc.ca/documentation/managing-data-dictionary

**Comment by CraigClark** [comment]
@NicoledeGreef ready for review here https://cat.data.fin.gov.bc.ca/documentation/managing-data-dictionary

**Comment by NicoledeGreef** [comment]
reviewed and minor revisions made. thank you!
