### ISSUE TITLE
"Unpublish" button is displayed to Manager when a record is already unpublished?

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#465]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6578633388

---

## Describe the bug
Metadata management screen, logged in as a Manager. The presence of the "Unpublish" button seems contradictory.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/a01cdfdb-9eee-4bf3-b808-f40e416623f3)

Other records have different combos of buttons based on the conditions of the user (did they author the MR? what Org membership does the user have? Is the MR published?)

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/386b5760-1a09-48f6-ade5-e209f6a0204b)

Should "Draft" moderation state have the Unpublish button?

**Comment by CraigClark** [comment]
Agree. It can be confusing to users to see a button to do a thing that's done already. If you do try to unpublish an unpublished record it will give you an error message, which is good, but best would be if the button wasn't there at all

**Comment by NicoledeGreef** [comment]
verified in dev
