### ISSUE TITLE
Change the search box text on the home page

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#466]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6578757937

---

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/e3166605-6c8b-4f94-b5f8-891445a67ba8)

- [ ] "Find metadata records" --> "Find metadata records by keyword"
- [ ] consider making the font smaller for the link under the search box

**Comment by CraigClark** [comment]
@NicoledeGreef We can call the links whatever we like, however _Advanced search_ is a common label and people know what it means. Let me know if you would like it changed anyway.

**Comment by CraigClark** [comment]
@NicoledeGreef This looks a lot different since the design update, I'll park this one until you see the changes

**Comment by NicoledeGreef** [comment]
The theming changes have addressed my previous concerns. Closing ticket.
