### ISSUE TITLE
Update data catalogue theme to reflect changes to the BC design system

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#468]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6596231716

---

>[!IMPORTANT]
> Related ticket on base-build theme | <https://github.com/bcgov/bcbb-theme/issues/20>

## DoD
- [ ] in user menu, add icons similar to the mockup
- [ ] on mobile, collapse docs/dashboard/logout/login to icons

## ToDo
Once the theme changes are done, create tickets for the following

- [x] #469

## Mock-up 
[BC Design adjustments.docx](https://github.com/bcgov/bcbb-theme/files/15238999/BC.Design.adjustments.docx)

**Comment by NicoledeGreef** [comment]
tagging with `base build candidate` to ensure we don't lose sight of this work in that context. polling others to confirm ahead of our next bcbb meeting.

**Comment by CraigClark** [comment]
This was done at the same time as base-build adjustments.

DC adjustments are in this branch  https://github.com/bcgov/MFIN-Data-Catalogue/tree/468-update-theme-to-implement-new-bc-design-system

>[!NOTE]
>I couldn't get the background image on BC Data page to load properly in Illustrator for editing. Instead I used a [royalty free image from Pixabay.](https://pixabay.com/vectors/data-chart-graph-finance-business-8041755/)

**Comment by NicoledeGreef** [comment]
Reviewed in dv14. 

Can the whitespace be reduced as shown below?
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/67de7b11-ea96-40fc-8b36-9671acfccfc3)

**Comment by lkmorlan** [comment]
Merged

**Comment by NicoledeGreef** [comment]
reviewed in dv14
