### ISSUE TITLE
change Home in breadcumb to Finance Data Catalogue

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#469]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6605131511

---

Update the breadcrumb so the first item is _Finance Data Catalogue_ instead of home

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/5fe1c144-73cd-4c67-814b-cc263e03fbad)

**Comment by NicoledeGreef** [comment]
reviewed in dv14
