### ISSUE TITLE
Meeting to discuss review of Standard Operating Procedures document

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#47]
## This feature support the following requirements

Meeting to review in-progress Standard Operating Procedures (SOP) document.

## Additional context

A Standard Operating Procedures document is under development to ensure that the CabOps & FINtranet Drupal apps are regularly backed up and restorable through processes outlined in the document.  This ensures that anyone responsible for such operational tasks has the standard document to guide them when needed.

## Definition of done (DoD)
- [x] SOP drafted
- [x] SOP circulated for review
- [ ] meeting to discuss the SOP

@eloynav @CraigClark @lkmorlan @sylus @sangtrinh

**Comment by NicoledeGreef** [comment]
Moved from Sprint 3 to Sprint 4 as the document draft is in progress until at least July 26.

**Comment by NicoledeGreef** [comment]
@eloynav - would you please attach the document to this ticket if you would like to have it reviewed and meet about it?

**Comment by eloynav** [comment]
Sure thing
[Openshift Standard Operating Procedure.docx](https://github.com/bcgov/MFIN-Data-Catalogue/files/13230625/Openshift.Standard.Operating.Procedure.docx)
