### ISSUE TITLE
Revisions tab usability observations

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#470]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6606442785

---
Production users were looking for ways to delete draft revisions that are un-needed. Delete appears to be limited to the Catalogue admin role. We should explore adding the Delete revisions permission to Manager and possibly Editor roles.

Also reported that they figured out the revision comparison bit but feared that no one would scroll down to find the "Compare selected revisions" button. How might we address this?

Ideas: 
- move the button to the top of the list since latest revisions are generally more relevant and proximity would help
- update instructional text indicating the important of scrolling down

- [x] Add the patch that improves accessibility and user experience of the diff page.
- [x] Ensure there is a diff link at the top of the page.

**Comment by CraigClark** [comment]
@NicoledeGreef They shouldn't have to delete old revisions. We have a pruner that does that, see #191. Old drafts should be deleted. Old published records are kept. Forward draft revisions are also kept.

Could you please send a link to the record that has the draft revisions you want to delete? We can check to make sure it is doing what is should.

**Comment by CraigClark** [comment]
There is a [patch](https://www.drupal.org/project/diff/issues/2834253) we we worked on for another project that improves accessibility and user experience of the diff page. We will get that intro the base-build.

@lkmorlan cold you look after that please? 

Also, if this doesn't bring in a compare link at the top, Joel mentioned there is a patch somewhere that does that.

**Comment by NicoledeGreef** [comment]
> @NicoledeGreef They shouldn't have to delete old revisions. We have a pruner that does that, see #191. Old drafts should be deleted. Old published records are kept. Forward draft revisions are also kept.
> 
> Could you please send a link to the record that has the draft revisions you want to delete? We can check to make sure it is doing what is should.

Editor (Mike) created this record: https://cat.data.fin.gov.bc.ca/canadian-vehicle-specifications
Manager (Christa)  added a couple of Draft revisions.  This was Christa's view of the revisions:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/5d7c7da8-ba75-46ba-8b01-d37807ded3cf)

This was Mike's view of the same; you can see that he drafted and published after Christa's last draft. They couldn't get rid of the Draft revisions that weren't needed.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/b476a1a4-dc67-4640-bb82-18cbb754b7b3)

I guess the pruner eventually takes care of this. How often?
Please ensure the auto-pruning activity is mentioned in the docs and that the same doc has updated screenshots once the UI changes are in place: https://cat.data.fin.gov.bc.ca/documentation/working-revisions

**Comment by NicoledeGreef** [comment]
Instructional text, button addition and column headers for radio buttons verified in dev.

**Comment by NicoledeGreef** [comment]
@lkmorlan  - we are seeing a bunch of old drafts in Revisions in Prod, for example: https://cat.data.fin.gov.bc.ca/node/188/revisions

Expected behaviour as per #191 : old drafts would periodically be removed by the pruner

**Comment by lkmorlan** [comment]
@NicoledeGreef I have re-opened #191 to fix the pruner issue. Please review the fixes in this ticket.

**Comment by NicoledeGreef** [comment]
reviewed in prod
