### ISSUE TITLE
Add placeholder text to search fields

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#471]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6613668802

---

In the search input in the header, on the home page and the search results page, add place holder text `Search Finance Data Catalogue`

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/3c52b164-e1dd-4f44-8add-9afc5b21070a)

**Comment by NicoledeGreef** [comment]
reviewed in prod
