### ISSUE TITLE
Users that aren't logged in get "page not found"

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#472]
**OP timer**

---
https://dev.cat.data.fin.gov.bc.ca/node/37/revisions is a valid link that was sent to a user that doesn't usually work in dev. 

The user received a "Page not found". In such circumstances, how might be make it more obvious that they should login to see the content rather than simply stating "page not found"?

**Comment by CraigClark** [comment]
@NicoledeGreef 


That depends on how often you think you will need to send links to revisions. There is a [module called authlink](https://www.drupal.org/project/node_authlink) that can be used where editors can create a link to a revision.  We have a client who uses this to send approval links to managers who do not want to have to log into a site to see a thing. The downside of this is that a) you have to create the link and b) once the link is crated, anyone with that link can access the revision. Whether that's a problem or not is a business decision.

The other option is, right now, 403 (access denied) errors forward to 404 (page not found). This is a common practice and falls into the security by obscurity realm. The idea being, if I have bad intentions, and I land on a 403, I know something is there and I keep hammering away at it until I get in.  With a 404, I have no idea there is actually content there. If you use 403, you can have a message on the page that the person has to log in.

If you occasionally have to send revision links, or only a small group of people need access to revision, I would add a reminder in the email, that's the easiest. 

> Hey Nicole, can you please take a look at https://example.com? You will need to log in to see it.

**Comment by NicoledeGreef** [comment]
Thanks for the insights. For now we'll call this one an education issue.  Because the record's visibility is set to Public, it's no problem to distribute the link for it:

[https://dev.cat.data.fin.gov.bc.ca/node/37](https://dev.cat.data.fin.gov.bc.ca/node/37)
or https://dev.cat.data.fin.gov.bc.ca/node/37

but Catalogue users should be made aware that Build/Edit/Revisions are only available to logged in users with permissions that allow them to access those things.
