### ISSUE TITLE
Make `field_series` be multi-select

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#473]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6613876319

---

The business notes that there is a list of Series values for review within their team.  Going through it they are finding some things could fit under multiple buckets. They are trying to figure out if they can/should raise the grain or can we allow for multiple selections.

- [x] set max term level to 1 on the vocabulary
- [x] allow for selection of multiple terms
- [x] use auto complete widget
- [x] layout on node view see [comment below](#issuecomment-2104580580) for what it should look like.

**Comment by CraigClark** [comment]
@NicoledeGreef 
Sure, we can do that.

One thing that would help is a rough idea how many items you think will end up in the taxonomy for series. This is not a technical limitation, it helps us choose the best formatter for the input form.

- up to eight items we use checkboxes.
- up to twenty a select list
- more than twenty auto-complete
- if there are children, a hierarchical select like we use for info schedule

For the display on the record view, I think we should use the same layout we have for visibility. The label on the left, then a list of right aligned items beside it if there is more than one item. If there is only one item, this is not a list and displays the same as it does now.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/edd38809-2f5d-46f9-bb4c-089025c023e5)

>[!NOTE]
> _Series_ should not have the circle icon before it, that's there because I cut/paste the html from _visibility_ to make the prototype

## Questions

1. Currently the series vocabulary allows for any term depth. Should this be set to 1?
2. How many values do you anticipate being in the _Series_ vocabulary?


## To proceed

If you want to go ahead with this, please add to sprint and assign to Liam.

**Comment by ChristaBull** [comment]
@NicoledeGreef  some thoughts for you.

**1. Currently the series vocabulary allows for any term depth. Should this be set to 1?**
Yes, I think it should be set to 1.  While there is the potential for hierarchies we're trying to land on a set of higher level groupings.

**2. How many values do you anticipate being in the Series vocabulary?**
It's probably going to be a longer list.  At the moment we have at least 30 items in our draft but we're still trying to determine where we want to set the groupings so they're meaningful but not too granular.  My team is meeting to discuss the draft list this afternoon.

Below is a list of things we currently have identified:

- System Logs
- BC Assessment or Property Assessment
- Property Transfer Tax
- Annual property tax OR Rural Property Tax, School Tax and Police Tax
- Property Tax Deferment
- Flipping Tax
- Speculation and Vacancy Tax
- Land Titles
- Home Owner Grant
- Income Tax Credits
- Provincial Sales Tax
- Pay Transparency
- Motor Fuel Tax
- Carbon tax
- Employer Health Tax
- Tobacco Tax
- Oil and Gas Royalty and Tax
- Forestry Tax OR Stumpage Fees and Logging Tax
- Insurance Premium Tax
- Income Tax OR Person Income Tax (T1), Corporation Income Tax (T2), Statement of Remuneration (T4), etc.
- Stats
  - Vehicles
  - Stats Canada Data (e.g. Labour Force Survey, Census)
  - Local Govt Stats
- Money Services Businesses
- Family Benefit System (FBS)
- Geocode/location
- Covid Programs OR IEI, RBP, EBW, PRME
- MRDT
- CSAIR
- Beneficial Ownership OR Land Owner Transparency Registry, Business Transparency Registry, etc.
- Corporate Registry

**Comment by NicoledeGreef** [comment]
@CraigClark please see comment above from @ChristaBull

**Comment by CraigClark** [comment]
@NicoledeGreef We will go with auto-complete for this. The list is a bit long for a select list.

In the example above, stats has children, which would imply at least two levels. For now we can restrict the vocabulary to 1 level, so you will need to do something lile `Stats - Vehicles` for the term name.

If you want deeper levels in the future, an admin can change the depth on the vocabulary and change the input widget to SHS.

**Comment by NicoledeGreef** [comment]
reviewed in dv14.
