### ISSUE TITLE
document pruner cron in Wiki and user documentation

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#476]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6630153730

---
- [ ] FYI in the Documentation (@CraigClark )
- [x] implementation specifics in the Wiki

**Comment by lkmorlan** [comment]
Added [pruner documentation](/bcgov/MFIN-Data-Catalogue/wiki/Revision-pruner).

**Comment by CraigClark** [comment]
I added a reference to the wiki docs in the [user documentation](https://cat.data.fin.gov.bc.ca/documentation/working-revisions).

**Comment by CraigClark** [comment]
@NicoledeGreef please review

**Comment by NicoledeGreef** [comment]
Looking at: https://cat.data.fin.gov.bc.ca/documentation/working-revisions

- Please update the screen shots to reflect current Revisions tab (changes were made as part of #470).


Looking at: https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Revision-pruner

- Please add a note as to what time of day does the pruner cron job run.

**Comment by CraigClark** [comment]
@NicoledeGreef I have updated the wiki.

For the screenshots, I created a new task, see #486
