### ISSUE TITLE
Create agenda for code walk-through meeting

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#478]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6648400695

---

On May 22, there is a code walk-through scheduled.  This task it to come up with a list of items to go through.

- The documentation is written with the assumption that developers will be familiar with Drupal development.
- Code is documented with code comments.
- `bcbb`
	- Wiki: https://github.com/bcgov/bcbb/wiki
	- `composer.json`
	- Sub-modules
	- Test trait and base classes
- `bcbb_theme`
- `bcbb-template`
	- `composer.json`
- `MFIN-Data-Catalogue`
	- Wiki: https://github.com/bcgov/MFIN-Data-Catalogue/wiki
	- `README.md`
	- `composer.json`, `composer.lock`
	- `config`
	- Automated tests, `phpunit.xml`; actual tests in `bc_dc`
	- `dc_theme`, sub-theme of `bcbb_theme`: Theme for data catalogue.
	- `bc_dc`: Custom functionality for data catalogue.

**Comment by NicoledeGreef** [comment]
meeting held, video captured and posted to Teams channel.
