### ISSUE TITLE
Local tasks tabs missing when I compare revisions

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#479]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6648994893

---

## Describe the bug

When I compare two revisions, I lose the local task tabs near the top of the page. This means there is no obvious way to get back to the page I was on unless I use the browser's back buttom

## To reproduce
Steps to reproduce the behaviour:
1. Go to any record
2. Click on the revisions tab
3. Select two revisions
4. compare revisions
5. See that the local tasks tabs are no longer available at  the top of the page.

## Expected behaviour
When I am comparing two revisions, I still see the local tasks at the top of the page and the _Revisions_ tab is open.

## Additional context
We can check RSAMS to see how this is done.

**Comment by joel-osc** [comment]
https://www.drupal.org/project/drupal/issues/2885278

**Comment by lkmorlan** [comment]
@joel-osc this issue is about the diff page, not viewing a revision. 

There is an issue for this:
https://www.drupal.org/project/diff/issues/3169729

**Comment by NicoledeGreef** [comment]
reviewed in dv14
