### ISSUE TITLE
Date range picker for SearchAPI Facets

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#48]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

https://openplus.monday.com/boards/4092908516/pulses/4688497276

---

## User story

As a anonymous user I want to select a date range for my last modified facet so that I can find all data sets that were modified, say, between January 1 2020 and January 1 2021 (for example)

## Describe the idea

Use the date range slider module maybe?  These might not do what we want but there's some possible modules to investigate:

https://www.drupal.org/project/facets_date_range_picker
https://www.drupal.org/project/facets_date_range
https://www.drupal.org/project/facets_range_input

and looking at this issue:
https://www.drupal.org/project/facets/issues/3187163
https://www.drupal.org/project/facets/issues/3195236
https://www.drupal.org/project/facets/issues/3216756

It might be that facets already supports facet range slider (which I had already seen when I was configuring it), so it might not even need a module for support.

What we're looking for is this: 
https://github.com/DSpace/DSpace/issues/8418

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
CC to investigate and determine if this exists (is feasible).  If not, we'll close it.

**Comment by lkmorlan** [comment]
All that appears to exist currently is using `facets_date_range` to create from and to controls, no slider for dates.

**Comment by NicoledeGreef** [comment]
Thanks for investigating!
