### ISSUE TITLE
ToDo's out of DevOps Q&A meetings

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#482]
**OP timer**

---

The following tasks are from notes taken in the two Q&A sessions with Will.

These are tasks we agreed to do, but I'm not sure if they are all Will or not. I'll assign @sylus and @chrislaick .

Chris, I would like to assume these are Will unless they have your name beside them. Could you please add your name beside items (if any) you will be looking after?

1. - [x] Allow to configure the backup days to keep from hardcoded
2. - [ ] #485 assigned to @lkmorlan 
3. - [x] Set the maintenance mode so is hardcoded during updatedb process
4. - [x] Proper inheritance for postgres cluster resources into values.yaml
5. - [x] Add Drupal 11 configuration as a [Merge Request](https://github.com/bcgov-c/tenant-gitops-ea352d/pull/4)
6. - [x] Push the solr configuration to the private tenants repo
7. - [x] Chris to send Will the HA proxy yaml for the router from another config using IP cidr block egress
8. - [x] Will to check into the key job failed for chris
9. - [x] Document the the backup / restore with PGO process and give the dev/devOps folks a little page for the 24th
10. - [x] Do a backup / restore from an hour before meeting and walk through the restore (only got to discuss)
11. - [x] Collaboratively go through a helm dep chart upgrade such as solr / varnish as part of dev walkthrough
12. - [ ] Answer [Chris's question about resource allocation](https://github.com/bcgov/MFIN-Data-Catalogue/issues/481#issuecomment-2130403461)

## Assigned to @sylus 

1. - [x] #480 
3. - [x] #450 
4. - [x] #355 
5. - [x] #44 
6. - [x] #43 
7. - [x] #461 
8. - [x] **update docs** |  https://github.com/bcgov/bcbb-gitops-docs/issues/2
9.  - [x] **update docs** | https://github.com/bcgov/bcbb-gitops-docs/issues/3
10. - [x] **update docs** | https://github.com/bcgov/bcbb-gitops-docs/issues/4
11. - [x] ~~Please provide drush command for exporting postgres DB for use in things like DDEV~~
12. - [x] Create netpol example to allow IP address ranges | https://github.com/bcgov-c/tenant-gitops-ea352d/pull/8

**Comment by CraigClark** [comment]
@NicoledeGreef is 11 the deployment that AppOps did with Liam?

**Comment by sylus** [comment]
The solr core's configuration I pushed to the tenants repo since that is where solr is installed think made the most sense.

**Comment by sylus** [comment]
I haven't been able to find any information about that failed job but I'll check again tomorrow.

**Comment by sylus** [comment]
@CraigClark so there is no easy or clean way to print a custom message when exec'ing into a container.

Is it possible that when drush status is run we get @lkmorlan to add a custom message prepended to the output?

Perhaps using pre-command instead of alter?

https://github.com/drush-ops/example-drush-extension/blob/78f98a333a7d12460329ba2dbb54e66b36188b57/ExampleStatusFieldHook.php#L51

The custom message to prepend:

```
    # Reminder to execute the following command
    source /vault/secrets/secrets.env
```

**Comment by chrislaick** [comment]
@sylus I've provided the route example with IP address ranges to allow.

**Comment by chrislaick** [comment]
> I haven't been able to find any information about that failed job but I'll check again tomorrow.

@sylus This might be old, but the Alerts page here is showing which Job has failed:
https://console.apps.silver.devops.gov.bc.ca/dev-monitoring/ns/ea352d-prod/alerts

And this is the offending Job:
https://console.apps.silver.devops.gov.bc.ca/k8s/ns/ea352d-prod/jobs/mfin-data-catalogue-drupal-cron-28487625
Reason: BackoffLimitExceeded

**Comment by CraigClark** [comment]
> Please provide drush command for exporting postgres DB for use in things like DDEV

There isn't a drush command for this. However we did meet with Chris and Dan yesterday and walked them through the process of getting a DB off prod and importing it locally on DDEV. There is a recording of this session and @chrislaick is going to document the commands in the [wiki for local development](https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Local-development)

**Comment by CraigClark** [comment]
> Collaboratively go through a helm dep chart upgrade such as solr / varnish as part of dev walkthrough


Session completed for updating SOLR on May 24

**Comment by CraigClark** [comment]
> Do a backup / restore from an hour before meeting and walk through the restore

@NicoledeGreef I don't think we are going to have time for this.

**Comment by sylus** [comment]
> > Do a backup / restore from an hour before meeting and walk through the restore
> 
> @NicoledeGreef I don't think we are going to have time for this.

@CraigClark I did go over it verbally in one of the meetings but in addition I added some quick notes in my M.R. for the bcbb-gitops-docs repo.

https://github.com/bcgov/bcbb-gitops-docs/pull/5/files#diff-d5950c0d6bb7ac4b4e8ee8223b7a1e466d851d8b8772ae703797d5f95a0c4723
