### ISSUE TITLE
Taxonomy Manager failing on dv14

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#483]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6689772491

---
This was noticed when trying to edit a single Series value using the Taxonomy Manager.

To replicate:
- IDIR user is a Catalogue user and Catalogue admin
- IDIR user is a member of Information Management Branch Org
- go to dv14
- go to Taxonomy Manager
- click on Series
- click on a value and edit the Name or Description
- click Save
- see error

When attempted in dv14, a stack trace occurs.

The same edit is successful when using OTB Drupal Taxonomy interface.

 It seems to be an issue in dev, test, and prod which result in:

**Error 500 Internal Server Error**
Internal Server Error

Guru Meditation:
XID: 886503

Varnish cache server

Question: is this something that can be included in the automated tests?

**Comment by lkmorlan** [comment]
This is caused by a bug in `taxonomy_manager`. I reported and fixed it here:

https://www.drupal.org/project/taxonomy_manager/issues/3449448

**Comment by NicoledeGreef** [comment]
verified in dv14
