### ISSUE TITLE
show counts for multi-select items on Build screen

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#484]
**OP timer**

---
As discussed with respect to #473, for the Build screen of an asset we need to simply list the number of items selected via multi-select fields instead of displaying the items selected.

- [x] Series
- [x] Assets used
- [x] Related documents
- [x] Data dictionary columns

**Comment by danhgov** [comment]
I found a couple of commits to model this solution after:

- commit 4e3972dcd9, re Related Documents ("Issue #295: Set permissions on related docs field, theme build section for related docs"). 
- commit 1e0f48f3bc4, re Data Dictionary Columns ("Issue #198: Display columns as count", from Nov 8)

I see that in the latter of these two, @lkmorlan modified the test-code to go with it. I am going to skip that step for now, given that I haven't yet figured out how to run the tests, and I'd want to make sure that any test code I wrote actually passed before committing it here.

**Comment by danhgov** [comment]
@NicoledeGreef, on this project, do we generally merge our own pull-requests? I'd kinda rather that @lkmorlan look it over, first, as I'm new here.

The PR is at https://github.com/bcgov/MFIN-Data-Catalogue/pull/491 (I'm sure github must link this automatically, but I can't see it anywhere.)

**Comment by NicoledeGreef** [comment]
Reviewed in dv14.
