### ISSUE TITLE
Attempt to display the motd, ensure it's displayed to the end user and make that a PR

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#485]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6696698787

---

This should be a PR

This is a copy of [this comment](https://github.com/bcgov/MFIN-Data-Catalogue/issues/482#issuecomment-2126155866).

There is no easy or clean way to print a custom message when exec'ing into a container.

Is it possible that when drush status is run we get @lkmorlan to add a custom message prepended to the output?

Perhaps using pre-command instead of alter?

https://github.com/drush-ops/example-drush-extension/blob/78f98a333a7d12460329ba2dbb54e66b36188b57/ExampleStatusFieldHook.php#L51

The custom message to prepend:

```
    # Reminder to execute the following command
    source /vault/secrets/secrets.env
```

**Comment by lkmorlan** [comment]
Issue opened in the process of working on this:
https://github.com/drush-ops/drush/issues/6014

**Comment by CraigClark** [comment]
passed. You can see this when you run `drush status`



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/15035354-390a-4d06-8e88-f90d8b1e29b2)
