### ISSUE TITLE
Update documentation screenshots

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#486]
**OP timer**

---

With the theme and feature changes, several screenshots are no longer relevant. 

this task is to go through the documentation pages and update screenshots to reflect theme and functionality changes.

>[!IMPORTANT]
>Do not capture header and footer unless it is needed for whatever is being documented

- [x] https://cat.data.fin.gov.bc.ca/documentation/dashboard-overview
- [x] https://cat.data.fin.gov.bc.ca/documentation/reports
- [x] https://cat.data.fin.gov.bc.ca/documentation/bookmarks-and-update-notifications
- [x] https://cat.data.fin.gov.bc.ca/documentation/saving-searches
- [x] https://cat.data.fin.gov.bc.ca/documentation/downloading-search-results
- [x] https://cat.data.fin.gov.bc.ca/documentation/creating-metadata-record
- [x] https://cat.data.fin.gov.bc.ca/documentation/edit-unpublish-or-delete-existing-record
- [x] https://cat.data.fin.gov.bc.ca/documentation/review-interval
- [x] https://cat.data.fin.gov.bc.ca/documentation/working-revisions
- [x] https://cat.data.fin.gov.bc.ca/documentation/managing-documentation
- [x] https://cat.data.fin.gov.bc.ca/documentation/managing-content-home-page

**Comment by CraigClark** [comment]
Assigned to @NicoledeGreef to review

**Comment by NicoledeGreef** [comment]
List to review in Prod:
- [x] https://cat.data.fin.gov.bc.ca/documentation/dashboard-overview
- [x]  https://cat.data.fin.gov.bc.ca/documentation/reports
- [x]  https://cat.data.fin.gov.bc.ca/documentation/bookmarks-and-update-notifications
- [x]  https://cat.data.fin.gov.bc.ca/documentation/saving-searches
- [x]  https://cat.data.fin.gov.bc.ca/documentation/downloading-search-results
- [x]  https://cat.data.fin.gov.bc.ca/documentation/creating-metadata-record
- [x]  https://cat.data.fin.gov.bc.ca/documentation/edit-unpublish-or-delete-existing-record
- [x]  https://cat.data.fin.gov.bc.ca/documentation/review-interval
- [x]  https://cat.data.fin.gov.bc.ca/documentation/working-revisions
- [x]  https://cat.data.fin.gov.bc.ca/documentation/managing-documentation
- [x]  https://cat.data.fin.gov.bc.ca/documentation/managing-content-home-page

**Comment by NicoledeGreef** [comment]
**Notes:**
https://cat.data.fin.gov.bc.ca/documentation/dashboard-overview 
_there is a placeholder "[ ADD INTERNAL LINK | content manager roles ]"_

May be related to #488 ? @CraigClark

**Comment by CraigClark** [comment]
@NicoledeGreef I fixed the link on the [dashboard overview(https://cat.data.fin.gov.bc.ca/documentation/dashboard-overview) and Finished #488

**Comment by CraigClark** [comment]
@NicoledeGreef to review
