### ISSUE TITLE
complete this documentation (says "Incomplete")

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#488]
**OP timer**

---
https://cat.data.fin.gov.bc.ca/node/9

is linked to from https://cat.data.fin.gov.bc.ca/documentation/edit-unpublish-or-delete-existing-record

**Comment by CraigClark** [comment]
@NicoledeGreef ready for review https://cat.data.fin.gov.bc.ca/documentation/permissions

**Comment by CraigClark** [comment]
@NicoledeGreef to review

**Comment by NicoledeGreef** [comment]
"The settings for how Organization members interact with metadata records are **content**, and therefore are not tracked by version control."

Isn't all content tracked by version control in Drupal? I'm wondering if it is more accurate to say "The settings for how Organization members interact with metadata records are **not content**, and therefore are not tracked by version control."

**Comment by NicoledeGreef** [comment]
altered to reference config sync as opposed to version control.
