### ISSUE TITLE
implement Sysdig in the Openshift project

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#495]
Add Sysdig so we can have monitoring and alerts.

**Comment by chrislaick** [comment]
@NicoledeGreef Sysdig setup is complete with custom PromQL queries for our containers. 

1. Login to https://app.sysdigcloud.com/api/oauth/openid/bcdevops
2. Select a Dashboard under My Dashboards

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/99423089/4e4004ca-9a50-46d5-a2a4-bf4645ad55ab)
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/99423089/196af916-e8e2-4908-9561-e460fba2e427)

**Comment by chrislaick** [comment]
At the moment, only the following users have access:

- Chris Lai
- Dan Howard
- Nicole DeGreef

New users will need to be added via OC command line to the sysdig-team object.

**Comment by chrislaick** [comment]
Assigning to @kardamk to setup Sysdig alerts. He will take a look at how I've configured the other alerts in a1a681 and perhaps configure them similarly.

**Comment by kardamk** [comment]
Hi @chrislaick ,

I have added 2 more Sysdig alerts to our namespace ea352d. 

1. For container restarting within a POD for all the workloads
2. When a container is terminated with an error for all the workloads

Do let me know what other alerts are we interested in to be set in place for MFIN data catalogue.

**Comment by chrislaick** [comment]
Hi @kardamk,

Could you create some alerts for PVCs nearing full?

**Comment by kardamk** [comment]
Hi @chrislaick,

We have an alert in place for PVC's when they are more than 90% full.

**Comment by chrislaick** [comment]
This is completed. There are 6 alerts in Sysdig that have been setup by @kardamk. Thanks!
