### ISSUE TITLE
Establish S3 object storage bucket

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#506]
Location for storage of DB image needed; I will request S3 object storage. I surmise that it will not be in place before June.

_Originally posted by @NicoledeGreef in https://github.com/bcgov/MFIN-Data-Catalogue/issues/43#issuecomment-2133882044_

**Comment by NicoledeGreef** [comment]
Service Account request: SRF-4690 (MySC REQ0537377): 
Object Storage request: SRF-4691

**Comment by NicoledeGreef** [comment]
SRF-4690 (MySC REQ0537377) has been fulfilled. To whom should I send the temporary password? @kardamk @chrislaick it relates to the need identified at: https://github.com/bcgov/MFIN-Data-Catalogue/issues/43#issuecomment-2127944457

**Comment by chrislaick** [comment]
@NicoledeGreef We can store the temporary password in Vault for safekeeping. However, I'm unsure of what to do next as I've never implemented S3 object storage.

**Comment by NicoledeGreef** [comment]
The Object Storage request itself has not yet been actioned, only the Service Account to be used with it has been fulfilled. I will follow up via [SRF-4691](https://fincsp.atlassian.net/servicedesk/customer/portal/7/SRF-4691)

**Comment by NicoledeGreef** [comment]
Credentials sent to @kardamk via email; also added him to [SRF-4691](https://fincsp.atlassian.net/servicedesk/customer/portal/7/SRF-4691)

**Comment by NicoledeGreef** [comment]
S3 Object Storage particulars sent to @kardamk who will look into what needs to be done to fulfill [#43 ](https://github.com/bcgov/MFIN-Data-Catalogue/issues/43#issuecomment-2127944457). Closing this ticket and tagging #43 with current sprint label.
