### ISSUE TITLE
Documentation for local development environment

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#51]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4708101094

---

## This feature support the following requirements

[IMB training and support](https://openplus.monday.com/boards/3958997205/pulses/4658902260)

## Additional context

Prior to #46, prepare documentation on using ddev locally to manage local development for the  data catalogue. documentation will include:

1. customization to ddev required to emulate the production environment.
2. instructions on how to set up the DC project locally
3. how to properly commit local dev work to the repo

## Definition of done (DoD)
- [ ] ddev documentation is included in the BC data catalogue wiki
- [ ] any recipes for working locally

**Comment by CraigClark** [comment]
@NicoledeGreef @chrislaick here are is the first iteration of the local dev docs. This is what I'll be talking about on Tuesday.

see https://github.com/bcgov/bcbb/wiki/Local-development

To do:

- [x] @lkmorlan to review
- [x] @chrislaick  to review
- [x] write a set of docs and recipes for working locally with the data catalogue specifically.

**Comment by CraigClark** [comment]
Data catalogue specific docs are here https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Local-development

They need a review by @lkmorlan , then @chrislaick

**Comment by CraigClark** [comment]
@NicoledeGreef This is ready for @chrislaick 's review.
Base build  docs are here <https://github.com/bcgov/bcbb/wiki/Local-development> and data catalogue specific are here <https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Local-development>

**Comment by NicoledeGreef** [comment]
@chrislaick  - can you please review the bcbb documentation re: local development at your earliest availability?

**Comment by chrislaick** [comment]
@NicoledeGreef Sorry for the delay on this. I've read the documentation and it all looks good.
