### ISSUE TITLE
GDX Analytics not capturing traffic?

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#519]
Visited https://intranet.qa.gov.bc.ca/analytics/finance-data-catalogue

There appears to be no data for the last 7 days (default time frame) even though the Finance Data Catalogue was used to edit & publish metadata in that time,

If I expand the time frame to the last month I get results but not since June 11:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/dacc4df5-fa0f-447d-9ade-e00c794675fe)

**Comment by chrislaick** [comment]
@NicoledeGreef I don't have access to the GDX Analytics dashboard, so this would be a little hard for me to troubleshoot. I will reach out to the GDX Analytics team with a support request. Do you mind if I also put in a request to take one of the seats for the GDX Analytics dashboard?

**Comment by NicoledeGreef** [comment]
Thanks @chrislaick. I think you should definitely have a seat.

**Comment by chrislaick** [comment]
Hi @NicoledeGreef. I just got added to the dashboard and GDX is looking into the analytics.

**Comment by chrislaick** [comment]
The issue here is that the GDX Analytics collector URL got changed on a recent deployment from the PROD pipeline to the TEST pipeline. I'll be creating a new PR to address this with config split, so we can have different values for their respective environments.

**Comment by chrislaick** [comment]
Deployed to PROD. Data is showing up again on the GDX Analytics dashboard, including my test searches. Looks like this is done.

**Comment by NicoledeGreef** [comment]
Thank you, @chrislaick
