### ISSUE TITLE
inventory documentation for references to Build which have now changed to Edit/Modify

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#536]
A quick (case insensitive) search of the Documentation for the word "build" revealed numerous references to:

- "build view" (50+ matches in 50 results)
- "build button" (1 match in 2 results)
- "build page" (6+ matches in 6 results)
- "build tab" (2+ matches in 2 results)

For many of the results that match there are likely screenshots to be updated. 
This example has two screenshots that have references to "Build" which have recently changed to "Edit": https://cat.data.fin.gov.bc.ca/documentation/edit-unpublish-or-delete-existing-record

The good news is that the 50 matches in 50 results don't have screen shots - they just require update from "build view" to "edit view" in the text.

There will be gaps in this analysis but it's a good place to start. A final check over can be done by clicking through the Book pages
Example of a page with no text reference to "build" but that contains one or more screenshots with "Build" in it:
https://cat.data.fin.gov.bc.ca/documentation/working-revisions

Lastly, some of the screenshots are simple and some contain markup to assist the user. We should make a list of the pages that contain one or more screenshots with markup. We can either request assistance in generating updated ones or determine the tools we need to DIY.

**Comment by david-fong-bc** [comment]
Here's what I found of references in screenshots:
- [creating-metadata-record](https://cat.data.fin.gov.bc.ca/documentation/creating-metadata-record)
  - "Getting to the Build page": [draft-mr-table-showing-build-button.png](https://cat.data.fin.gov.bc.ca/sites/default/files/styles/max_1300x1300/public/2024-05/draft-mr-table-showing-build-button.png)
  - "Build page overview": [build-page-overview.png](https://cat.data.fin.gov.bc.ca/sites/default/files/styles/max_1300x1300/public/2024-05/build-page-overview.png) For this one, also update the text under the image to say "(not shown)" like it currently does for the "Current published" tab for any tabs that are not shown in the new screenshot.
- [edit-unpublish-or-delete-existing-record](https://cat.data.fin.gov.bc.ca/documentation/edit-unpublish-or-delete-existing-record)
  - "Edit a metadata record": [manage-tab.png](https://cat.data.fin.gov.bc.ca/sites/default/files/styles/max_1300x1300/public/2024-05/manage-tab.png)
  - "Alternate ways to build, unpublish, or delete a record": [node-tabs.png](https://cat.data.fin.gov.bc.ca/sites/default/files/styles/max_1300x1300/public/2024-05/node-tabs.png)
- [review-interval](https://cat.data.fin.gov.bc.ca/documentation/review-interval)
  - "How do I use this feature? 5.": [click-this-is-a-full-review.png](https://cat.data.fin.gov.bc.ca/sites/default/files/styles/max_1300x1300/public/2024-05/click-this-is-a-full-review.png)
- [working-revisions](https://cat.data.fin.gov.bc.ca/documentation/working-revisions)
  - "Permissions": [revisions-tab.png](https://cat.data.fin.gov.bc.ca/sites/default/files/styles/max_1300x1300/public/2024-05/revisions-tab.png)
  - "The revision interface": [revisions-page.png](https://cat.data.fin.gov.bc.ca/sites/default/files/styles/max_1300x1300/public/2024-05/revisions-page.png)

For textual, non-screenshot references, I found it helpful to open the "Printer-friendly version" of each of the four top-level documentation nodes and use my browser's `ctrl+f`.

**Comment by david-fong-bc** [comment]
I'm currently going through the textual, non-screenshot instances of "build" in the documentation and updating them. Here is the update mapping that Nicole and I made:

- “[Build a metadata record](https://cat.data.fin.gov.bc.ca/documentation/creating-metadata-record#build-a-metadata-record)” -> “Manage or view a metadata record” 
- “Build page” -> “Metadata record overview page” 
  - [Example of previous usage](https://cat.data.fin.gov.bc.ca/documentation/creating-metadata-record#build-a-metadata-record): “Build page overview: The Build page is like a command centre for a metadata record. You can add or edit content, view draft, published and previously published versions, and publish your record.”
  - "Metadata record overview page" is a bit of a mouthful, but Nicole and I agreed that it felt appropriate. We wanted to have something that didn't seem to imply that the page was only for making changes such as editing/publishing/unpublishing/deleting, so we avoided phrases like "build" / "manage". Of course, if we find different wording that works better, we can always change this.
- “Build tab” -> “Edit tab” 
- “Build button” -> “Edit button” 
- “Build sections” -> “Edit sections” 
- “Alternate ways to build, unpublish, or delete a record” -> “Alternate ways to edit, unpublish, or delete a record” 
- “Build view” -> “Edit view”

Some additional items related to "edit/modify":

- https://cat.data.fin.gov.bc.ca/documentation/creating-metadata-record 
  - “Click the Edit button in a section to edit it.” -> “Click the Modify button in a section to edit it.” 
- https://cat.data.fin.gov.bc.ca/documentation/managing-data-dictionary 
  - “Next to Section 6: Data dictionary, click edit.” -> “Next to Section 6: Data dictionary, click Modify.” (multiple occurrences) 
- https://cat.data.fin.gov.bc.ca/documentation/review-interval 
  - “Click Edit beside beside Section 2: Description” -> “Click Modify beside Section 2: Description”

**Comment by david-fong-bc** [comment]
I have finished making the changes I described in my previous comment. [The remaining instances of the word "build"](https://cat.data.fin.gov.bc.ca/documentation/search?search_api_fulltext=build) are for a different sense of the word.

**Comment by NicoledeGreef** [comment]
Thanks @david-fong-bc 
Closing this one as we have the screenshot updates covered in #568
