### ISSUE TITLE
Review and assess vulnerability reported in Vulnerability Notifications 09/10/2024

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#538]
Vulnerability and Risk Management (CITZ) publishes an email newsletter of vulnerabilities and Drupal was on the list for Sept 10, 2024.

https://www.drupal.org/sa-contrib-2024-036

**Comment by chrislaick** [comment]
The vulnerability pertains to the paragraphs_table module, which we aren't using in MFIN Data Catalogue. We are using paragraphs and paragraphs_features, which are unaffected by this vulnerability notice.

**Comment by NicoledeGreef** [comment]
Thanks @chrislaick
