### ISSUE TITLE
Iterate on the MFIN Catalogue Content Architecture document

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#54]
The [MFIN Catalogue Content Architecture document](https://docs.google.com/document/d/1Uv06o_cJOmSSZrAXJza-LyexrbCRAkTS/edit) could be updated.

There is more info available about Unique Identifier, for example, and I think we could supply better taxonomic example values in some cases.

Note: one cannot edit this document (including comment) unless logged in with a Google account.

---

## User story

As a Product Owner I want to evolve the MFIN Catalogue Content Architecture document so that it serves as a solid point of reference for all parties involved in the product's development so that we can implement a baseline in the MVP and iterate from there.

## Actions

- [ ] Meeting (internal or internal + OpenPlus?)

**Comment by NicoledeGreef** [comment]
dependency on #93

**Comment by CraigClark** [comment]
@NicoledeGreef I have exported this to Word and uploaded it to the BC MFIN SharePoint site for the data catalogue project. This is now the authoritative source for this doc, see <https://bcgov.sharepoint.com/:w:/t/06981/EX9azddFuKJMnIgqF_6Hsn8BYirY2HkQfqGk1qGRFy301Q?e=fpfxaI>.

I have noted on our Google doc that it is now a legacy document.

People with the appropriate credentials at BC can now edit and comment on the doc

**Comment by NicoledeGreef** [comment]
i turned on tracking (i made a few minor edits before i realized it wasn't on).

**Comment by CraigClark** [comment]
@NicoledeGreef are we OK to close this now?

**Comment by NicoledeGreef** [comment]
@CraigClark i tagged this one as Sprint 3 and noted a dependency on #93
Let's leave it open until we discuss and make some amendments to the doc (Unique Identifier, Information Schedule, taxonomic values, etc.)

**Comment by CraigClark** [comment]
I'm closing this as the architecture is now a living doc in the BC SharePoint site. Refineing it will be an ongoing process.
