### ISSUE TITLE
investigate Book content not displaying revisions when changes are made

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#540]
Steps to recreate:

1. Make a minor edit was made to a node and save it
2. Click on Revisions tab
3. Note that there is no new revision logged

**Comment by chrislaick** [comment]
The problem was `$form['revision_information']['#access'] = FALSE;` not only hides the field from the node and node edit form, but it also destroys the value, and thus no new revisions are saved. Fixed by setting `#value` to TRUE.

**Comment by chrislaick** [comment]
Deployed to DEV and TEST.

**Comment by NicoledeGreef** [comment]
Edited Book content in Test environment and Revisions are now populating as expected.

**Comment by chrislaick** [comment]
Deployed to PROD.

**Comment by NicoledeGreef** [comment]
Thanks for the swift attention and fix, @chrislaick
