### ISSUE TITLE
Prevent tagging the same series multiple times to a single MR

### ISSUE THREAD

**Issue by david-fong-bc** [bcgov/MFIN-Data-Catalogue#549]
## Describe the bug
When editing a MR's "Section 1: Details", the same series can be added multiple times.

## To reproduce
Steps to reproduce the behaviour:
1. Create a MR
2. Navigate to edit section 1
3. Add a series
4. Click "Add another item" and then add the same item from step 3 in the new slot

## Notes

Can potentially use the "Chosen" Drupal module from ESS (might need to add it to bcbb).

## Expected behaviour
- The dropdown autocomplete does not show series which have already been added to the MR.
- Attempting to manually set (without autocomplete) a series slot to one which has already been added informs the user that it has already been added and rejects the operation.

**Comment by david-fong-bc** [comment]
> Attempting to manually set (without autocomplete) a series slot to one which has already been added informs the user that it has already been added and rejects the operation.

Or maybe it would be better to just have the server automatically remove any duplicates that the user manually enters before writing to the DB?

**Comment by chrislaick** [comment]
Deployed to DEV and TEST. Marking Ready for QA.

**Comment by david-fong-bc** [comment]
@chrislaick It looks like the change hasn't reached TEST yet, but I see it in DEV and also noticed that the selected items get sorted alphabetically, which I think is a nice touch.

**Comment by chrislaick** [comment]
@david-fong-bc Oops sorry my mistake. This is now deployed to TEST.

**Comment by david-fong-bc** [comment]
@chrislaick I just verified the fix in TEST. Looks good! I also noticed it automatically removes pre-existing duplicates when opening the edit interface. Thanks for the fix :)

**Comment by NicoledeGreef** [comment]
I agree - very nice solution to the issue.
