### ISSUE TITLE
Enable API user to create and edit field_primary_responsibility_org

### ISSUE THREAD

**Issue by david-fong-bc** [bcgov/MFIN-Data-Catalogue#564]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

I'm currently performing research on the capabilities and usability of [the Drupal JSON:API Module](https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module) that we have (some preliminary research was performed before, and now I'm continuing that work). My end goals are to figure out how to create, edit, publish, and (potentially) delete metadata records.

I've currently had reached success in creating and editing, and am running into an issue where I cannot set the Office of Primary Responsibility when creating or editing. The JSON:API module returns a 404 response. I also observed that when using the API and creating a new MR without setting OPR, it does not [get defaulted to the API user's organization](https://cat.data.fin.gov.bc.ca/documentation/creating-metadata-record#:~:text=By%20default%2C%20the%20Organization%20you%20belong%20to%20will%20be%20applied%20as%20OPR%20for%20the%20record) (which I don't see as an immediate issue). The API user I am using is the Drupal user account ["no-reply-svc-property-taxation at gov dot bc dot ca" in the TEST environment](https://test.cat.data.fin.gov.bc.ca/user/91). That account is configured with the API user role. I believe this behaviour is according to permission configuration:

This is the configuration for the API user role:

https://github.com/bcgov/MFIN-Data-Catalogue/blob/96c3728fdf123cf870f0d1eaf7eb9759d45409bb/config/sync/user.role.data_catalogue_api_user.yml#L59

https://github.com/bcgov/MFIN-Data-Catalogue/blob/96c3728fdf123cf870f0d1eaf7eb9759d45409bb/config/sync/user.role.data_catalogue_api_user.yml#L61

And compare with the Admin role:

https://github.com/bcgov/MFIN-Data-Catalogue/blob/96c3728fdf123cf870f0d1eaf7eb9759d45409bb/config/sync/user.role.data_catalogue_administrator.yml#L93

https://github.com/bcgov/MFIN-Data-Catalogue/blob/96c3728fdf123cf870f0d1eaf7eb9759d45409bb/config/sync/user.role.data_catalogue_administrator.yml#L143

https://github.com/bcgov/MFIN-Data-Catalogue/blob/96c3728fdf123cf870f0d1eaf7eb9759d45409bb/config/sync/user.role.data_catalogue_administrator.yml#L145

https://github.com/bcgov/MFIN-Data-Catalogue/blob/96c3728fdf123cf870f0d1eaf7eb9759d45409bb/config/sync/user.role.data_catalogue_administrator.yml#L200

https://github.com/bcgov/MFIN-Data-Catalogue/blob/96c3728fdf123cf870f0d1eaf7eb9759d45409bb/config/sync/user.role.data_catalogue_administrator.yml#L202

This issue of being unable to set OPR via API doesn't have huge impacts on my current exploration, but I believe it is the reason why I'm unable to use the API to delete records I created via API. The API role permissions has (note the qualifier "`in_org`"):

https://github.com/bcgov/MFIN-Data-Catalogue/blob/96c3728fdf123cf870f0d1eaf7eb9759d45409bb/config/sync/user.role.data_catalogue_api_user.yml#L35

Since I can't set OPR via this API user, I'm guessing the `in_org` condition can never be met.

## Describe the idea

At least for my current exploration of the API capabilities and usability, I would like to be able to create the OPR field and edit it on metadata records that I created through the same API user. I'm guessing that means adding the following to the API user role configuration: `create field_primary_responsibility_org` and `edit own field_primary_responsibility_org`.

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
@danhgov @chrislaick As Drupal admins, would one of you be able to toggle the permissions for the API user role in the Test environment (described above)?

**Comment by chrislaick** [comment]
> @danhgov @chrislaick As Drupal admins, would one of you be able to toggle the permissions for the API user role in the Test environment (described above)?

I've made the live change on TEST, however it's not persisted/deployed via code yet. @david-fong-bc can you confirm you want this change deployed after your testing?

**Comment by david-fong-bc** [comment]
@chrislaick thanks. I'll give it a try soon today. Out of the two permissions I highlighted- `create field_primary_responsibility_org` and `edit own field_primary_responsibility_org`, I think the one for creating will be a necessary change for the JSON:API module to be usable to create new metadata records. For the editing permission, I'm not sure yet whether that will be necessary for what we may use this API for in the future.

So @NicoledeGreef, does it sound good to you to deploy just the addition of `create field_primary_responsibility_org` for the API role, and leave `edit own field_primary_responsibility_org` for future discussion?

**Comment by david-fong-bc** [comment]
@chrislaick I gave it a try and it works. I can create a new MR with OPR set to PTB, edit it to set it to something else, and set it back to PTB.

Sorry for flip-flopping, but I'm now thinking it's fine and good for the API role to be granted _both_ `create field_primary_responsibility_org` and `edit own field_primary_responsibility_org`, since I assume that for any MR created via API, the field that says who authored/owns the MR (which I'm guessing is `uid`?) will be changed away from the API user (I think Nicole said users with the Admin role can change authorship\*). So even if it has that permission, it'll only have it until the new MR is off to the non-API user who will take care of the MR. I.e. It won't have it longer than it needs to have it. Does that sound good to you, @NicoledeGreef?

---

\*Maybe for future discussion whether it'd be good to enable the API role to edit the `uid` field, assuming that that's the backend side of changing who is considered the "author" of a MR. I tried editing `uid` via API just now and got a 404 error, which I assume was translated to 404 from 403 (Forbidden).

**Comment by NicoledeGreef** [comment]
As we don't anticipate giving the API user role/Drupal accounts to other parties (they will be internal to our team) I think it's fine to leave the ability to set/edit OPR with the API role. What's unclear to me currently is whether the `create field_primary_responsibility_org` permission is needed for that. I am thinking that perhaps `create field_primary_responsibility_org` is the permission required in order to edit the Organization taxonomy. We should look into this and confirm before adding both `create field_primary_responsibility_org` and `edit field_primary_responsibility_org` to the API user role.

**Comment by chrislaick** [comment]
From a general perspective, if a user has create permissions, it's always advisable to have edit permissions as well. Sometimes people make mistakes and need to correct them later. As for the permissions required to edit the Organization taxonomy, that's a separate permission under the Taxonomy module:

- Organization: Create terms
- Organization: Delete terms
- Organization: Edit terms

Of which, Data catalogue administrator and Data catalogue manager are the only roles currently enabled for these permissions.

> *Maybe for future discussion whether it'd be good to enable the API role to edit the `uid` field, assuming that that's the backend side of changing who is considered the "author" of a MR. I tried editing `uid` via API just now and got a 404 error, which I assume was translated to 404 from 403 (Forbidden).

As of Oct 15, the 403 to 404 redirect is no longer active in DEV and TEST. If you're receiving a 404 in DEV/TEST the page doesn't exist. See: https://github.com/bcgov/MFIN-Data-Catalogue/issues/507 in Ready for QA.

**Comment by david-fong-bc** [comment]
Confirming: I just tested in the TEST environment using the API to delete an MR I created via API with OPR set to the API user, and it now works (which is a good thing, I think).

**Comment by NicoledeGreef** [comment]
To (hopefully) clarify: the API role should not be able to create or edit terms in the Organization taxonomy or other taxonomies. That ability should stay with Drupal and Catalogue Admins.

The API Role _should_ be able to set an OPR value in a metadata record based on the terms already present in the Organization taxonomy.

Have we given the API role more than it should have?

**Comment by chrislaick** [comment]
With the two new permissions, the API role is not able to create/edit taxonomy terms in Organization vocabulary or any other vocabulary.

Merged to 1.0.x and deployed to DEV and TEST.

**Comment by david-fong-bc** [comment]
I just tested in DEV and TEST and I am able to use API set OPR when creating a new MR, edit OPR, and delete the created MR when it has the same OPR as the API user (and not when it has a different OPR or has no OPR yet, which is the specified behaviour in the documentation).

**Comment by NicoledeGreef** [comment]
@david-fong-bc  - would you please check this in Production? If all is as expected we can close this ticket.

**Comment by david-fong-bc** [comment]
@NicoledeGreef Just tested ([MR now deleted](https://cat.data.fin.gov.bc.ca/node/245)) and it looks good! I can create and edit OPR for MRs via API in PROD.

Thanks again, Chris! This will really help us leverage the API :)
