### ISSUE TITLE
Reports and Metadata records can be printed

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#57]
PrintCSS

**Comment by CraigClark** [comment]
It's good practice to make everything printable if possible. Paper isn't the only thing people print to. PRint to PDF is pretty widely used and that uses the print style sheet.

**Comment by CraigClark** [comment]
There are two branches for this ready for merge, 

The base-build covers most things that will be removed or altered on print.

There are a few print styles in the dc_theme that deal with project specific display

- <https://github.com/bcgov/bcbb-theme/tree/18-print-style-sheet>
- <https://github.com/bcgov/MFIN-Data-Catalogue/tree/57-reports-and-metadata-records-can-be-printed>

**Comment by CraigClark** [comment]
@NicoledeGreef I did this one, so someone else needs to test. You can test by going to anything in the DC and doing a print preview.

**Comment by CraigClark** [comment]
@NicoledeGreef this might be a candidate for the demo

**Comment by NicoledeGreef** [comment]
I checked a bunch of things and I liked the clean look of the printable documents. My only question is: can we strip out the report criteria for the Reports and only get the resulting content?

If it's easy to do, it would make things cleaner (similar to CSV export):

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/d6bf5109-3ed2-4d15-ae27-d8180c48673c)
