### ISSUE TITLE
Update to Drupal v10.3

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#573]
We need to update the Finance Data Catalogue to Drupal v10.3

Version 10.3 info: https://www.drupal.org/project/drupal/releases/10.3.0

**Comment by chrislaick** [comment]
Deployed to DEV and TEST.

**Comment by NicoledeGreef** [comment]
In Test (incognito), I:

- [x] logged in as an admin user
- [x] was able to edit and save my test account's permissions
- [x] search based on key words: "assessment", "fruit", "fruitsation"
- [x] add and remove Bookmarks
- [x] see the Bookmarks reflected in my dashboard and access them
- [x] get notified as an editor that i have records that need review (expected early sunday am)
- [x] save searches
- [x] access saved searches
- [x] see reports under my dashboard
- [x] get accurate results on metadata metrics report
- [x] get accurate results using the query builder reporting tool
- [x] see relationships reflected accurately in the dependencies report
- [x] see accurate incomplete IM report 
- [x] facet based searches
- [x] login flow for IDIR users
- [x] logout flow for IDIR users --> invalid URI message as noted in #507 
- [x] login flow for Drupal accounts using showCore parameter --> seems to push me to the IDIR user login dialogue
- [x] need to test visibility restrictions but showCore item is preventing that
- [x] change a user's org and see it reflected in the interface and visibility

**Comment by chrislaick** [comment]
@NicoledeGreef #507 has been deployed to DEV and TEST. I can't seem to replicate the issue you're having with showCore parameter, as it's working for me.

**Comment by chrislaick** [comment]
Ah, I now understand testing of visibility restrictions with showCore. Unfortunately, this can't be easily tested as a Data Catalogue administrator. Navigating to a page with visibility restrictions forces an automatic login, and as a Data Catalogue administrator you'll be able to see all records. If you can pair up with David, you can try removing your IDIR account's role as Data Catalogue administrator and test the functionality. After validating, you can restore your role.

**Comment by david-fong-bc** [comment]
@NicoledeGreef Chris and I tested the above together. He temporarily removed my IDIR account's admin role, and then we verified that when I then log out of my IDIR account and then try to visit a page I don't have access to, I get sent to select a microsoft account for login, and then get redirected to the homepage with the message "Access denied. Your account permissions do not match the record you are trying to reach."

**Comment by NicoledeGreef** [comment]
> Ah, I now understand testing of visibility restrictions with showCore. Unfortunately, this can't be easily tested as a Data Catalogue administrator. Navigating to a page with visibility restrictions forces an automatic login, and as a Data Catalogue administrator you'll be able to see all records. If you can pair up with David, you can try removing your IDIR account's role as Data Catalogue administrator and test the functionality. After validating, you can restore your role.

That's why I have a non-admin Drupal account for testing...so I can use my IDIR (Admin) account to change settings on my Drupal account to test different scenarios.

**Comment by david-fong-bc** [comment]
I went through the documentation and followed along in TEST looking at the various pages and features to see that nothing looks obviously broken. Things look okay.

I did noticed one issue- in TEST, the "Updated" indicator in the bookmarks listings don't get removed after I view the MR that was updated. It's working fine in DEV but not in TEST.

**Comment by NicoledeGreef** [comment]
Thanks @david-fong-bc  - I checked the Updated issue you mention in test and it disappeared for me. I clicked the back button and it was still there but when I refreshed the page it disappeared.

**Comment by david-fong-bc** [comment]
@NicoledeGreef interesting! I'm still getting what looks like the wrong behaviour. I can show you what I see tomorrow over call if you have time- maybe in the morning.
