### ISSUE TITLE
Active directory should be used to control access / levels

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#58]
QUESTIONS:

1. Is active directory the right technology, or should this Office365?
2. Is the OpenShift stack able to connect to AzureAD / Office365 endpoint for authentication?  
3. Do we have enough details in the response to place users into specific organizations and providing the correct access controls in place?

**OP timer**

---

## User story

As a …

I want to …

So that …

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
5. second test step …
6. etc …

**Comment by CraigClark** [comment]
I'm not sure this is a Quick win. It's either that or a lot if difficulty. What we need to do is see if we can get an group out of AD and map it to a Drupal role. Joel ad OP has done this sort of thing before.

**Comment by CraigClark** [comment]
Closing this. There is a duplicate issue at #127
