### ISSUE TITLE
Make it intuitive for custodians and non-data people

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#59]
Aspiration not a feature.  Continuous engagement and improvement leads to this.

**Comment by CraigClark** [comment]
This looks like a development principal, not really as feature to be build.

**Comment by NicoledeGreef** [comment]
I agree @CraigClark though it might inspire some ideas; it's a good thing not to lose sight of as we progress.  Maybe we could log the principles somewhere...Readme? Wiki?
