### ISSUE TITLE
A dashboard widget to show most Bookmarked metadata

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#61]
Bookmarking nodes is a feature built into the MFIN Data Catalogue.  Leverage this to show metrics about levels of general interest in metadata records.

**OP timer**

---

## User story

As a Metadata Author
I want to gain sight into how much interest there is in the assets I've created and maintain
So that I know there is value in maintaining my records well.

As a Product Owner, 
I want to incentivize the appropriate use of the Data Catalogue 
so that we build a culture of excellence in data and metadata management.

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
This functionally complete.
