### ISSUE TITLE
Determine if a workflow-based approval process is desirable/needed

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#63]
QUESTIONS:

Confirm typical approval workflow with roles:

Content inputter creates datasets and can only set workflow state to “In review”
Data custodian is notified via email and can see dataset on their dashboard that is in the state “In review”
Data custodian reviews dataset and publishes it when read.
Content inputter can create a new draft of the dataset and when done updating, can set the workflow state to “In review” again.
Data custodian can “Archive” the dataset.  This marks the data set as Archived and renders it no longer searchable unless “Search archived” is selected.
Data custodian can delete the dataset.

**PO needs to sketch out one or more workflow approaches vs. non-workflow approaches and play them back to business domain SMEs to see which apply to them before making a decision that affects all domains.**

**Comment by NicoledeGreef** [comment]
@lkmorlan @CraigClark please consider the attached Simple Workflow and let me know if you think it is a challenging pivot to make later in the process - what would be the order of magnitude effort (Low, Med, High, VeryHigh) to pivot to a (very) simple workflow from a no workflow approach?

[Simple_Workflow.pdf](https://github.com/bcgov/MFIN-Data-Catalogue/files/12921030/Simple_Workflow.pdf)

**Comment by NicoledeGreef** [comment]
For now, no workflow is acceptable and we'll proceed in that way.  We'll pivot later if needed.

It's technically feasible to implement later. It's not difficult to implement workflow but the hooks into the app making it more valuable represent some work.
