### ISSUE TITLE
Data Catalogue Onboarding and Engagement Strategy

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#64]
This ticket is a repository for notes pertaining to developing a strategy for onboarding and engaging business domains with respect to the Finance Data Catalogue.

**Principles**
- Take a non-invasive approach to Data Governance: recognize what people are already doing in the space of data management and co-create a path towards improving quality and trust in the assets
- Employ metadata as the language of Data Governance in the Ministry
- Regardless of the tool(s) being used, metadata will not govern itself

**Governance**
- "Governance"  = as per Seiner, it is the execution and enforcement of authority over data, but he admits that to some this definition makes it seems like the Data Police are moving in
- "Governance" is essentially the formalization of accountability for producing, using, destroying, ___________ datasets and related entities (e.g. forms and reports)

Core components of a Governance framework can include (+/-): 
- Data: Assets being governed and quality improved
- Roles: Formal Accountability for Data Governance and Information Quality
- Processes: Application / Enforcement
- Communications: Education, Training, and Awareness
- Metrics: Measurements and KPIs
- Tools: Artifacts Purchased and Developed

Levels of a Governance framework can include (+/-):
- Executive: Senior Leadership
- Strategic: Business & Tech Mgmt
- Tactical: SMEs
- Operational: Daily Job Function
- Support: Functional Mgmt (includes partners such as IT, PMO, Reg & Compliance, Info Security, Legal & Audit, Comms, HR)

Governance Framework template available to help us sketch it out and play it back.

**Engagement With Business Domains**
_People_
- identify who are the domain's Data Custodians (usually an ED; this role is derived from the [BCGov Data Management Policy](https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/policies-procedures/data-management-policy/data_management_policy_v10.pdf))
- As per the DMP, Data Custodians "have the responsibility to:
    • Oversee the management of data throughout its lifecycle
    • Ensure intended users of the data are supported and trained appropriately
    • Meet the requirements of applicable laws, policies, and standards, including this Policy"
- identify who are the domain's Data Stewards?
- how does IT apply to the stewardship aspect (is there a need to identify IT Data Stewards for each domain?)

_Assets_
1. identify the items (datasets, forms, and reports) to be assessed
2. determine if there is ROT (Redundancy, Obsolescence, Triviality) at play and possibly shorten the list
3. identify the items to be catalogued
4. work with the domain SMEs  to determine the metadata values for the items
5. research to fill any gaps (may require IT support)
6. prepare metadata for loading
<Note: review 7-10 with OpenPlus>
7. loading metadata into staging area for review before loading to Production(?)
8. domain reps review metadata within the staging site
9. seek sign-off
10. load and publish metadata (incl. data dictionary columns) into Production

**Comment by NicoledeGreef** [comment]
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/2ff34e7f-cfaf-43ce-a5cf-7e0e167d703d)

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/5e09782d-7c4a-49c0-bf1d-25ac15a5807f)

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/7932f81a-1740-4610-a01d-52e056e2e52c)

**Comment by NicoledeGreef** [comment]
Being tracked in JIRA

**Comment by mjmcclung** [comment]
@NicoledeGreef can you please make sure I am engaged in discussions on this topic?  This directly relates to the IM awareness content I am working on.
