### ISSUE TITLE
Report / dashboard accessibility

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#66]
QUESTIONS:

Does BC use a tool to measure WCAG or do they engage companies to provide an audit service?

**OP timer**

---

## User story

As a Product Owner
I want to ensure that the MFIN Data Catalogue meets BC Gov standards for [Web Content Accessibility Guidelines (WCAG) 
So that the product is inclusive and supports a range of abilities through compatibility with assistive technology.

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
I will inquire with the Accessibility CoP I recently joined about tools or audit capabilities.

At minimum I think we should try to hit these:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/ec6ca86f-22ee-44fc-9062-30aad92d0dd9)


**Resources:**

Language: https://www.w3.org/WAI/WCAG21/Understanding/language-of-page.html

Session Expiry: https://cccaccessibility.org/web-1/web-developer-tutorials/accessible-timeouts

Interactive Elements: https://developer.chrome.com/docs/lighthouse/accessibility/interactive-element-affordance/

Alt text for image is self-explanatory.

**Comment by CraigClark** [comment]
What should happen here is BC decides on a standard, for example WCAG 2.1 AA and aspire to meet it. We will never get 100% accessibility, but we can get close.
@NicoledeGreef

**Comment by NicoledeGreef** [comment]
Re: accessibility standards please see:
https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/web-content-development-guides/web-standards

**Comment by lkmorlan** [comment]
@NicoledeGreef Does it need to meet WCAG 2.0 or 2.1?

**Comment by NicoledeGreef** [comment]
@lkmorlan let's shoot for WCAG 2.0 - it seems to be what most teams are targeting at the current time.

**Comment by NicoledeGreef** [comment]
WCAG 2.0 AA is the target

**Comment by NicoledeGreef** [comment]
[Accessibility and Inclusion Toolkit](https://www2.gov.bc.ca/gov/content/home/accessible-government/toolkit/accessible-digital-content)

**Comment by NicoledeGreef** [comment]
The Accessibility measure in the contract actually states "meets WCAG 2.0" as being necessary in the 3rd phase ("Implementation").
