### ISSUE TITLE
Entry differentiate tool (old vs new, current vs proposed)

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#67]
**OP timer**

---

## User story

As a …

I want to …

So that …

## This feature support the following requirements

Interpreted by @NicoledeGreef as "Metadata record diff display (old vs new, current vs proposed)"

## Additional context

Was logged in the Matrix as:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/c3469869-af04-42ff-ab46-1b905ad736b5)

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
This is at least partially covered by #87; only the "proposed" aspect is not. Remains to be seen if that is raised again during user review.
