### ISSUE TITLE
Branding my screen for my brand on division

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#69]
QUESTION:
Do we really want to allow users to change the branding for their particular instance of their dashboard or the tool itself?

**Comment by NicoledeGreef** [comment]
It is not currently a requirement to put branding changes in the hands of the user, **but** we do want to set up different experiences for users in different branches within the Ministry (this would include different labeling on the screen - in tune with their "brand", styling choices like colour, placement of content according to their reps' states preferences, etc.).

**Comment by NicoledeGreef** [comment]
this is referenced in #176

**Comment by NicoledeGreef** [comment]
#176
