### ISSUE TITLE
Tables, graphs, other visuals to see the data

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#70]
Individual UI components will get their own tickets.

**Comment by CraigClark** [comment]
@sangtrinh @NicoledeGreef , would this be visualization on the data set or the dashboard or a bit of both?

**Comment by NicoledeGreef** [comment]
Not sure of the context for this particular ticket. It is nice to be able to preview the data (first x rows) in tabular format when applicable.

**Comment by NicoledeGreef** [comment]
Closing this ticket as it is covered elsewhere (see #137)
