### ISSUE TITLE
Visual depiction of dataset quality

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#71]
**OP timer**

---

## User story

As a …

I want to …

So that …

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by CraigClark** [comment]
>**Note**: will need to figure out indicators for this.

**Comment by CraigClark** [comment]
this could be related to #70

**Comment by NicoledeGreef** [comment]
Age of metadata (how long since last update)?
Completeness or quality of attribute values?
This feature ask may be covered off by other tasks we're closing it for now.

**Comment by NicoledeGreef** [comment]
Food for thought for the next time we are thinking about data quality ratings @CraigClark @sangtrinh 

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/223f370d-7249-4d88-b4e4-924093a591c4)
