### ISSUE TITLE
Seek clarity: Shared data dictionary; collaboration and comments

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#76]
QUESTIONS:

1. Shared taxonomy vocabulary yes
2. Comments can be added
3. Forum / discussions ?
4. Voting
5. Like / dislike?
6. Other collaboration tools?

**OP timer**

---

## User story

As a …

I want to …

So that …

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
6. second test step …
7. etc …

**Comment by CraigClark** [comment]
- shared vocabulary, this is a controlled vocabulary in Drupal. 
- comments - lets not do this for now, not the best, but stick with email for now
- find out from stakeholders what the intent is of this
- find out intent behind voting
@NicoledeGreef

**Comment by NicoledeGreef** [comment]
we have other tickets around data quality so we're shutting this ticket.
