### ISSUE TITLE
A vote button for likes or flagging issues

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#78]
QUESTIONS:

1. Should these be part of the metrics viewable by the public?
2. Should it be viewable by data custodians and compared against other datasets within the division/across ministries?

**OP timer**

---

## User story

As a …

I want to …

So that …

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by CraigClark** [comment]
@sangtrinh should this be merged in with #30 ? OR would this be a typical 'report an issue' type thing that goes to an business owner?

**Comment by NicoledeGreef** [comment]
see #91
