### ISSUE TITLE
Metadata reports are useful source of feedback for metadata improvement

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#81]
Each report will have its own issue ticket.

**Comment by NicoledeGreef** [comment]
There are options for enabling reports based on Drupal data: core Views module and API to PowerBI, etc.

**Comment by NicoledeGreef** [comment]
Have added some issue tickets for desired reports:

#208 
#209 
#210 
#211 
#212

**Comment by CraigClark** [comment]
Thanks for these Nicole.

Some of these we can do in Drupal and some will need to be analytics
software.

Regards

**Comment by NicoledeGreef** [comment]
Closing this ticket as there are now individual report and dashboard tickets.
