### ISSUE TITLE
Consistent use of jargon, reduce use of synonyms

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#83]
QUESTIONS:

Is this addressed by controlled vocabularies?

**OP timer**

---

## User story

As a …

I want to …

So that …

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
similar to #76 (@NicoledeGreef to follow up)

**Comment by NicoledeGreef** [comment]
In Help files, add some content around this.

**Comment by CraigClark** [comment]
We can use taxonomies to leverage the best of both worlds

**Comment by NicoledeGreef** [comment]
Thinking this is a Business Glossary
