### ISSUE TITLE
Set required fields

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#84]
QUESTIONS:

Should be all attributes always filled out.  If they are missing from the dataset, they are missing.  Not sure if there’s a way to tell since the data custodian is responsible for ensuring all attributes are filled.

Maybe make required fields in Drupal to ensure that they are filled?

**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4732951108

---
## List of required fields 

- [x] @CraigClark to provide @NicoledeGreef with a spreadsheet list of fields
- [x] @NicoledeGreef to flag the required fields for Data, From, and Reports

- [x] On the "Build" page, the "Publish" button does not appear unless all required fields are completed. This can be checked can calling `$node->validate()`.

### Automated functional tests

- [x] I have written functional tests for this feature

**Comment by CraigClark** [comment]
As Sang mentioned, this has potential to cause issues. If my data set doesn't use all the fields, a list of empty attributes could lead me to believe there is something missing from the data set when there isn't. 

Drupal does have required fields. Using required fields would render this moot as you can't publish if there is an empty required field.

**Comment by NicoledeGreef** [comment]
We need to scope out which fields are mandatory versus optional (the ones listed in the Core Metadata Standard should be mandatory + others we deem as mandatory).

Let's add this to the agenda at the meeting about INFO SCHEDULE on July 18

**Comment by CraigClark** [comment]
@NicoledeGreef Attached is a list of fields in use on the data catalogue. If the machine labels are not clear, you can check against the [data set](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/metadata-fields) and [data dictionary](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/data-dictionary-fields)  fields in the help guide.

Some fields are required for other functionality. I have listed those as _Y_. Some fields are completed pragmatically. Those are listed as _NA_.

Could you please fill out the rest of this sheet and get it back to me?



[BC_MFIN_DC_fields.xlsx](https://github.com/bcgov/MFIN-Data-Catalogue/files/13480855/BC_MFIN_DC_fields.xlsx)

**Comment by NicoledeGreef** [comment]
@CraigClark you can find the completed sheet [here](https://bcgov.sharepoint.com/:x:/r/teams/06981/_layouts/15/Doc.aspx?sourcedoc=%7BB7916BF2-A2B1-470A-8A5E-5BCDC4C93EB7%7D&file=BC_MFIN_DC_fields.xlsx&action=default&mobileredirect=true).

**Comment by CraigClark** [comment]
This task is specific to required fields. There are some fields where the requirement and/or visibility are conditional. There is place holder task for that, #269

**Comment by CraigClark** [comment]
A PR has been submitted for this https://github.com/bcgov/MFIN-Data-Catalogue/pull/278

>[!IMPORTANT]
> - that conditional fields will be part of the next release.
> - source system could not be set as required at this point because it is conditional

**Comment by CraigClark** [comment]
re opening, some were missed

**Comment by CraigClark** [comment]
Required fields have been updated and submitted to @lkmorlan for review/merge. see https://github.com/bcgov/MFIN-Data-Catalogue/tree/84-update-required-fields

**Comment by CraigClark** [comment]
reviewed and merged
