### ISSUE TITLE
Changes in datasets, who made those changes, what are they impacting?

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#87]
**OP timer**

---

## User story

As a reader of content in the Data Catalogue

I want to be able to see changes (revisions) of the metadata record (who, what, when)

So that I can be well informed if I have dependencies on a given dataset.

## Additional context

Revision log is available via Drupal; even diff is available
Should be added to the Help Guide

**UsedInProducts** leads to contacts associated with downstream products that would be impacted by a model change 

Auto-notifications not in scope of this ticket; could be a different item for consideration if users communicate a need.

## Proposed solution

Permissions on a logged in user will determine if they can revert to an earlier version; anyone else would be able to see the revs but not action based on them.

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
This is covered in other tickets so closing.
