### ISSUE TITLE
Prepare Security Threat Risk Assessment (STRA) for the DC

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#89]
**OP timer**

---

## User story

As a …

I want to …

So that …

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
A SOAR was prescribed and prepared by the Privacy team.
