### ISSUE TITLE
Notify data custodians when dataset metadata is out of date

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#90]
QUESTIONS:

Is there an update frequency field we can use to trigger this?  The last set of datasets sent indicated that it was "Ad-hoc" which does not help with this functionality.

Currently the content architecture does not contain an update frequency field, however this is easily addable.

**OP timer**

---

## User story

As a …

I want to …

So that …

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

### Automated site tests

- [ ] I have written site tests for this feature
- [ ] I have run the site tests and they pass

### This feature requires manual testing

1. first test step …
2. second test step …
3. etc …

**Comment by NicoledeGreef** [comment]
relates to #28
