### ISSUE TITLE
Meeting to discuss UNIQUE IDENTIFIER and INFO SCHEDULE needs

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#93]
## Additional context

UNIQUE IDENTIFIER and INFORMATION SCHEDULE are BCGov core metadata standard requirements.

There was some misinterpretation initially on what these meant and before we go to far, we should clear this up.

## Proposed solution

Arrange a meeting that includes MM, CB @CraigClark, @sangtrinh, @lkmorlan 

## Definition of done (DoD)
- arrange discussion meeting
- hold discussion
- consensus as to what these fields should be in the context of MFIN Data Catalogue is achieved and documented

**Comment by NicoledeGreef** [comment]
meeting scheduled for July 17

**Comment by CraigClark** [comment]
Related #74

**Comment by CraigClark** [comment]
I'm not sure what _info schedule_ refers to.
