### ISSUE TITLE
Research Item: Dashboard options 

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#94]
**OP timer**

---

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Estimated level of effort

- 1 day

**Comment by CraigClark** [comment]
I investigated the chart module and met with Joel on this as he has done this sort of thing in the past. We have a lit of options for visuals, charts, graphs, colour coding and icons. The challenge is going to be that for these to work, we need numbers. So for example, if we want a colour bar that indicates the quality of a data set, we need to figure out how to represent quality numerically.
