### ISSUE TITLE
testing documentation

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#96]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4736444524

---

## This feature support the following requirements

[Master test plan](https://openplus.monday.com/boards/3958997205/pulses/4157359213)

## Additional context

Write the testing documentation in the wiki for the data catalogue project. New code is constantly being deployed the the data catalogue project by multiple people. With this approach, it is ideal to have automated tests so that there are no blockers while we wait for the time consuming process of manual testing.

## Proposed solution

Documentation should include:

1. Describe the overall process of what automated test do and why we use them.
2. Where to find automated test scripts
3. Types of automated tests
4. How to run automated tests
5. What to do if tests fail
6. Decision making process for failures due to upstream code

## Estimated level of effort

- 2 days

## Definition of done (DoD)
- [x] Documentation is available on the wiki for data-catalogue
- [ ] BC technical team accepts the documentation

>**Note**: All documentation in the wiki are considered _living documents_ and will be changed as needed after this task has been completed.

**Comment by CraigClark** [comment]
@lkmorlan I've done what I can with this, can you please review and answer questions where you are flagged?

see https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Test-plan

**Comment by lkmorlan** [comment]
When running tests in DDEV, I run `ddev ssh` and then run the tests inside. There may need to be tweaks to `config/phpunit.xml` to allow it to run in DDEV.

**Comment by CraigClark** [comment]
@NicoledeGreef Could you please review the test plan and let us know if this approach works for you?

**Comment by NicoledeGreef** [comment]
@CraigClark the testing documentation looks good to me.  Just the section "Running tests" could use an update as the question to @lkmorlan is still there and he has commented above about that.  I like the flow diagram under "Evaluating failures". Thanks for putting this together!

I'd like @chrislaick and @danhgov to take a look at this once the update is made.

**Comment by CraigClark** [comment]
@NicoledeGreef I have added instructions for running tests in ddev as per Liam's comments. Ready for @chrislaick and @danhgov to review.

**Comment by chrislaick** [comment]
@CraigClark @NicoledeGreef  This looks good to me.
