### ISSUE TITLE
Update automated tests from sprint 1

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#98]
**OP timer**

use the timer for each listed ticket to track time.

---

There were features completed in the first sprint that did not have tests written.

Once the test plan is approved, validate that the following have been tested and passed:

> **Note**: Currently all search related features are failing automated tests because if an issue with the `bootstrap_layouts` module. This will be addressed at the next base-build meeting.

- [x] #49 
- [x] #36 
- [x] #22 
- [x] #21 
- [x] #35

**Comment by lkmorlan** [comment]
See also #109.
