### ISSUE TITLE
test CSV import of data dictionary for 1000 columns 

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#99]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a data curator I have some data sets that have up to 800 fields
I need confidence in the CSV import so that
managing the data dictionary is a smooth procedure.

## Describe the idea

Stemmed from @chrislaick 's question about limits as to number of fields at the Review for Sprint 2.

## Actions

- [ ] prep a 1000 column file and run a test

**Comment by CraigClark** [comment]
I tried this with a 1500 row csv.

1. upload csv took 1.24 seconds
2. import the csv took 33.8 seconds (note, environment will have a lot to do with this speed)
3. go to edit tab to publish and get error    
     
```
Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 69632 bytes) in /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Component/Utility/NestedArray.php on line 73

Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 65536 bytes) in /var/www/html/dv21.openplus.ca/html/core/lib/Drupal/Core/Database/Query/Merge.php on line 46

Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 65536 bytes) in /var/www/html/dv21.openplus.ca/html/core/includes/errors.inc on line 59

Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 65536 bytes) in Unknown on line 0

```

**Comment by NicoledeGreef** [comment]
@CraigClark Is it the same result using a 1000 row file? We think 800 is about the biggest.

**Comment by CraigClark** [comment]
@NicoledeGreef I have tests to run with 100, 500, 1000, 1500. I know 800 is the biggest, but since it's breaking at 1500, I'd like to know why.

**Comment by CraigClark** [comment]
Done see #20 comment
